/- replay: the class certificate 11211 (L1_1d, generated by gen_replay.py). -/
import ReplayCommon
import R11211_Assembly
import ZetaS.Cert.ChainV3

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace ZetaS.CertV2
namespace R11211

/-- the certificate of class 11211: the specification's instance, the root box, the tree of the shards. -/
def cert : Cert := ⟨classData [1,1,2,1,1], [((0 : ℚ),(141/16 : ℚ)),((0 : ℚ),(351/64 : ℚ)),((0 : ℚ),(351/64 : ℚ)),((0 : ℚ),(141/16 : ℚ))], T0⟩

/-- the literal instance of the shards is the specification's `classData`. -/
theorem data_eq : classData [1,1,2,1,1] = D_R11211 :=
  LIQ.ext' (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem cert_ok : Cert.check cert = true := by
  apply Cert.check_of_parts
  · decide +kernel
  · show Node.check (classData [1,1,2,1,1]) T0 [((0 : ℚ),(141/16 : ℚ)),((0 : ℚ),(351/64 : ℚ)),((0 : ℚ),(351/64 : ℚ)),((0 : ℚ),(141/16 : ℚ))] = true
    rw [data_eq]
    exact T0_ok

/-- the local inequality of class 11211 on the whole orthant (soundness chain `ChainV3`, L5_2). -/
theorem holds : (classData [1,1,2,1,1]).Holds := ChainV3.cert_check_sound cert cert_ok

end R11211
end ZetaS.CertV2
