/- replay: the class certificate 12221 (L1_1d, generated by gen_replay.py). -/
import ReplayCommon
import R12221_Assembly
import ZetaS.Cert.ChainV3

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace ZetaS.CertV2
namespace R12221

/-- the certificate of class 12221: the specification's instance, the root box, the tree of the shards. -/
def cert : Cert := ⟨classData [1,2,2,2,1], [((0 : ℚ),(607/64 : ℚ)),((0 : ℚ),(189/32 : ℚ)),((0 : ℚ),(189/32 : ℚ)),((0 : ℚ),(607/64 : ℚ))], T0⟩

/-- the literal instance of the shards is the specification's `classData`. -/
theorem data_eq : classData [1,2,2,2,1] = D_R12221 :=
  LIQ.ext' (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem cert_ok : Cert.check cert = true := by
  apply Cert.check_of_parts
  · decide +kernel
  · show Node.check (classData [1,2,2,2,1]) T0 [((0 : ℚ),(607/64 : ℚ)),((0 : ℚ),(189/32 : ℚ)),((0 : ℚ),(189/32 : ℚ)),((0 : ℚ),(607/64 : ℚ))] = true
    rw [data_eq]
    exact T0_ok

/-- the local inequality of class 12221 on the whole orthant (soundness chain `ChainV3`, L5_2). -/
theorem holds : (classData [1,2,2,2,1]).Holds := ChainV3.cert_check_sound cert cert_ok

end R12221
end ZetaS.CertV2
