/- replay: the class certificate 12212 (L1_1d, generated by gen_replay.py). -/
import ReplayCommon
import R12212_Assembly
import ZetaS.Cert.ChainV3

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace ZetaS.CertV2
namespace R12212

/-- the certificate of class 12212: the specification's instance, the root box, the tree of the shards. -/
def cert : Cert := ⟨classData [1,2,2,1,2], [((0 : ℚ),(19/2 : ℚ)),((0 : ℚ),(189/32 : ℚ)),((0 : ℚ),(189/32 : ℚ)),((0 : ℚ),(19/2 : ℚ))], T0⟩

/-- the literal instance of the shards is the specification's `classData`. -/
theorem data_eq : classData [1,2,2,1,2] = D_R12212 :=
  LIQ.ext' (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem cert_ok : Cert.check cert = true := by
  apply Cert.check_of_parts
  · decide +kernel
  · show Node.check (classData [1,2,2,1,2]) T0 [((0 : ℚ),(19/2 : ℚ)),((0 : ℚ),(189/32 : ℚ)),((0 : ℚ),(189/32 : ℚ)),((0 : ℚ),(19/2 : ℚ))] = true
    rw [data_eq]
    exact T0_ok

/-- the local inequality of class 12212 on the whole orthant (soundness chain `ChainV3`, L5_2). -/
theorem holds : (classData [1,2,2,1,2]).Holds := ChainV3.cert_check_sound cert cert_ok

end R12212
end ZetaS.CertV2
