/- replay: the class certificate 21222 (L1_1d, generated by gen_replay.py). -/
import ReplayCommon
import R21222_Assembly
import ZetaS.Cert.ChainV3

set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace ZetaS.CertV2
namespace R21222

/-- the certificate of class 21222: the specification's instance, the root box, the tree of the shards. -/
def cert : Cert := ⟨classData [2,1,2,2,2], [((0 : ℚ),(315/32 : ℚ)),((0 : ℚ),(49/8 : ℚ)),((0 : ℚ),(49/8 : ℚ)),((0 : ℚ),(315/32 : ℚ))], T0⟩

/-- the literal instance of the shards is the specification's `classData`. -/
theorem data_eq : classData [2,1,2,2,2] = D_R21222 :=
  LIQ.ext' (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem cert_ok : Cert.check cert = true := by
  apply Cert.check_of_parts
  · decide +kernel
  · show Node.check (classData [2,1,2,2,2]) T0 [((0 : ℚ),(315/32 : ℚ)),((0 : ℚ),(49/8 : ℚ)),((0 : ℚ),(49/8 : ℚ)),((0 : ℚ),(315/32 : ℚ))] = true
    rw [data_eq]
    exact T0_ok

/-- the local inequality of class 21222 on the whole orthant (soundness chain `ChainV3`, L5_2). -/
theorem holds : (classData [2,1,2,2,2]).Holds := ChainV3.cert_check_sound cert cert_ok

end R21222
end ZetaS.CertV2
