/-
Copyright (c) 2026 Oliver D'Souza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
SPDX-License-Identifier: Apache-2.0
-/
/-
ZetaShell — root of the family follow-up library (RH-72 follow-up; plan `mathsrh/rh72/LEAN_PLAN.md`, board
`mathsrh/rh72/lean_board/BOARD.md`). Integrated by L0_6 on 28 Sep 2026 from the work folders of L7_1 (architect),
L7_2, L7_3, L7_5, L7_6, L7_7, L7_8 and L7_9; mapping, checksums and census in
`mathsrh/rh72/lean_board/reports/L0_6_family_integration.md`. Later shifts: L0_7 (28 Sep; adds L7_10;
`L0_7_family_integration_2.md`) and L0_8 (1 Oct; adds L7_11, L7_12; `L0_8_family_integration_3.md`).

Layout (modules `ZetaShell.<Group>.<file name in the work folder>`):
  Challenge, Interfaces   the architect's Mathlib-only statement layer and the interfaces (their `sorry`s are the
                          architect's four headlines and two tree-form headlines, kept unchanged)
  Top.HeadlineReduced     the REDUCED headline statements (hypothesis `ZeroDensityInput` only): the statements of
                          record; with the proved implications to and from the architect's forms
  Cert/                   Track R: the kernel-checked rational certificate and `certS53`, `certD53` (level A)
  PNT/                    the medium prime number theorem (L7_2)
  Density/, Frame/, Top/  the architect's proved nodes Z1-Z3, B1, F2 and T1
  Defs/                   shared definitions of Track F (`TF_Defs`) and Lemma K (`LK_Defs`); `Defs.Unify` proves the
                          repeated ones equal
  Farey/, Lemma2/         Track F: signed Farey identity, rectangles, hole-edge mass, Lemma 1', Lemma 3 (A3),
                          Lemma 2 (b), (c) and the steps of Lemma 2 (a), Lemma P
  Design/                 the design layer at bandwidth 191/100 (L7_7)
  LemmaK/                 Lemma K and Theorem 1' (L7_3, L7_9); K2 of record = `gallagher_with_zero_set_corr`
  PropZ/                  the Proposition Z chain (L7_5)
  ShellS/, ShellK/        the Theorem S side (L7_10, L7_12); Theorem K and the Frobenius row (L7_10, L7_3)
  Skeleton/               every module that carries an open node (`sorry`), statements unchanged; the refuted
                          frozen statements `gallagher_with_zero_set` (K2) and `ring_le_primitive` (A⋆) are not in
                          the library, their corrected forms (`_corr`) are
The lakefile glob `ZetaShell.*` builds every module under `ZetaShell/`, whether or not it is imported here.
-/
import ZetaShell.Basic
import ZetaShell.Cert.R1_CplusBounds
import ZetaShell.Cert.R2_BshellMono
import ZetaShell.Cert.R3_ShellPayoffFormula
import ZetaShell.Cert.R4_CertS53
import ZetaShell.Cert.R5_D53
import ZetaShell.Cert.R5_ProfileL75
import ZetaShell.Cert.R5_S53
import ZetaShell.Cert.R6_AdmissibleOfL75
import ZetaShell.Cert.ShellCertQ
import ZetaShell.Cert.TR_Biv
import ZetaShell.Cert.TR_Bshell
import ZetaShell.Cert.TR_L75
import ZetaShell.Cert.TR_Poly
import ZetaShell.Cert.TR_Psi
import ZetaShell.Cert.TR_Q
import ZetaShell.Challenge
import ZetaShell.Defs.LK_Defs
import ZetaShell.Defs.TF_Defs
import ZetaShell.Defs.Unify
import ZetaShell.Density.Z1_ZDIToBulkLogFree
import ZetaShell.Density.Z2_Alpha0D1prime
import ZetaShell.Density.Z3_ThetaS53
import ZetaShell.Design.SD_A0_DesignAtM
import ZetaShell.Design.SD_A1_PolyEval
import ZetaShell.Design.SD_A2_ProfileQ
import ZetaShell.Design.SD_A3_Moments
import ZetaShell.Design.SD_A4_GevreyGate
import ZetaShell.Design.SD_A5_ExistsAt
import ZetaShell.Design.SD_A6_Exists
import ZetaShell.Design.SD_A7_Regime
import ZetaShell.Design.SD_A8_Scales
import ZetaShell.Design.SD_B1_Row2Lam
import ZetaShell.Design.SD_B2_Row9Lam
import ZetaShell.Design.SD_B3_TraceRow
import ZetaShell.Design.SD_B4_RvMLower
import ZetaShell.Design.SD_B5_NIIUpper
import ZetaShell.Design.SD_B6_Tail
import ZetaShell.Design.SD_B7_D0Bound
import ZetaShell.Design.SD_B8_Rates
import ZetaShell.Design.SD_C1_CWin
import ZetaShell.Design.SD_C3_EndsC1
import ZetaShell.Design.SD_D1_Display
import ZetaShell.Design.SD_F1_FromNodes
import ZetaShell.Design.SD_KBridge
import ZetaShell.Design.ShellDesignDefs
import ZetaShell.Farey.A1_SignedFarey
import ZetaShell.Farey.A1p_FarNorm
import ZetaShell.Farey.A1p_ReplaceCost
import ZetaShell.Farey.A1p_SmallPrimeNorm
import ZetaShell.Farey.AF1_HoleEdgeMass
import ZetaShell.Farey.Z6b_Rectangles
import ZetaShell.Farey.Astar_Gauss
import ZetaShell.Frame.B1_CountBridge
import ZetaShell.Frame.F2_ShellAssembly
import ZetaShell.Interfaces
import ZetaShell.Lemma2.A2P_S2_ConvSum
import ZetaShell.Lemma2.A2_FareyBasics
import ZetaShell.Lemma2.A2_InterfaceCheck
import ZetaShell.Lemma2.A2a_Main
import ZetaShell.Lemma2.A2a_S0_Lines
import ZetaShell.Lemma2.A2a_S1_Expansion
import ZetaShell.Lemma2.A2a_S2_CRT
import ZetaShell.Lemma2.A2a_S2_CRTExist
import ZetaShell.Lemma2.A2a_S2_Mobius
import ZetaShell.Lemma2.A2a_S2_OneClass
import ZetaShell.Lemma2.A2a_S2_Progression
import ZetaShell.Lemma2.A2a_StepDefs
import ZetaShell.Lemma2.A2b_DensityBound
import ZetaShell.Lemma2.A2c_Holes
import ZetaShell.LemmaK.LK9_K2_Aux
import ZetaShell.LemmaK.LK9_K4_Aux
import ZetaShell.LemmaK.LK9_K4b_Aux
import ZetaShell.LemmaK.LK9_K5_Asym
import ZetaShell.LemmaK.LK9_K5_Main
import ZetaShell.LemmaK.LK9_K5_Tail
import ZetaShell.LemmaK.LK9_K6_Defs
import ZetaShell.LemmaK.LK9_K6_Derive
import ZetaShell.LemmaK.LK9_K6b_SBP
import ZetaShell.LemmaK.LK9_K6c_Helpers
import ZetaShell.LemmaK.LK9_K6d_Aux
import ZetaShell.LemmaK.LK9_K6d_Tails
import ZetaShell.LemmaK.LK_K00_BKleB
import ZetaShell.LemmaK.LK_K01_BKmonoC
import ZetaShell.LemmaK.LK_K1_GaussSumIneq
import ZetaShell.LemmaK.LK_K1s_FareySum
import ZetaShell.LemmaK.LK_K2_GallagherZeroSet
import ZetaShell.LemmaK.LK_K3_HoleCores
import ZetaShell.LemmaK.LK_K4_PrincipalGaussHole
import ZetaShell.LemmaK.LK_K4b_MuSqTotient
import ZetaShell.LemmaK.LK_K5_SmallPrimes
import ZetaShell.LemmaK.LK_K6_ArcMass
import ZetaShell.LemmaK.LK_K7_Defs
import ZetaShell.LemmaK.LK_K7_HoleLe
import ZetaShell.LemmaK.LK_K7_Pointwise
import ZetaShell.LemmaK.LK_K7c_Plain
import ZetaShell.LemmaK.LK_K8_FrobKilled
import ZetaShell.LemmaK.LK_K8a1_KilledMaster
import ZetaShell.LemmaK.LK_K8a2_Saving
import ZetaShell.LemmaK.LK_K8a3_Errors
import ZetaShell.LemmaK.LK_K8a4_Chain
import ZetaShell.LemmaK.LK_K8a_Defs
import ZetaShell.LemmaK.LK_K8b_HfrobKilled
import ZetaShell.LemmaK.LK_K8c_ZoneSplitRamp
import ZetaShell.LemmaK.LK_K8d_Bridge
import ZetaShell.LemmaK.LK_KA_Assembly
import ZetaShell.LemmaK.LK_KCa_CertCore
import ZetaShell.LemmaK.LK_KCq
import ZetaShell.LemmaK.LK_KT_Headline
import ZetaShell.PNT.PNTMedium
import ZetaShell.PropZ.Z5Zero_W
import ZetaShell.PropZ.Z5_PropZW
import ZetaShell.PropZ.Z5a_Plancherel
import ZetaShell.PropZ.Z5a_PlancherelMajorant
import ZetaShell.PropZ.Z5b_Weil
import ZetaShell.PropZ.Z5b_WeilOne
import ZetaShell.PropZ.Z5c_FamilyErrors
import ZetaShell.PropZ.Z5c_FamilyErrorsW
import ZetaShell.PropZ.ZDefs
import ZetaShell.PropZ.ZDefsW
import ZetaShell.PropZ.ZP_Pointwise
import ZetaShell.PropZ.ZZ0_Defs
import ZetaShell.Skeleton.A2P_LineProfile
import ZetaShell.Lemma2.A2a_OutsideShells
import ZetaShell.Lemma2.A2a_S2_LineCount
import ZetaShell.Lemma2.A2a_S3_Count
import ZetaShell.Lemma2.A2a_S4_Profile
import ZetaShell.Lemma2.A2a_S5_Window
import ZetaShell.Farey.A3_SignedGallagher
import ZetaShell.Skeleton.F1_ShellFrameQle
import ZetaShell.LemmaK.LK9_K6a_ModelMass
import ZetaShell.Skeleton.LK9_K6b_GallagherL2
import ZetaShell.LemmaK.LK9_K6c_PNTStep
import ZetaShell.LemmaK.LK_K7a_FareyHole
import ZetaShell.LemmaK.LK_K7b_HoleLower
import ZetaShell.Skeleton.LK_K9_Frame
import ZetaShell.Skeleton.LK_KC_Cert
import ZetaShell.Skeleton.SD_C2_ZoneSlope
import ZetaShell.Skeleton.SD_F1c_FrobRow
import ZetaShell.PropZ.Z5R_W
import ZetaShell.Skeleton.Z5_PropZ
import ZetaShell.Skeleton.Z5_Steps
import ZetaShell.Skeleton.Z5b_SmoothEF
import ZetaShell.PropZ.ZP_Bridge
import ZetaShell.PropZ.ZZ1_Expand
import ZetaShell.PropZ.ZZ2_OneZero
import ZetaShell.PropZ.ZZ3_Pair
import ZetaShell.PropZ.ZZ4_Count
import ZetaShell.Top.HeadlineReduced
import ZetaShell.Top.T1_Headline
import ZetaShell.LemmaK.LK9_DT_Facts
import ZetaShell.LemmaK.LK9_K6a_DiffD
import ZetaShell.LemmaK.LK9_K6a_DwSum
import ZetaShell.LemmaK.LK9_K6a_L2Final
import ZetaShell.LemmaK.LK9_K6a_L2Lower
import ZetaShell.LemmaK.LK9_K6a_Outer
import ZetaShell.LemmaK.LK9_K6a_OuterGen
import ZetaShell.LemmaK.LK9_K6a_Split
import ZetaShell.LemmaK.LK9_K6a_Step2
import ZetaShell.LemmaK.LK9_K6c2_Aux
import ZetaShell.LemmaK.LK9_K6c2_Var
import ZetaShell.LemmaK.LK9_K6c3_Aux
import ZetaShell.LemmaK.LK9_K6c3_PNT
import ZetaShell.LemmaK.LK9_K6c4_Assembly
import ZetaShell.LemmaK.LK_K7_HoleGeneric
import ZetaShell.PropZ.DT_Facts
import ZetaShell.Lemma2.A2a_S2s_AbsMu
import ZetaShell.Lemma2.A2a_S2s_Defs
import ZetaShell.Lemma2.A2a_S2s_Expand
import ZetaShell.Lemma2.A2a_S3_Defs
import ZetaShell.Lemma2.A2a_S3b_LineInt
import ZetaShell.Lemma2.A2a_S3c_Irrelevant
import ZetaShell.PropZ.DT_Facts2
import ZetaShell.PropZ.MellinDecay
import ZetaShell.PropZ.ZB_As
import ZetaShell.PropZ.ZB_Bounded
import ZetaShell.PropZ.ZR_Digamma
import ZetaShell.PropZ.ZR_Leaves
import ZetaShell.PropZ.ZR_Mellin
import ZetaShell.PropZ.ZR_Phi
import ZetaShell.PropZ.ZR_Phi2
import ZetaShell.PropZ.ZR_PhiPw0
import ZetaShell.PropZ.ZR_Remainder
import ZetaShell.PropZ.ZZ1a_Scaling
import ZetaShell.ShellK.L10_F1c
import ZetaShell.ShellK.L10_F1cChain
import ZetaShell.ShellK.L10_K
import ZetaShell.ShellK.L10_KDefs
import ZetaShell.ShellK.LF_1_Master
import ZetaShell.ShellK.LF_Assembly
import ZetaShell.ShellK.LF_Defs
import ZetaShell.ShellK.LF_EndsS
import ZetaShell.ShellK.LF_Frame
import ZetaShell.ShellK.LF_HsepS
import ZetaShell.ShellK.LF_InArith
import ZetaShell.ShellK.LF_InZone
import ZetaShell.ShellK.LF_Kernel
import ZetaShell.ShellK.LF_OutDiag
import ZetaShell.ShellK.LF_OutFinal
import ZetaShell.ShellK.LF_Rows8
import ZetaShell.ShellK.LF_Small
import ZetaShell.ShellK.LF_Transfer
import ZetaShell.ShellS.L10_Defs
import ZetaShell.ShellS.L10_S
import ZetaShell.ShellS.L10_S4
import ZetaShell.ShellS.L10_Z6c
import ZetaShell.Lemma2.A2a_S2s_Class
import ZetaShell.Lemma2.A2a_S2s_Main
import ZetaShell.Lemma2.A2a_S3a_Reindex
import ZetaShell.Lemma2.A2a_S3d_Arith
import ZetaShell.Lemma2.A2a_S3e_Tail
import ZetaShell.Skeleton.L10_AS
import ZetaShell.ShellK.L10_K1_Strip
import ZetaShell.ShellK.L10_K2_ShellZone
import ZetaShell.ShellK.L10_K3_Killed
import ZetaShell.ShellK.L10_KInt
import ZetaShell.ShellK.L10_KT
import ZetaShell.Skeleton.L10_S1
import ZetaShell.ShellS.L12_S3
import ZetaShell.Skeleton.L10_Z6d
import ZetaShell.Skeleton.LF_AsmBase
import ZetaShell.ShellK.LF_Mertens
import ZetaShell.ShellK.LF_K3a
import ZetaShell.ShellK.LF_KernelWin
import ZetaShell.ShellK.LF_MajConstr
import ZetaShell.ShellK.LF_MajConstr2
import ZetaShell.ShellK.LF_MajConstr3
import ZetaShell.ShellK.LF_MajConstr4
import ZetaShell.ShellK.LF_MajConstr5
import ZetaShell.ShellK.LF_Majorant
import ZetaShell.ShellK.LF_K3Split
import ZetaShell.Lemma2.A2a_S2c_FamData
import ZetaShell.Lemma2.A2a_S2c_ProgGeneral
import ZetaShell.Lemma2.A2a_S2c_ProgSum
import ZetaShell.Lemma2.A2a_S2c_Reparam
import ZetaShell.Lemma2.A2a_S2s_MainAux
import ZetaShell.Lemma2.A2a_S3a_Collapse
import ZetaShell.Lemma2.A2a_S3a_WindowAux
import ZetaShell.Lemma2.A2a_S3a_WindowProof
import ZetaShell.Lemma2.A2a_S3d_InnerAux
import ZetaShell.Lemma2.A2a_S3d_InnerProof
import ZetaShell.Lemma2.A2a_S3d_JsumAux
import ZetaShell.Lemma2.A2a_S3d_JsumProof
import ZetaShell.Lemma2.A2a_S3d_Qphi4
import ZetaShell.Lemma2.A2a_S3d_Route4
import ZetaShell.Lemma2.L711_MuSqPhi
import ZetaShell.Lemma2.L711_QphiSum
import ZetaShell.Lemma2.L711_S4a_ChangeVar
import ZetaShell.Lemma2.A2P_LineSumCore
import ZetaShell.Lemma2.A2a_S3e_TailGeom
import ZetaShell.Lemma2.A2a_S3e_TailPlain
import ZetaShell.Skeleton.A2a_S3a_Window
import ZetaShell.Skeleton.A2a_S3d_ArithSplit
import ZetaShell.Skeleton.A2a_S3d_CeTau
import ZetaShell.Skeleton.A2a_S3e_TailParts
import ZetaShell.ShellS.L12_Aux
import ZetaShell.Skeleton.Astar_Corr
import ZetaShell.PropZ.FourierLink
import ZetaShell.PropZ.ZB_Meas
import ZetaShell.PropZ.ZP_IBP
import ZetaShell.PropZ.ZZ1b_Expand
import ZetaShell.PropZ.ZZ2a_OneZeroSplit
import ZetaShell.PropZ.ZZ2b_Trivial
import ZetaShell.PropZ.ZZ2c_HL2
import ZetaShell.PropZ.ZZ2d_Young
import ZetaShell.PropZ.ZZ2e_Fourier
import ZetaShell.PropZ.ZZ2f_Ibp
import ZetaShell.PropZ.ZZ2g_Nsp
import ZetaShell.PropZ.ZZ2h_NspCore
import ZetaShell.PropZ.ZZ3a_PairSplit
import ZetaShell.PropZ.ZZ3b_Irho
import ZetaShell.PropZ.ZZ3c_Q
import ZetaShell.PropZ.ZZ3d_Deriv
import ZetaShell.PropZ.Z5_PropZWdom
import ZetaShell.ShellS.S1L_Eventually
import ZetaShell.ShellS.S1L_Meas
import ZetaShell.ShellS.S1L_Model
import ZetaShell.ShellS.S1L_MuSq
import ZetaShell.ShellS.S1L_PP
import ZetaShell.ShellS.S1L_TestFn
import ZetaShell.ShellS.S1L_Twist
import ZetaShell.ShellS.S1_AstarLink
import ZetaShell.ShellS.S1_Defs
import ZetaShell.ShellS.S1_FromZ
import ZetaShell.ShellS.S1_Leaves
import ZetaShell.ShellS.L12b_LocalCount
import ZetaShell.ShellS.L12b_Window
import ZetaShell.ShellS.L12b_Pair
import ZetaShell.ShellS.L12b_RPhi
import ZetaShell.ShellS.L12b_Char
import ZetaShell.ShellS.L12b_Z6a
import ZetaShell.ShellS.L12c_Shell
import ZetaShell.ShellS.L12c_Family
import ZetaShell.ShellS.L12c_Counts
import ZetaShell.ShellS.L12c_Zones
import ZetaShell.ShellS.L12c_Layer
import ZetaShell.ShellS.L12c_Bounds
import ZetaShell.ShellS.L12c_Zsize
import ZetaShell.ShellS.L12c_Z6d
import ZetaShell.ShellS.L12c_S2
import ZetaShell.ShellK.LF_K3bU
import ZetaShell.ShellK.LF_K3bP
import ZetaShell.ShellK.LF_K3bA
import ZetaShell.ShellK.LF_K3bArith
import ZetaShell.ShellK.LF_K3bI
import ZetaShell.ShellK.LF_K3bM
import ZetaShell.ShellK.LF_FrameNoP
import ZetaShell.Top.T1_HeadlineNoP
import ZetaShell.ShellK.L10c_K2Aux
import ZetaShell.ShellK.L10c_K2Point
import ZetaShell.ShellK.L10c_KT
import ZetaShell.ShellK.L10c_Scales
import ZetaShell.ShellK.L10c_Window
import ZetaShell.ShellS.L10c_ASArith
import ZetaShell.ShellS.L10c_ASBounds
import ZetaShell.ShellS.L10c_ASC
import ZetaShell.ShellS.L10c_ASCore
import ZetaShell.ShellS.L10c_ASD
import ZetaShell.ShellS.L10c_ASD2
import ZetaShell.ShellS.L10c_ASF
import ZetaShell.ShellS.L10c_ASH
import ZetaShell.ShellS.L10c_ASMain
import ZetaShell.ShellS.L10c_ASP
import ZetaShell.ShellS.L10c_ASPoint
import ZetaShell.ShellS.L10c_ASSupp
import ZetaShell.ShellS.L10c_Tao
