/-
lean_work/L3_2/top/PolyMoments.lean — exact moments of the window psiPoly8A (thm:zeta-mainw2) and H(psiPoly8A)
(L3_2, 28 Sep 2026; generated by py/gen_polymoments.py, sympy, and checked by Lean: ring / norm_num).
Device of the tree (Zeta23/XiPrime/Certificate/Poly.lean): polynomials as coefficient lists, `integral_polyEval`.
  ∫ψ̃ = 107992/116753,  ∫ψ̃² = 330733552129940/383449375766457,  ∬|u − v|ψ̃(u)ψ̃(v) = 664167408393196/2428512713187561  (the kernel ∫|s − s′|ψ̃(s′)ds′ is an explicit polynomial for
  |s| ≤ 1/2, by splitting at s′ = s),  H(ψ̃) = 2 − (b + J)/a² = 26957030199857/40103091391077 (= L0_2 `HD_P8`).
-/
import ZetaS.Interfaces
import Zeta23.XiPrime.Certificate.Poly

open intervalIntegral Zeta23.XiPrime

noncomputable section

namespace ZetaS
namespace PolyMom

def cψ : List ℝ := [(50000 / 50037 : ℝ), (0 : ℝ), (10160 / 50037 : ℝ), (0 : ℝ), (-239920 / 16679 : ℝ), (0 : ℝ), (1979840 / 50037 : ℝ), (0 : ℝ), (10240 / 16679 : ℝ)]
def cψ1 : List ℝ := [(0 : ℝ), (50000 / 50037 : ℝ), (0 : ℝ), (10160 / 50037 : ℝ), (0 : ℝ), (-239920 / 16679 : ℝ), (0 : ℝ), (1979840 / 50037 : ℝ), (0 : ℝ), (10240 / 16679 : ℝ)]
def cψ2 : List ℝ := [(2500000000 / 2503701369 : ℝ), (0 : ℝ), (1016000000 / 2503701369 : ℝ), (0 : ℝ), (-71872774400 / 2503701369 : ℝ), (0 : ℝ), (183358476800 / 2503701369 : ℝ), (0 : ℝ), (43181292800 / 192592413 : ℝ), (0 : ℝ), (-316599449600 / 278189041 : ℝ), (0 : ℝ), (3875544371200 / 2503701369 : ℝ), (0 : ℝ), (40547123200 / 834567123 : ℝ), (0 : ℝ), (104857600 / 278189041 : ℝ)]
def cG : List ℝ := [(176131 / 800592 : ℝ), (0 : ℝ), (50000 / 50037 : ℝ), (0 : ℝ), (5080 / 150111 : ℝ), (0 : ℝ), (-47984 / 50037 : ℝ), (0 : ℝ), (494960 / 350259 : ℝ), (0 : ℝ), (2048 / 150111 : ℝ)]
def cGψ : List ℝ := [(550409375 / 2503701369 : ℝ), (0 : ℝ), (870614395 / 834567123 : ℝ), (0 : ℝ), (-21991759105 / 7511104107 : ℝ), (0 : ℝ), (-49726637380 / 7511104107 : ℝ), (0 : ℝ), (78679447040 / 1947323287 : ℝ), (0 : ℝ), (93748725760 / 5841969861 : ℝ), (0 : ℝ), (-3062532665600 / 52577728749 : ℝ), (0 : ℝ), (966183633920 / 17525909583 : ℝ), (0 : ℝ), (73998499840 / 52577728749 : ℝ), (0 : ℝ), (20971520 / 2503701369 : ℝ)]

lemma psi_eq (x : ℝ) : psiPoly8A x = polyEval cψ x := by
  simp only [psiPoly8A, cψ, polyEval, List.length_cons, List.length_nil, Finset.sum_range_succ,
    Finset.sum_range_zero, List.getD_cons_succ, List.getD_cons_zero]
  ring

lemma psi1_eq (x : ℝ) : x * psiPoly8A x = polyEval cψ1 x := by
  simp only [psiPoly8A, cψ1, polyEval, List.length_cons, List.length_nil, Finset.sum_range_succ,
    Finset.sum_range_zero, List.getD_cons_succ, List.getD_cons_zero]
  ring

lemma psi2_eq (x : ℝ) : psiPoly8A x ^ 2 = polyEval cψ2 x := by
  simp only [psiPoly8A, cψ2, polyEval, List.length_cons, List.length_nil, Finset.sum_range_succ,
    Finset.sum_range_zero, List.getD_cons_succ, List.getD_cons_zero]
  ring

lemma Gpsi_eq (x : ℝ) : psiPoly8A x * polyEval cG x = polyEval cGψ x := by
  simp only [psiPoly8A, cG, cGψ, polyEval, List.length_cons, List.length_nil, Finset.sum_range_succ,
    Finset.sum_range_zero, List.getD_cons_succ, List.getD_cons_zero]
  ring

theorem int_psi : ∫ x in (-(1 / 2 : ℝ))..(1 / 2), psiPoly8A x = (107992 / 116753 : ℝ) := by
  rw [intervalIntegral.integral_congr (fun x _ => psi_eq x), integral_polyEval]
  simp only [polyInt, cψ, List.length_cons, List.length_nil, Finset.sum_range_succ,
    Finset.sum_range_zero, List.getD_cons_succ, List.getD_cons_zero]
  norm_num

theorem int_psi_sq : ∫ x in (-(1 / 2 : ℝ))..(1 / 2), psiPoly8A x ^ 2 = (330733552129940 / 383449375766457 : ℝ) := by
  rw [intervalIntegral.integral_congr (fun x _ => psi2_eq x), integral_polyEval]
  simp only [polyInt, cψ2, List.length_cons, List.length_nil, Finset.sum_range_succ,
    Finset.sum_range_zero, List.getD_cons_succ, List.getD_cons_zero]
  norm_num

lemma cont_psi : Continuous psiPoly8A := by unfold psiPoly8A; fun_prop

/-- the kernel `∫|s − s′|ψ̃(s′)ds′` for `|s| ≤ 1/2`. -/
theorem kernel_psi {s : ℝ} (hs1 : -(1 / 2 : ℝ) ≤ s) (hs2 : s ≤ 1 / 2) :
    ∫ s' in (-(1 / 2 : ℝ))..(1 / 2), |s - s'| * psiPoly8A s' = polyEval cG s := by
  have hcont : ∀ a b : ℝ, IntervalIntegrable (fun s' => |s - s'| * psiPoly8A s') MeasureTheory.volume a b :=
    fun a b => (Continuous.intervalIntegrable (by have := cont_psi; fun_prop) a b)
  have hP : ∀ a b : ℝ, IntervalIntegrable (fun s' => polyEval cψ s') MeasureTheory.volume a b := fun a b =>
    (Continuous.intervalIntegrable (by unfold polyEval; fun_prop) a b)
  have hP1 : ∀ a b : ℝ, IntervalIntegrable (fun s' => polyEval cψ1 s') MeasureTheory.volume a b := fun a b =>
    (Continuous.intervalIntegrable (by unfold polyEval; fun_prop) a b)
  rw [← intervalIntegral.integral_add_adjacent_intervals (hcont _ s) (hcont s _)]
  have hl : ∫ s' in (-(1 / 2 : ℝ))..s, |s - s'| * psiPoly8A s'
      = ∫ s' in (-(1 / 2 : ℝ))..s, (s * polyEval cψ s' - polyEval cψ1 s') := by
    apply intervalIntegral.integral_congr
    intro x hx
    rw [Set.uIcc_of_le hs1] at hx
    show |s - x| * psiPoly8A x = s * polyEval cψ x - polyEval cψ1 x
    rw [abs_of_nonneg (by linarith [hx.2] : (0:ℝ) ≤ s - x), ← psi_eq, ← psi1_eq]; ring
  have hr : ∫ s' in s..(1 / 2), |s - s'| * psiPoly8A s'
      = ∫ s' in s..(1 / 2), (polyEval cψ1 s' - s * polyEval cψ s') := by
    apply intervalIntegral.integral_congr
    intro x hx
    rw [Set.uIcc_of_le hs2] at hx
    show |s - x| * psiPoly8A x = polyEval cψ1 x - s * polyEval cψ x
    rw [abs_of_nonpos (by linarith [hx.1] : s - x ≤ 0), ← psi_eq, ← psi1_eq]; ring
  rw [hl, hr, intervalIntegral.integral_sub ((hP _ _).const_mul s) (hP1 _ _),
    intervalIntegral.integral_sub (hP1 _ _) ((hP _ _).const_mul s),
    intervalIntegral.integral_const_mul, intervalIntegral.integral_const_mul,
    integral_polyEval, integral_polyEval, integral_polyEval, integral_polyEval]
  simp only [polyInt, polyEval, cψ, cψ1, cG, List.length_cons, List.length_nil, Finset.sum_range_succ,
    Finset.sum_range_zero, List.getD_cons_succ, List.getD_cons_zero]
  ring

theorem jInt_psi : ∫ u in (-(1 / 2 : ℝ))..(1 / 2), ∫ v in (-(1 / 2 : ℝ))..(1 / 2),
    |u - v| * psiPoly8A u * psiPoly8A v = (664167408393196 / 2428512713187561 : ℝ) := by
  have hstep : ∀ u ∈ Set.uIcc (-(1 / 2 : ℝ)) (1 / 2),
      (∫ v in (-(1 / 2 : ℝ))..(1 / 2), |u - v| * psiPoly8A u * psiPoly8A v) = polyEval cGψ u := by
    intro u hu
    rw [Set.uIcc_of_le (by norm_num)] at hu
    have e1 : ∀ v : ℝ, |u - v| * psiPoly8A u * psiPoly8A v = psiPoly8A u * (|u - v| * psiPoly8A v) := by
      intro v; ring
    rw [intervalIntegral.integral_congr (fun v _ => e1 v), intervalIntegral.integral_const_mul,
      kernel_psi hu.1 hu.2, Gpsi_eq]
  rw [intervalIntegral.integral_congr hstep, integral_polyEval]
  simp only [polyInt, cGψ, List.length_cons, List.length_nil, Finset.sum_range_succ,
    Finset.sum_range_zero, List.getD_cons_succ, List.getD_cons_zero]
  norm_num

end PolyMom

/-- `H(ψ̃) = 26957030199857/40103091391077` (rem:zeta-P8; = L0_2 `HD_P8`). -/
theorem Hpsi_poly8A : Hpsi psiPoly8A = 26957030199857 / 40103091391077 := by
  unfold Hpsi Rpsi
  rw [PolyMom.int_psi_sq, PolyMom.jInt_psi, PolyMom.int_psi]
  norm_num

end ZetaS
