/-
L7_3 (round 5): **the ends chain of ZetaQ at the Shell envelope `c₁ = 0.52`** (restated F1c-4b and its consumers).
GENERATED by `py/gen_ends.py` from the green tree by mechanical substitution (`envSep → envSepS`, `Bends → BendsS`,
`c1Ends → c1S = 0.52`, `endsMaj → endsMajS`, each copied theorem `X → X_S`):
`S3_continuous_envSep`, `S4_nuBound_envSep`, `S5_LB_le_Bends`, `scale_sq_mul_Bends_sq`, `scale_mul_envSep`,
`nuBound_envSep_abs`, `S6_family_pass`, `sum_majK1_le`, `majK2_integrable_fam`, `sum_majK2_le`, `ends_family_bound` (Ends.lean) and
`frobSqGhatFam_le_Mform_add_ends` (FrobAssembly.lean). `Bfam_le_sep_S` is `Bfam_le_sep` with its two δ-steps replaced by
hypotheses (`log X ≤ 1.955·log Q`, `πX ≤ 10⁻⁴Q²`; A7 gives both at `λ = 1.91`) and its numeric core re-derived: the prime
half costs `0.3183224·1.00005·0.7072·1.955 = 0.4401269 ≤ 0.4401270` per unit of `ℒ − 3.46` (was `0.33769337` at
`2 − δ = 1.5`), and `0.07003 + 0.44013 = 0.51016 ≤ c₁ = 0.52` (C3's `c1EndsShell`; ZetaQ's `0.41` is not reachable,
since the route needs `c₁ ≥ 1.955/(√2π) + 3/(√2π³) = 0.5085`).
-/
import ZetaShell.ShellK.LF_Defs
import ZetaShell.Design.SD_C3_EndsC1

noncomputable section
open scoped BigOperators
open scoped ArithmeticFunction
open MeasureTheory

namespace ZetaShell
namespace ShellK
namespace F1c

open ZetaQ ZetaQ.Ends ZetaQ.Payoff ZetaQ.Zones ZetaQ.FrobAssembly Zeta23.PrimeSide Zeta23.ThmE

variable {P : ParamsQ}

/-- the Shell ends constant `c₁ = 0.52` (L7_7's C3 `c1EndsShell`). -/
def c1S : ℝ := 0.52

theorem c1S_eq_c1EndsShell : c1S = Design.c1EndsShell := rfl

/-- `B_ends` at `c₁ = 0.52`. -/
def BendsS (P : ParamsQ) : ℝ := c1S * (P.LL + C0Ends) / cMu

/-- the separated envelope at `c₁ = 0.52`. -/
def envSepS (P : ParamsQ) (τ : ℝ) : ℝ := BendsS P + logPlusQ P τ

/-- the family ends majorant at `c₁ = 0.52` (ZetaQ's `endsMaj` with `c1Ends → c1S`). -/
def endsMajS (P : ParamsQ) : ℝ :=
  ((P.aQ * P.LB ^ 2)⁻¹) ^ 2
    * ((c1S * P.Q) ^ 2 * (P.LB ^ 3 * (P.LB + Zeta23.l P.T) * (P.LL + C0Ends) ^ 2
        * (C1ends P.cWin + C2ends P.cWin * (1 + Real.log P.LB))))

set_option maxHeartbeats 4000000 in
theorem S3_continuous_envSep_S (P : ParamsQ) (hT : 0 < P.T) : Continuous (envSepS P) := by
  have hlog : Continuous (logPlusQ P) := by
    rw [continuous_iff_continuousAt]
    intro τ
    rcases eq_or_ne τ 0 with rfl | hτ
    · -- on the ball `|x| < 4T` the `log⁺` is identically `0`, so it is continuous at `0`
      have hev : (fun _ : ℝ => (0 : ℝ)) =ᶠ[nhds (0 : ℝ)] logPlusQ P := by
        filter_upwards [Metric.ball_mem_nhds (0 : ℝ) (by linarith : (0:ℝ) < 4 * P.T)] with x hx
        have hx' : |x| < 4 * P.T := by
          simpa [Real.dist_eq] using hx
        have h0 : (0 : ℝ) ≤ |x| / (4 * P.T) := by positivity
        have h1 : |x| / (4 * P.T) ≤ 1 := by
          rw [div_le_one (by linarith)]; linarith
        show (0 : ℝ) = logPlusQ P x
        rw [logPlusQ, max_eq_right (Real.log_nonpos h0 h1)]
      exact continuousAt_const.congr hev
    · have hne : |τ| / (4 * P.T) ≠ 0 := by
        have : (0 : ℝ) < |τ| := abs_pos.mpr hτ
        positivity
      have hc : ContinuousAt (fun x : ℝ => Real.log (|x| / (4 * P.T))) τ :=
        ContinuousAt.log (by fun_prop) hne
      exact hc.max continuousAt_const
  exact continuous_const.add hlog

set_option maxHeartbeats 4000000 in
theorem S4_nuBound_envSep_S (P : ParamsQ) (hP : P.Valid) :
    NuBound (toSetting P) (BendsS P) (envSepS P) := by
  have hQ : (3 : ℝ) ≤ P.Q := hP.Q_ge
  have hT : (300 : ℝ) ≤ P.T := by
    have h := hP.T_ge; unfold Zeta23.Tail.T₀ at h; exact h
  have hpi : Real.pi ≤ 4 := Real.pi_le_four
  have hLL : (0 : ℝ) ≤ P.LL := by
    unfold ParamsQ.LL
    apply Real.log_nonneg
    rw [le_div_iff₀ (by positivity)]
    nlinarith [mul_le_mul hQ hT (by norm_num : (0:ℝ) ≤ 300) (by linarith : (0:ℝ) ≤ P.Q),
      Real.pi_pos]
  have hBends : (0 : ℝ) ≤ BendsS P := by
    have : (0 : ℝ) ≤ c1S * (P.LL + C0Ends) := by
      unfold c1S C0Ends; linarith
    exact div_nonneg this cMu_pos.le
  intro τ
  have h0 : (0 : ℝ) ≤ logPlusQ P τ := le_max_right _ _
  rw [abs_of_nonneg (by show (0:ℝ) ≤ BendsS P + logPlusQ P τ; linarith)]
  show BendsS P + logPlusQ P τ ≤ BendsS P + logPlusQ P τ
  exact le_rfl

set_option maxHeartbeats 4000000 in
theorem S5_LB_le_Bends_S (P : ParamsQ) (hP : P.Valid) : P.LB ≤ BendsS P := by
  have hQ : (3 : ℝ) ≤ P.Q := hP.Q_ge
  have hT : (300 : ℝ) ≤ P.T := by
    have h := hP.T_ge; unfold Zeta23.Tail.T₀ at h; exact h
  have hpi : (3 : ℝ) < Real.pi := Real.pi_gt_three
  have hpi' : Real.pi ≤ 4 := Real.pi_le_four
  have hpi3 : (27 : ℝ) < Real.pi ^ 3 := by
    have := pow_lt_pow_left₀ hpi (by norm_num : (0:ℝ) ≤ 3) (by norm_num : 3 ≠ 0)
    norm_num at this; exact this
  -- `ℒ = log(QT/2π) ≥ 0` from `Q ≥ 3`, `T ≥ 300`.
  have hLL : (0 : ℝ) ≤ P.LL := by
    unfold ParamsQ.LL
    apply Real.log_nonneg
    rw [le_div_iff₀ (by positivity)]
    nlinarith [mul_le_mul hQ hT (by norm_num : (0:ℝ) ≤ 300) (by linarith : (0:ℝ) ≤ P.Q)]
  have hLBnn : (0 : ℝ) ≤ P.LB := by
    unfold ParamsQ.LB; exact mul_nonneg hP.lam_pos.le hLL
  -- `λ < 2` (Valid.lam_lt_two — NOT `λ ≤ 1`).
  have hLB2 : P.LB ≤ 2 * P.LL := by
    unfold ParamsQ.LB; nlinarith [hP.lam_lt_two]
  have hcmu : cMu ≤ 1 / 9 := by
    unfold cMu
    rw [div_le_div_iff₀ (by positivity) (by norm_num)]
    linarith
  show P.LB ≤ c1S * (P.LL + C0Ends) / cMu
  rw [le_div_iff₀ cMu_pos]
  have hstep : P.LB * cMu ≤ P.LB * (1 / 9) := mul_le_mul_of_nonneg_left hcmu hLBnn
  unfold c1S C0Ends
  linarith

set_option maxHeartbeats 4000000 in
theorem scale_sq_mul_Bends_sq_S (P : ParamsQ) :
    (cMu * P.Q) ^ 2 * BendsS P ^ 2 = (c1S * P.Q) ^ 2 * (P.LL + C0Ends) ^ 2 := by
  have h : cMu ≠ 0 := ne_of_gt cMu_pos
  unfold BendsS
  field_simp

set_option maxHeartbeats 4000000 in
theorem scale_mul_envSep_S (P : ParamsQ) (τ : ℝ) :
    cMu * P.Q * envSepS P τ
      = c1S * P.Q * (P.LL + C0Ends) + cMu * P.Q * logPlusQ P τ := by
  have h : cMu ≠ 0 := ne_of_gt cMu_pos
  unfold envSepS BendsS
  field_simp

set_option maxHeartbeats 4000000 in
theorem nuBound_envSep_abs_S (P : ParamsQ) :
    NuBound (toSetting P) (max |BendsS P| 1) (envSepS P) := by
  intro τ
  have h0 : (0 : ℝ) ≤ logPlusQ P τ := le_max_right _ _
  have hb : |BendsS P| ≤ max |BendsS P| 1 := le_max_left _ _
  have h1 : |envSepS P τ| ≤ |BendsS P| + logPlusQ P τ := by
    have := abs_add_le (BendsS P) (logPlusQ P τ)
    rwa [abs_of_nonneg h0] at this
  show |envSepS P τ| ≤ max |BendsS P| 1 + max (Real.log (|τ| / (4 * (toSetting P).T))) 0
  have h2 : max (Real.log (|τ| / (4 * (toSetting P).T))) 0 = logPlusQ P τ := rfl
  rw [h2]; linarith

set_option maxHeartbeats 4000000 in
theorem S6_family_pass_S (P : ParamsQ) (Qn : ℕ) (X : ℝ)
    (hsep : ∀ τ : ℝ, Bfam Qn X τ ≤ cMu * P.Q * envSepS P τ) (τ τ' : ℝ) :
    ZetaQ.Ends.famSum Qn (fun _ χ => |nuFam X χ τ| * |nuFam X χ τ'|)
      ≤ (cMu * P.Q) ^ 2 * (envSepS P τ * envSepS P τ') := by
  -- flatten the family double sum, so Cauchy–Schwarz applies in one index
  set S : Finset ((_ : ℕ) × DirichletCharacter ℂ _) :=
    (Finset.Icc 1 Qn).sigma (fun q => primitiveChars q) with hS
  have hflat : ∀ f : (q : ℕ) → DirichletCharacter ℂ q → ℝ,
      ZetaQ.Ends.famSum Qn f = ∑ x ∈ S, f x.1 x.2 := fun f => Finset.sum_sigma' _ _ _
  have hsqflat : ∀ σ : ℝ, BfamSq Qn X σ = ∑ x ∈ S, nuFam X x.2 σ ^ 2 := fun σ =>
    hflat (fun _ χ => nuFam X χ σ ^ 2)
  -- Cauchy–Schwarz in χ, POINTWISE in `(τ, τ′)`
  have hCS := Finset.sum_mul_sq_le_sq_mul_sq S
    (fun x => |nuFam X x.2 τ|) (fun x => |nuFam X x.2 τ'|)
  have hsq1 : ∀ σ : ℝ, ∑ x ∈ S, |nuFam X x.2 σ| ^ 2 = BfamSq Qn X σ := by
    intro σ
    rw [hsqflat σ]
    exact Finset.sum_congr rfl fun x _ => sq_abs _
  rw [hsq1 τ, hsq1 τ'] at hCS
  have hnn : (0 : ℝ) ≤ ∑ x ∈ S, |nuFam X x.2 τ| * |nuFam X x.2 τ'| :=
    Finset.sum_nonneg fun x _ => mul_nonneg (abs_nonneg _) (abs_nonneg _)
  have hB0 : ∀ σ : ℝ, (0 : ℝ) ≤ Bfam Qn X σ := fun σ => Real.sqrt_nonneg _
  have hBsq : ∀ σ : ℝ, BfamSq Qn X σ = Bfam Qn X σ ^ 2 := by
    intro σ
    refine (Real.sq_sqrt ?_).symm
    unfold BfamSq ZetaQ.Ends.famSum
    exact Finset.sum_nonneg fun q _ => Finset.sum_nonneg fun χ _ => sq_nonneg _
  rw [hBsq τ, hBsq τ'] at hCS
  -- `Σ ≤ B_fam(τ)·B_fam(τ′)`
  have hmain : ∑ x ∈ S, |nuFam X x.2 τ| * |nuFam X x.2 τ'|
      ≤ Bfam Qn X τ * Bfam Qn X τ' := by
    nlinarith [hCS, hnn, hB0 τ, hB0 τ', mul_nonneg (hB0 τ) (hB0 τ')]
  rw [hflat (fun _ χ => |nuFam X χ τ| * |nuFam X χ τ'|)]
  refine hmain.trans ?_
  have h1 := hsep τ
  have h2 := hsep τ'
  calc Bfam Qn X τ * Bfam Qn X τ'
      ≤ (cMu * P.Q * envSepS P τ) * (cMu * P.Q * envSepS P τ') :=
        mul_le_mul h1 h2 (hB0 τ') ((hB0 τ).trans h1)
    _ = (cMu * P.Q) ^ 2 * (envSepS P τ * envSepS P τ') := by ring

set_option maxHeartbeats 4000000 in
theorem sum_majK1_le_S
    (P : ParamsQ) (Qn : ℕ) (cϱ X : ℝ) (F : LocalFun)
    (hF : LocalHypsCoreW cϱ (toSetting P) F)
    (hν : ∀ (q : ℕ) (χ : DirichletCharacter ℂ q), Continuous (nuFam X χ))
    (hsep : ∀ τ : ℝ, Bfam Qn X τ ≤ cMu * P.Q * envSepS P τ) :
    ZetaQ.Ends.famSum Qn (fun _ χ => ∫ z in sqI (toSetting P), majK1 (toSetting P) F (nuFam X χ) z)
      ≤ (cMu * P.Q) ^ 2 * ∫ z in sqI (toSetting P), majK1 (toSetting P) F (envSepS P) z := by
  rcases T_ge_or_neg hF with hT | hT
  · -- **The honest branch**, `T ≥ 2πe > 0`.
    simp only [toSetting_T] at hT
    have hTpos : (0 : ℝ) < P.T := by
      have h1 : (0 : ℝ) < 2 * Real.pi * Real.exp 1 := by positivity
      linarith
    have hcont : Continuous (envSepS P) := S3_continuous_envSep_S P hTpos
    have hint : ∀ (q : ℕ) (χ : DirichletCharacter ℂ q),
        IntegrableOn (majK1 (toSetting P) F (nuFam X χ)) (sqI (toSetting P)) :=
      fun q χ => majK1_integrableOn (hν q χ) hF
    have hinte : IntegrableOn (majK1 (toSetting P) F (envSepS P)) (sqI (toSetting P)) :=
      majK1_integrableOn hcont hF
    -- flatten the family double sum to a single index, exactly as in `S6_family_pass_S`
    set S : Finset ((_ : ℕ) × DirichletCharacter ℂ _) :=
      (Finset.Icc 1 Qn).sigma (fun q => primitiveChars q) with hS
    have hflat : ∀ f : (q : ℕ) → DirichletCharacter ℂ q → ℝ,
        ZetaQ.Ends.famSum Qn f = ∑ x ∈ S, f x.1 x.2 := fun f => Finset.sum_sigma' _ _ _
    -- the family sum passes inside the double integral (finitely many terms, each integrable)
    have hL : ZetaQ.Ends.famSum Qn
          (fun _ χ => ∫ z in sqI (toSetting P), majK1 (toSetting P) F (nuFam X χ) z)
        = ∫ z in sqI (toSetting P), ∑ x ∈ S, majK1 (toSetting P) F (nuFam X x.2) z := by
      rw [hflat (fun _ χ => ∫ z in sqI (toSetting P), majK1 (toSetting P) F (nuFam X χ) z)]
      exact (integral_finsetSum S (fun x _ => hint x.1 x.2)).symm
    have hR : (cMu * P.Q) ^ 2 * ∫ z in sqI (toSetting P), majK1 (toSetting P) F (envSepS P) z
        = ∫ z in sqI (toSetting P), (cMu * P.Q) ^ 2 * majK1 (toSetting P) F (envSepS P) z :=
      (integral_const_mul _ _).symm
    rw [hL, hR]
    refine setIntegral_mono_on
      (integrable_finsetSum S (fun x _ => hint x.1 x.2))
      (hinte.const_mul _) measurableSet_sqI ?_
    -- **the seam**: Cauchy–Schwarz in χ, POINTWISE in `(τ, τ′)`, against the nonnegative kernel
    intro z hz
    have hz1 : z.1 ∈ Set.Icc (toSetting P).T (2 * (toSetting P).T) := hz.1
    have hz2 : z.2 ∈ Set.Icc (toSetting P).T (2 * (toSetting P).T) := hz.2
    have hg1 : 0 < gwt (toSetting P) z.1 := gwt_pos hz1
    have hg2 : 0 < gwt (toSetting P) z.2 := gwt_pos hz2
    have hr1 : 0 ≤ rho (toSetting P) F z.1 := rho_nonneg hF z.1
    have hr2 : 0 ≤ rho (toSetting P) F z.2 := rho_nonneg hF z.2
    have hS6 := S6_family_pass_S P Qn X hsep z.1 z.2
    rw [hflat (fun _ χ => |nuFam X χ z.1| * |nuFam X χ z.2|)] at hS6
    simp only [majK1]
    set W : ℝ := (toSetting P).L ^ 2 *
        (rho (toSetting P) F z.1 / gwt (toSetting P) z.1 * gwt (toSetting P) z.2
          + gwt (toSetting P) z.1 * (rho (toSetting P) F z.2 / gwt (toSetting P) z.2))
      with hWdef
    have hWnn : 0 ≤ W := by
      rw [hWdef]
      refine mul_nonneg (sq_nonneg _) ?_
      have h1 : 0 ≤ rho (toSetting P) F z.1 / gwt (toSetting P) z.1 * gwt (toSetting P) z.2 :=
        mul_nonneg (div_nonneg hr1 hg1.le) hg2.le
      have h2 : 0 ≤ gwt (toSetting P) z.1 * (rho (toSetting P) F z.2 / gwt (toSetting P) z.2) :=
        mul_nonneg hg1.le (div_nonneg hr2 hg2.le)
      linarith
    rw [← Finset.mul_sum]
    have habs : envSepS P z.1 * envSepS P z.2 ≤ |envSepS P z.1| * |envSepS P z.2| := by
      rw [← abs_mul]; exact le_abs_self _
    have key : (W * (cMu * P.Q) ^ 2) * (envSepS P z.1 * envSepS P z.2)
        ≤ (W * (cMu * P.Q) ^ 2) * (|envSepS P z.1| * |envSepS P z.2|) :=
      mul_le_mul_of_nonneg_left habs (mul_nonneg hWnn (sq_nonneg _))
    have step : W * ∑ x ∈ S, |nuFam X x.2 z.1| * |nuFam X x.2 z.2|
        ≤ W * ((cMu * P.Q) ^ 2 * (envSepS P z.1 * envSepS P z.2)) :=
      mul_le_mul_of_nonneg_left hS6 hWnn
    nlinarith [step, key]
  · -- **The degenerate branch**, `T < 0`: `I × I = ∅`, so both sides are `0`.
    have hempty : sqI (toSetting P) = ∅ := sqI_eq_empty (by simpa using hT)
    rw [hempty]
    simp [ZetaQ.Ends.famSum]

set_option maxHeartbeats 4000000 in
theorem majK2_integrable_fam_S (P : ParamsQ) (Qn : ℕ) (cϱ X : ℝ) (F : LocalFun)
    (hF : LocalHypsCoreW cϱ (toSetting P) F) (hTπ : 2 * Real.pi ≤ P.T)
    (hν : ∀ (q : ℕ) (χ : DirichletCharacter ℂ q), Continuous (nuFam X χ))
    (hsep : ∀ τ : ℝ, Bfam Qn X τ ≤ cMu * P.Q * envSepS P τ)
    {q : ℕ} {χ : DirichletCharacter ℂ q}
    (hq : q ∈ Finset.Icc 1 Qn) (hχ : χ ∈ primitiveChars q) :
    Integrable (majK2 cϱ (toSetting P) (nuFam X χ)) := by
  have hpi3 : (3 : ℝ) < Real.pi := Real.pi_gt_three
  have hTpos : (0 : ℝ) < P.T := by linarith
  have hT1 : (1 : ℝ) ≤ P.T := by linarith
  have hcont : Continuous (envSepS P) := S3_continuous_envSep_S P hTpos
  have hNB := nuBound_envSep_abs_S P
  have hB1 : (1 : ℝ) ≤ max |BendsS P| 1 := le_max_right _ _
  have hTT1 : (1 : ℝ) ≤ (toSetting P).T := hT1
  have hgrid : ∀ k ∈ Finset.range (toSetting P).d,
      ((toSetting P).tau k : ℝ) ∈ Set.Icc (toSetting P).T (2 * (toSetting P).T) := by
    intro k hk
    have h := Setting.tau_mem (toSetting P) hF.L_pos (by exact hTpos.le) hk
    exact ⟨h.1, h.2⟩
  have hbase : ∀ k ∈ Finset.range (toSetting P).d,
      Integrable (fun τ : ℝ =>
        psiA cϱ (toSetting P) (τ - (toSetting P).tau k) * |envSepS P τ|) :=
    fun k hk => integrable_psiA_shift_mul_nu hcont hF hNB hB1 hTT1 (hgrid k hk)
  have hnuB : ∀ τ : ℝ, |nuFam X χ τ| ≤ |cMu * P.Q| * |envSepS P τ| := by
    intro τ
    calc |nuFam X χ τ| ≤ Bfam Qn X τ := abs_nuFam_le_Bfam hq hχ τ
      _ ≤ cMu * P.Q * envSepS P τ := hsep τ
      _ ≤ |cMu * P.Q * envSepS P τ| := le_abs_self _
      _ = |cMu * P.Q| * |envSepS P τ| := abs_mul _ _
  have hwk : ∀ k ∈ Finset.range (toSetting P).d,
      Integrable (fun τ : ℝ =>
        psiA cϱ (toSetting P) (τ - (toSetting P).tau k) * |nuFam X χ τ|) := by
    intro k hk
    have hmeas : AEStronglyMeasurable
        (fun τ : ℝ => psiA cϱ (toSetting P) (τ - (toSetting P).tau k) * |nuFam X χ τ|)
        (volume : Measure ℝ) :=
      (psiA_shift_integrable hF _).aestronglyMeasurable.mul (hν q χ).abs.aestronglyMeasurable
    refine ((hbase k hk).const_mul |cMu * P.Q|).mono' hmeas ?_
    filter_upwards with τ
    have hψ : 0 ≤ psiA cϱ (toSetting P) (τ - (toSetting P).tau k) := psiA_nonneg_of hF _
    rw [Real.norm_eq_abs, abs_of_nonneg (mul_nonneg hψ (abs_nonneg _))]
    calc psiA cϱ (toSetting P) (τ - (toSetting P).tau k) * |nuFam X χ τ|
        ≤ psiA cϱ (toSetting P) (τ - (toSetting P).tau k) * (|cMu * P.Q| * |envSepS P τ|) :=
          mul_le_mul_of_nonneg_left (hnuB τ) hψ
      _ = |cMu * P.Q|
            * (psiA cϱ (toSetting P) (τ - (toSetting P).tau k) * |envSepS P τ|) := by ring
  have h : Integrable (fun z : ℝ × ℝ => ∑ k ∈ Finset.range (toSetting P).d,
      ((toSetting P).L ^ 2
          * (psiA cϱ (toSetting P) (z.1 - (toSetting P).tau k) * |nuFam X χ z.1|))
        * (psiA cϱ (toSetting P) (z.2 - (toSetting P).tau k) * |nuFam X χ z.2|)) := by
    refine integrable_finsetSum _ fun k hk => ?_
    exact ((hwk k hk).const_mul ((toSetting P).L ^ 2)).mul_prod (hwk k hk)
  refine h.congr (Filter.Eventually.of_forall fun z => ?_)
  simp only [majK2]
  rw [Finset.mul_sum, Finset.sum_mul]
  exact Finset.sum_congr rfl fun k _ => by ring

set_option maxHeartbeats 4000000 in
theorem sum_majK2_le_S
    (P : ParamsQ) (Qn : ℕ) (cϱ X : ℝ) (F : LocalFun)
    (hF : LocalHypsCoreW cϱ (toSetting P) F)
    (hν : ∀ (q : ℕ) (χ : DirichletCharacter ℂ q), Continuous (nuFam X χ))
    (hsep : ∀ τ : ℝ, Bfam Qn X τ ≤ cMu * P.Q * envSepS P τ) :
    ZetaQ.Ends.famSum Qn (fun _ χ => ∫ z in (sqI (toSetting P))ᶜ, majK2 cϱ (toSetting P) (nuFam X χ) z)
      ≤ (cMu * P.Q) ^ 2 * ∫ z in (sqI (toSetting P))ᶜ, majK2 cϱ (toSetting P) (envSepS P) z := by
  rcases T_ge_or_neg hF with hT | hT
  · -- **The honest branch**, `T ≥ 2πe`, which supplies [R]'s own floor `2π ≤ T`.
    simp only [toSetting_T] at hT
    have hexp : (2 : ℝ) ≤ Real.exp 1 := by linarith [Real.add_one_le_exp (1 : ℝ)]
    have hpi : (0 : ℝ) < Real.pi := Real.pi_pos
    have hpi3 : (3 : ℝ) < Real.pi := Real.pi_gt_three
    have hT2π : 2 * Real.pi ≤ P.T := by nlinarith
    have hTpos : (0 : ℝ) < P.T := by linarith
    have hcont : Continuous (envSepS P) := S3_continuous_envSep_S P hTpos
    have hNB := nuBound_envSep_abs_S P
    have hB1 : (1 : ℝ) ≤ max |BendsS P| 1 := le_max_right _ _
    have hTT2π : 2 * Real.pi ≤ (toSetting P).T := hT2π
    set S : Finset ((_ : ℕ) × DirichletCharacter ℂ _) :=
      (Finset.Icc 1 Qn).sigma (fun q => primitiveChars q) with hS
    have hflat : ∀ f : (q : ℕ) → DirichletCharacter ℂ q → ℝ,
        ZetaQ.Ends.famSum Qn f = ∑ x ∈ S, f x.1 x.2 := fun f => Finset.sum_sigma' _ _ _
    have hMint : ∀ x ∈ S, Integrable (majK2 cϱ (toSetting P) (nuFam X x.2)) := by
      intro x hx
      rw [hS, Finset.mem_sigma] at hx
      exact majK2_integrable_fam_S P Qn cϱ X F hF hT2π hν hsep hx.1 hx.2
    have hMinte : Integrable (majK2 cϱ (toSetting P) (envSepS P)) :=
      majK2_integrable hcont hF hNB (by linarith) hTT2π
    -- the family sum passes inside the double integral
    have hL : ZetaQ.Ends.famSum Qn
          (fun _ χ => ∫ z in (sqI (toSetting P))ᶜ, majK2 cϱ (toSetting P) (nuFam X χ) z)
        = ∫ z in (sqI (toSetting P))ᶜ,
            ∑ x ∈ S, majK2 cϱ (toSetting P) (nuFam X x.2) z := by
      rw [hflat (fun _ χ => ∫ z in (sqI (toSetting P))ᶜ, majK2 cϱ (toSetting P) (nuFam X χ) z)]
      exact (integral_finsetSum S (fun x hx => (hMint x hx).integrableOn)).symm
    have hR : (cMu * P.Q) ^ 2
          * ∫ z in (sqI (toSetting P))ᶜ, majK2 cϱ (toSetting P) (envSepS P) z
        = ∫ z in (sqI (toSetting P))ᶜ,
            (cMu * P.Q) ^ 2 * majK2 cϱ (toSetting P) (envSepS P) z :=
      (integral_const_mul _ _).symm
    rw [hL, hR]
    refine setIntegral_mono_on
      (integrable_finsetSum S (fun x hx => (hMint x hx).integrableOn))
      (hMinte.integrableOn.const_mul _) measurableSet_sqI.compl ?_
    -- **the seam**: Cauchy–Schwarz in χ, POINTWISE in `(τ, τ′)`, against the nonneg ψ-kernel
    intro z _
    have hS6 := S6_family_pass_S P Qn X hsep z.1 z.2
    rw [hflat (fun _ χ => |nuFam X χ z.1| * |nuFam X χ z.2|)] at hS6
    simp only [majK2]
    set W : ℝ := (toSetting P).L ^ 2 *
        ∑ k ∈ Finset.range (toSetting P).d,
          psiA cϱ (toSetting P) (z.1 - (toSetting P).tau k)
            * psiA cϱ (toSetting P) (z.2 - (toSetting P).tau k) with hWdef
    have hWnn : 0 ≤ W :=
      mul_nonneg (sq_nonneg _) (Finset.sum_nonneg fun k _ =>
        mul_nonneg (psiA_nonneg_of hF _) (psiA_nonneg_of hF _))
    rw [← Finset.mul_sum]
    have habs : envSepS P z.1 * envSepS P z.2 ≤ |envSepS P z.1| * |envSepS P z.2| := by
      rw [← abs_mul]; exact le_abs_self _
    have key : (W * (cMu * P.Q) ^ 2) * (envSepS P z.1 * envSepS P z.2)
        ≤ (W * (cMu * P.Q) ^ 2) * (|envSepS P z.1| * |envSepS P z.2|) :=
      mul_le_mul_of_nonneg_left habs (mul_nonneg hWnn (sq_nonneg _))
    have step : W * ∑ x ∈ S, |nuFam X x.2 z.1| * |nuFam X x.2 z.2|
        ≤ W * ((cMu * P.Q) ^ 2 * (envSepS P z.1 * envSepS P z.2)) :=
      mul_le_mul_of_nonneg_left hS6 hWnn
    nlinarith [step, key]
  · -- **The degenerate branch**, `T < 0`: `d = ⌊LT/2π⌋₊ = 0`, so `majK2 ≡ 0` on both sides.
    have hd : (toSetting P).d = 0 := d_eq_zero hF (by simpa using hT)
    have hzero : ∀ ν : ℝ → ℝ, majK2 cϱ (toSetting P) ν = fun _ => 0 := by
      intro ν; funext z; simp [majK2, hd]
    simp only [hzero]
    simp [ZetaQ.Ends.famSum]

set_option maxHeartbeats 4000000 in
theorem ends_family_bound_S
    (P : ParamsQ) (Qn : ℕ) (cϱ X : ℝ) (F : LocalFun)
    (hP : P.Valid)
    (hl : Zeta23.l P.T ≠ 0)
    (hT1 : (2 * Real.pi) ^ 2 ≤ P.T)
    (hT2 : 2 * Real.pi * Real.exp 8 ≤ P.T)
    (hF : LocalHypsCoreW cϱ (toSetting P) F)
    (hν : ∀ (q : ℕ) (χ : DirichletCharacter ℂ q), Continuous (nuFam X χ))
    (hsep : ∀ τ : ℝ, Bfam Qn X τ ≤ cMu * P.Q * envSepS P τ) :
    ZetaQ.Ends.famSum Qn (fun _ χ => |calE1 (toSetting P) F (nuFam X χ)|)
      + ZetaQ.Ends.famSum Qn (fun _ χ => |calE2 (toSetting P) F (nuFam X χ)|)
    ≤ (c1S * P.Q) ^ 2 * (P.LB ^ 3 * (P.LB + Zeta23.l P.T) * (P.LL + C0Ends) ^ 2
        * (C1ends cϱ + C2ends cϱ * (1 + Real.log P.LB))) := by
  have hpi3 : (3 : ℝ) < Real.pi := Real.pi_gt_three
  have hsq : 2 * Real.pi ≤ (2 * Real.pi) ^ 2 := by nlinarith
  have hT2π : 2 * Real.pi ≤ P.T := by linarith
  have hTpos : (0 : ℝ) < P.T := by linarith
  -- the bridge: [R]'s `Setting.L` at `toSetting P` IS the paper's `L = λℒ`
  have hLB : (toSetting P).L = P.LB := S1_toSetting_L P hl
  have hcont : Continuous (envSepS P) := S3_continuous_envSep_S P hTpos
  have hNB : NuBound (toSetting P) (BendsS P) (envSepS P) := S4_nuBound_envSep_S P hP
  -- **S5**: the absorbing hypothesis `p.L ≤ B` of `calE2_maj_bound_L`, at `B := B_ends`
  have hBL : (toSetting P).L ≤ BendsS P := by rw [hLB]; exact S5_LB_le_Bends_S P hP
  -- ── 𝓔₁ half ────────────────────────────────────────────────────────────────────────
  have e1 : ZetaQ.Ends.famSum Qn (fun _ χ => |calE1 (toSetting P) F (nuFam X χ)|)
      ≤ (cMu * P.Q) ^ 2
        * (C1ends cϱ * (P.LB ^ 3 * BendsS P ^ 2 * (P.LB + Zeta23.l P.T))) := by
    calc ZetaQ.Ends.famSum Qn (fun _ χ => |calE1 (toSetting P) F (nuFam X χ)|)
        ≤ ZetaQ.Ends.famSum Qn (fun _ χ =>
            ∫ z in sqI (toSetting P), majK1 (toSetting P) F (nuFam X χ) z) :=
          famSum_mono fun q _ χ _ => abs_calE1_le_maj (hν q χ) hF hTpos
      _ ≤ (cMu * P.Q) ^ 2 * ∫ z in sqI (toSetting P), majK1 (toSetting P) F (envSepS P) z :=
          sum_majK1_le_S P Qn cϱ X F hF hν hsep
      _ ≤ (cMu * P.Q) ^ 2
            * (C1ends cϱ * (P.LB ^ 3 * BendsS P ^ 2 * (P.LB + Zeta23.l P.T))) := by
          refine mul_le_mul_of_nonneg_left ?_ (sq_nonneg _)
          have h := majK1_integral_le (cϱ := cϱ) (toSetting P) F (BendsS P) (envSepS P)
            hT1 hF hcont hNB
          rwa [hLB] at h
  -- ── 𝓔₂ half ────────────────────────────────────────────────────────────────────────
  have e2 : ZetaQ.Ends.famSum Qn (fun _ χ => |calE2 (toSetting P) F (nuFam X χ)|)
      ≤ (cMu * P.Q) ^ 2 * (C2ends cϱ
          * (P.LB ^ 3 * BendsS P ^ 2 * (1 + Real.log P.LB) * (P.LB + Zeta23.l P.T))) := by
    calc ZetaQ.Ends.famSum Qn (fun _ χ => |calE2 (toSetting P) F (nuFam X χ)|)
        ≤ ZetaQ.Ends.famSum Qn (fun _ χ =>
            ∫ z in (sqI (toSetting P))ᶜ, majK2 cϱ (toSetting P) (nuFam X χ) z) :=
          famSum_mono fun q hq χ hχ => abs_calE2_le_maj_of_integrable hF
            (majK2_integrable_fam_S P Qn cϱ X F hF hT2π hν hsep hq hχ)
      _ ≤ (cMu * P.Q) ^ 2
            * ∫ z in (sqI (toSetting P))ᶜ, majK2 cϱ (toSetting P) (envSepS P) z :=
          sum_majK2_le_S P Qn cϱ X F hF hν hsep
      _ ≤ (cMu * P.Q) ^ 2 * (C2ends cϱ
            * (P.LB ^ 3 * BendsS P ^ 2 * (1 + Real.log P.LB) * (P.LB + Zeta23.l P.T))) := by
          refine mul_le_mul_of_nonneg_left ?_ (sq_nonneg _)
          have h := majK2_integral_le (cϱ := cϱ) (toSetting P) F (BendsS P) (envSepS P)
            hT2 hF hcont hNB hBL
          rwa [hLB] at h
  -- ── the repair is free: `(c_μQ)²·B_ends² = (c₁Q)²(ℒ + C₀)²` ────────────────────────
  have hfree : (cMu * P.Q) ^ 2
        * (C1ends cϱ * (P.LB ^ 3 * BendsS P ^ 2 * (P.LB + Zeta23.l P.T)))
      + (cMu * P.Q) ^ 2 * (C2ends cϱ
          * (P.LB ^ 3 * BendsS P ^ 2 * (1 + Real.log P.LB) * (P.LB + Zeta23.l P.T)))
      = (c1S * P.Q) ^ 2 * (P.LB ^ 3 * (P.LB + Zeta23.l P.T) * (P.LL + C0Ends) ^ 2
          * (C1ends cϱ + C2ends cϱ * (1 + Real.log P.LB))) := by
    have h := scale_sq_mul_Bends_sq_S P
    linear_combination (P.LB ^ 3 * (P.LB + Zeta23.l P.T)
      * (C1ends cϱ + C2ends cϱ * (1 + Real.log P.LB))) * h
  linarith [e1, e2, hfree]

set_option maxHeartbeats 4000000 in
theorem Bfam_le_sep_S
    (P : ParamsQ) (Qn : ℕ) (X : ℝ)
    (hP : P.Valid)
    (hsieve : LargeSieveHyp)
    -- `0 < δ` puts no floor under the sieve-efficiency exponent; `c₁ = 0.41` needs
    -- `2 − δ ≤ √2π(c₁ − 3/(√2π³)) = 1.5176`.  See the docstring.
    (hQn : (Qn : ℝ) ≤ P.Q) (hX1 : 1 ≤ X)
    (hY195 : Real.log X ≤ 1.955 * Real.log P.Q) (hXb : Real.pi * X ≤ 0.0001 * P.Q ^ 2)
    (hQ0 : (1000000000 : ℝ) ≤ P.Q) :
    ∀ τ : ℝ, Bfam Qn X τ ≤ c1S * P.Q * (P.LL + C0Ends) + cMu * P.Q * logPlusQ P τ := by
  intro τ
  have hπ := Real.pi_pos
  have hT : (300:ℝ) ≤ P.T := by
    have h := hP.T_ge; unfold Zeta23.Tail.T₀ at h; exact h
  have hQ3 : (3:ℝ) ≤ P.Q := hP.Q_ge
  have hQpos : (0:ℝ) < P.Q := by linarith
  have hLL : (0:ℝ) < P.LL := LL_pos P hT hQ3
  have hXpos : (0:ℝ) < X := by linarith
  set A : ℝ := logPlusQ P τ with hAdef
  have hA0 : (0:ℝ) ≤ A := le_max_right _ _
  set Y : ℝ := Real.log X with hYdef
  have hY0 : (0:ℝ) ≤ Y := Real.log_nonneg hX1
  -- `log X ≤ (2 − δ) log Q ≤ 1.5 (ℒ − 3.46)`
  have hYle : Y ≤ 1.955 * (P.LL - 3.46) := by
    have h2 := log_Q_le P hT hQ3
    have h1 : Y ≤ 1.955 * Real.log P.Q := hY195
    linarith
  -- Minkowski: `B_fam ≤ √(Σμ²) + √(ΣP²)`
  have hBeq : Bfam Qn X τ = Real.sqrt (ZetaQ.Ends.famSum Qn (fun q χ =>
      (Zeta23.ThmE.muq (ZetaQ.parity χ) q τ
        + Zeta23.ThmE.PXc (fun n => χ (n : ZMod q)) X τ) ^ 2)) := rfl
  have hmink := sqrt_famSum_add_sq_le Qn
    (fun q χ => Zeta23.ThmE.muq (ZetaQ.parity χ) q τ)
    (fun q χ => Zeta23.ThmE.PXc (fun n => χ (n : ZMod q)) X τ)
  -- the μ half
  have hμ := sqrt_famSum_muq_le P hT hQ3 hLL Qn hQn hQ0 τ
  -- the P half
  have hPh := sqrt_famSum_PXc_le Qn X τ hsieve
  -- the sieve factor and the Chebyshev factor
  have hfl : ((⌊X⌋₊:ℝ)) ≤ X := Nat.floor_le hXpos.le
  have hfl1 : (1:ℝ) ≤ ((⌊X⌋₊:ℝ)) := by
    have h := (Nat.one_le_floor_iff X).mpr hX1
    exact_mod_cast h
  have hQnn : (0:ℝ) ≤ (Qn:ℝ) := Nat.cast_nonneg Qn
  have hQn2 : (Qn:ℝ) ^ 2 ≤ P.Q ^ 2 := by nlinarith [hQnn, hQn]
  have hπfl : Real.pi * (⌊X⌋₊ : ℝ) ≤ Real.pi * X := mul_le_mul_of_nonneg_left hfl Real.pi_pos.le
  have hfac : ((Qn:ℝ) ^ 2 + Real.pi * (⌊X⌋₊ : ℝ)) ≤ 1.0001 * P.Q ^ 2 := by linarith
  have hfac0 : (0:ℝ) ≤ ((Qn:ℝ) ^ 2 + Real.pi * (⌊X⌋₊ : ℝ)) := by
    have := mul_nonneg Real.pi_pos.le (show (0:ℝ) ≤ (⌊X⌋₊ : ℝ) from Nat.cast_nonneg _)
    nlinarith [sq_nonneg (Qn:ℝ)]
  have hcheb := cheb_sq_div_le X hX1
  have hchebV : (0:ℝ) ≤ ∑ n ∈ Finset.Ioc 0 ⌊X⌋₊, Λ n ^ 2 / n :=
    Finset.sum_nonneg fun n _ => by positivity
  have hVnn : (0:ℝ) ≤ Y ^ 2 / 2 + 12 * Y + 12 := by nlinarith
  have hprod : ((Qn:ℝ) ^ 2 + Real.pi * (⌊X⌋₊ : ℝ))
        * ∑ n ∈ Finset.Ioc 0 ⌊X⌋₊, Λ n ^ 2 / n
      ≤ (1.00005 * P.Q) ^ 2 * (Y ^ 2 / 2 + 12 * Y + 12) := by
    have h1 : ((Qn:ℝ) ^ 2 + Real.pi * (⌊X⌋₊ : ℝ))
          * ∑ n ∈ Finset.Ioc 0 ⌊X⌋₊, Λ n ^ 2 / n
        ≤ (1.0001 * P.Q ^ 2) * (Y ^ 2 / 2 + 12 * Y + 12) :=
      mul_le_mul hfac hcheb hchebV (by positivity)
    have h2 : (1.0001 * P.Q ^ 2) * (Y ^ 2 / 2 + 12 * Y + 12)
        ≤ (1.00005 * P.Q) ^ 2 * (Y ^ 2 / 2 + 12 * Y + 12) := by
      have h3 : (1.0001:ℝ) * P.Q ^ 2 ≤ (1.00005 * P.Q) ^ 2 := by nlinarith [sq_nonneg P.Q]
      exact mul_le_mul_of_nonneg_right h3 hVnn
    linarith
  have hsqrtW : Real.sqrt (((Qn:ℝ) ^ 2 + Real.pi * (⌊X⌋₊ : ℝ))
        * ∑ n ∈ Finset.Ioc 0 ⌊X⌋₊, Λ n ^ 2 / n)
      ≤ (1.00005 * P.Q) * (0.7072 * Y + 8.5) := by
    refine (Real.sqrt_le_sqrt hprod).trans ?_
    rw [Real.sqrt_mul (sq_nonneg _), Real.sqrt_sq (by positivity)]
    exact mul_le_mul_of_nonneg_left (sqrt_cheb_le Y hY0) (by positivity)
  -- assemble the two halves
  have hsum : Bfam Qn X τ
      ≤ 0.44 * P.Q * muEnvQ P τ + (1 / Real.pi) * ((1.00005 * P.Q) * (0.7072 * Y + 8.5)) := by
    rw [hBeq]
    refine hmink.trans (add_le_add hμ (hPh.trans ?_))
    exact mul_le_mul_of_nonneg_left hsqrtW (by positivity)
  -- ─── the numeric core, per unit of Q ───────────────────────────────────────────────
  have hu : (1:ℝ) / (2 * Real.pi) ≤ 0.1591612 := inv_two_pi_le
  have hv : (1:ℝ) / Real.pi ≤ 0.3183224 := inv_pi_le
  have hcmu : (0.09675:ℝ) ≤ cMu := cMu_ge
  have hlog4' : Real.log 4 ≤ 1.3863 := log_four_le
  have hlog40 : (0:ℝ) ≤ Real.log 4 := Real.log_nonneg (by norm_num)
  -- μ term, per unit of Q
  have hmuterm : 0.44 * muEnvQ P τ ≤ 0.07003093 * (P.LL + 6.3863) + 0.07003093 * A := by
    have hpos : (0:ℝ) ≤ P.LL + Real.log 4 + 5 + A := by linarith
    have h1 : (1 / (2 * Real.pi)) * (P.LL + Real.log 4 + 5 + A)
        ≤ 0.1591612 * (P.LL + Real.log 4 + 5 + A) :=
      mul_le_mul_of_nonneg_right hu hpos
    have h2 : (0.1591612:ℝ) * (P.LL + Real.log 4 + 5 + A)
        ≤ 0.1591612 * (P.LL + 1.3863 + 5 + A) := by nlinarith
    unfold muEnvQ
    rw [← hAdef]
    nlinarith [h1, h2]
  -- P term, per unit of Q
  have hPterm : (1 / Real.pi) * (1.00005 * (0.7072 * Y + 8.5))
      ≤ 0.4401270 * (P.LL - 3.46) + 2.7058764 := by
    have hnn : (0:ℝ) ≤ 1.00005 * (0.7072 * Y + 8.5) := by nlinarith
    have h1 : (1 / Real.pi) * (1.00005 * (0.7072 * Y + 8.5))
        ≤ 0.3183224 * (1.00005 * (0.7072 * Y + 8.5)) :=
      mul_le_mul_of_nonneg_right hv hnn
    have hL346 : 0 ≤ P.LL - 3.46 := by linarith
    nlinarith [h1, hYle]
  -- combine, then multiply by Q
  have hscalar : 0.44 * muEnvQ P τ + (1 / Real.pi) * (1.00005 * (0.7072 * Y + 8.5))
      ≤ c1S * (P.LL + C0Ends) + cMu * A := by
    have hAterm : (0.09675:ℝ) * A ≤ cMu * A := mul_le_mul_of_nonneg_right hcmu hA0
    unfold c1S C0Ends
    nlinarith [hmuterm, hPterm, hAterm, hLL]
  have hfinal : 0.44 * P.Q * muEnvQ P τ
        + (1 / Real.pi) * ((1.00005 * P.Q) * (0.7072 * Y + 8.5))
      ≤ c1S * P.Q * (P.LL + C0Ends) + cMu * P.Q * A := by
    have h := mul_le_mul_of_nonneg_left hscalar hQpos.le
    nlinarith [h]
  linarith [hsum, hfinal]

set_option maxHeartbeats 4000000 in
theorem frobSqGhatFam_le_Mform_add_ends_S (hP : P.Valid) (hw : 8 * P.w ≤ P.LB)
    (hl : 1 ≤ Zeta23.l P.T) (hX : 1 ≤ P.XQ) (F : Family) (Qn : ℕ)
    (hT1 : (2 * Real.pi) ^ 2 ≤ P.T) (hT2 : 2 * Real.pi * Real.exp 8 ≤ P.T)
    (hsep : ∀ τ : ℝ, Bfam Qn P.XQ τ ≤ cMu * P.Q * envSepS P τ) :
    frobSqGhatFam P F Qn
      ≤ (P.aQ ^ 2 * P.LB ^ 2)⁻¹ * familySum F Qn (fun q χ => Mform P (nuQ P q χ) (nuQ P q χ))
        + endsMajS P := by
  classical
  have hlne : Zeta23.l P.T ≠ 0 := by intro h0; rw [h0] at hl; linarith
  have hF := S2_localHypsCoreW P hP (by linarith) hl hX
  have hends := ends_family_bound_S P Qn P.cWin P.XQ (P.toParams.localFun P.T) hP hlne hT1 hT2 hF
    (fun q χ => nuFam_continuous P χ) hsep
  have ha : 0 < P.aQ := hP.aQ_pos
  have hL : 0 < P.LB := hP.LB_pos
  set c := ((P.aQ * P.LB ^ 2)⁻¹) ^ 2 with hc
  have hc0 : 0 < c := by positivity
  -- per character: `‖Ĝ(χ)‖² = c·(L²𝓜 + 𝓔₁ + 𝓔₂)`
  have hchar : ∀ q ∈ F.moduli Qn, ∀ χ ∈ primitiveChars q,
      RHLinalg.frobSq (hatQ P (gridGram P χ))
        = c * (P.LB ^ 2 * Mform P (nuQ P q χ) (nuQ P q χ)
          + calE1 (toSetting P) (P.toParams.localFun P.T) (nuQ P q χ)
          + calE2 (toSetting P) (P.toParams.localFun P.T) (nuQ P q χ)) := by
    intro q hq χ _
    have h := frobSq_char_decomp hP hw hl hX (one_le_of_mem_moduli hq) χ
    rw [← h, hc]
    field_simp
  unfold frobSqGhatFam familySum
  rw [Finset.sum_congr rfl fun q hq =>
    Finset.sum_congr rfl fun χ hχ => hchar q hq χ (F.chars_subset q hχ)]
  -- bound the `𝓔` part by the family sum of absolute values over `Icc 1 Qn`
  have hE : ∑ q ∈ F.moduli Qn, ∑ χ ∈ F.chars q,
        (calE1 (toSetting P) (P.toParams.localFun P.T) (nuQ P q χ)
          + calE2 (toSetting P) (P.toParams.localFun P.T) (nuQ P q χ))
      ≤ ZetaQ.Ends.famSum Qn (fun _ χ => |calE1 (toSetting P) (P.toParams.localFun P.T) (nuFam P.XQ χ)|)
        + ZetaQ.Ends.famSum Qn (fun _ χ => |calE2 (toSetting P) (P.toParams.localFun P.T) (nuFam P.XQ χ)|) := by
    have hR : ZetaQ.Ends.famSum Qn (fun _ χ => |calE1 (toSetting P) (P.toParams.localFun P.T) (nuFam P.XQ χ)|)
        + ZetaQ.Ends.famSum Qn (fun _ χ => |calE2 (toSetting P) (P.toParams.localFun P.T) (nuFam P.XQ χ)|)
        = ∑ q ∈ Finset.Icc 1 Qn, ∑ χ ∈ primitiveChars q,
            (|calE1 (toSetting P) (P.toParams.localFun P.T) (nuQ P q χ)|
              + |calE2 (toSetting P) (P.toParams.localFun P.T) (nuQ P q χ)|) := by
      unfold ZetaQ.Ends.famSum
      rw [← Finset.sum_add_distrib]
      refine Finset.sum_congr rfl fun q _ => ?_
      rw [← Finset.sum_add_distrib]
      rfl
    rw [hR]
    refine le_trans (Finset.sum_le_sum fun q _ => Finset.sum_le_sum fun χ _ =>
      add_le_add (le_abs_self _) (le_abs_self _)) ?_
    refine le_trans (Finset.sum_le_sum fun q _ =>
      Finset.sum_le_sum_of_subset_of_nonneg (F.chars_subset q)
        (fun χ _ _ => add_nonneg (abs_nonneg _) (abs_nonneg _))) ?_
    refine Finset.sum_le_sum_of_subset_of_nonneg (moduli_subset_Icc F Qn) ?_
    intro q _ _
    exact Finset.sum_nonneg fun χ _ => add_nonneg (abs_nonneg _) (abs_nonneg _)
  have hM : ∑ q ∈ F.moduli Qn, ∑ χ ∈ F.chars q,
        c * (P.LB ^ 2 * Mform P (nuQ P q χ) (nuQ P q χ)
          + calE1 (toSetting P) (P.toParams.localFun P.T) (nuQ P q χ)
          + calE2 (toSetting P) (P.toParams.localFun P.T) (nuQ P q χ))
      = (P.aQ ^ 2 * P.LB ^ 2)⁻¹
          * ∑ q ∈ F.moduli Qn, ∑ χ ∈ F.chars q, Mform P (nuQ P q χ) (nuQ P q χ)
        + c * ∑ q ∈ F.moduli Qn, ∑ χ ∈ F.chars q,
            (calE1 (toSetting P) (P.toParams.localFun P.T) (nuQ P q χ)
              + calE2 (toSetting P) (P.toParams.localFun P.T) (nuQ P q χ)) := by
    rw [Finset.mul_sum, Finset.mul_sum, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun q _ => ?_
    rw [Finset.mul_sum, Finset.mul_sum, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun χ _ => ?_
    rw [hc]
    field_simp
    ring
  rw [hM]
  unfold endsMajS
  rw [← hc]
  have := mul_le_mul_of_nonneg_left (hE.trans hends) hc0.le
  linarith


end F1c
end ShellK
end ZetaShell
