/-
F1c-2 (L7_3, round 5): **the in-zone and cross half at the Shell design**, `shell_inzone`. GENERATED by
`py/gen_inzone.py` from the green tree: ZetaQ's `InZone.famPP_le_zone_split` re-run on `ShellDesignM S53L75` and closed
by `inzone_arith` (`LF_InArith`, the in-zone-and-cross part of `final_arith`) in place of `final_arith`.
Substitutions: `design_regime` → A7 (the budget from `X ≤ Q^{2−9/200}`: `lemma43_budget_is_Qsq` at `δ = 9/200`, with
A7's `2Q^{−9/200} ≤ 1/K`); `design_basic` → `design_basic_shell`; `NfamQ_sharp` → `NfamQ_sharp_shell`; `zone_facts` →
`zone_facts_shell` (the `DesignFamily` transfer); `reg_eventually` → `reg_shell` (transfer of `designFamily_reg`);
`ERRin_small_eventually`, `sizeR_LL_le_NfamQ_eventually` → Shell copies below; `cWinDesign` → C1's `cWinShell`;
`F` → `Family.qle`; the small parameter `δ = min(1, η/(48C + 32))`, and the witness `e = δ`.
-/
import ZetaShell.ShellK.LF_Transfer
import ZetaShell.Skeleton.LF_AsmBase
import ZetaShell.ShellK.LF_InArith


noncomputable section
open scoped BigOperators
open ComplexConjugate MeasureTheory Set Filter

namespace ZetaShell
namespace ShellK
namespace F1c

open ZetaQ ZetaQ.InZone ZetaQ.Zones ZetaQ.Payoff

theorem reg_shell (r ε : ℝ) (hr : 3 ≤ r) (hε : 0 < ε) :
    ∀ᶠ Qn : ℕ in atTop, ∀ P : ParamsQ, Design.ShellDesignM S53L75 r ε (Qn : ℝ) P →
      P.Valid ∧ 8 * P.w ≤ P.LB ∧ (8:ℝ) ≤ P.LB ∧ (8:ℝ) ≤ P.s0 ∧
        P.s0 ≤ Real.log P.Q ∧ P.LB ≤ 4 * Real.log P.Q ∧
        Real.log P.Q ^ 3 ≤ P.T ∧ (144:ℝ) ≤ Real.log P.Q ∧
        Real.log P.Q / 2 ≤ P.s0 := by
  refine transfer_of_shellDesign r ε hr hε _ (fun D hD => ?_)
  filter_upwards [designFamily_reg D (r + ε) hD, hD.Q_eq] with Q h hQ
  rw [hQ]
  exact h

set_option maxHeartbeats 4000000 in
theorem ERRin_small_shell (r ε : ℝ) (hr : 3 ≤ r) (hε : 0 < ε) {δ : ℝ}
    (hδ : 0 < δ) :
    ∀ᶠ Qn : ℕ in atTop, ∀ P : ParamsQ, Design.ShellDesignM S53L75 r ε (Qn : ℝ) P →
      ERRin P Qn ≤ δ * Family.qle.sizeR Qn := by
  have hS2 : ((S53L75.lam : ℚ) : ℝ) ≤ 191 / 100 := by norm_num [S53L75]
  have hK1 : (1 : ℝ) ≤ max 500 (160 / δ + 36) := le_trans (by norm_num) (le_max_left _ _)
  filter_upwards [Design.shellDesign_regime S53L75 hS2 r ε hr hε _ hK1, eventually_ge_atTop 2] with Qn hreg hQn2
  intro P hdes
  obtain ⟨hlogK, -, -, -, hszK, -, -, -⟩ := hreg P hdes
  have hP := hdes.1
  have hQ := (hdes.2.1 : P.Q = (Qn : ℝ))
  have h500 : (500 : ℝ) ≤ max 500 (160 / δ + 36) := le_max_left _ _
  have h80 : 160 / δ + 36 ≤ max 500 (160 / δ + 36) := le_max_right _ _
  have hsz : 500 * (1 + Real.log Qn) ^ 2 ≤ Qn :=
    le_trans (mul_le_mul_of_nonneg_right h500 (sq_nonneg _)) hszK
  have h36 : 36 ≤ Real.log Qn := by
    have : 160 / δ + 36 ≤ Real.log Qn := h80.trans hlogK
    have : 0 ≤ 160 / δ := by positivity
    linarith
  have h := ERRin_le_sizeR Family.qle Qn P hP hQ hQn2 h36 hsz
  refine h.trans ?_
  have hS0 : 0 ≤ Family.qle.sizeR Qn := by unfold Family.sizeR; positivity
  refine mul_le_mul_of_nonneg_right ?_ hS0
  have hlog : 160 / δ ≤ Real.log Qn := by linarith [h80.trans hlogK]
  have hlogpos : 0 < Real.log Qn := by linarith [show (0:ℝ) < 160 / δ by positivity]
  rw [div_le_iff₀ (by positivity)]
  have h1 : 160 ≤ Real.log Qn * δ := (div_le_iff₀ hδ).mp hlog
  have h2 : Real.log Qn ≤ Real.log Qn ^ 2 := by nlinarith
  nlinarith

set_option maxHeartbeats 4000000 in
theorem sizeR_LL_le_NfamQ_shell (r ε : ℝ) (hr : 3 ≤ r) (hε : 0 < ε) {η : ℝ}
    (hη : 0 < η) (hη1 : η ≤ 1) :
    ∀ᶠ Qn : ℕ in atTop, ∀ P : ParamsQ, Design.ShellDesignM S53L75 r ε (Qn : ℝ) P →
      Family.qle.sizeR Qn * (P.T / (2 * Real.pi) * P.LL) ≤ (1 + η) * NfamQ P Family.qle Qn := by
  have hS2 : ((S53L75.lam : ℚ) : ℝ) ≤ 191 / 100 := by norm_num [S53L75]
  have hC := FrobAssembly.Cconst_pos Family.qle
  have hK1 : (1 : ℝ) ≤ 300 / η := by rw [le_div_iff₀ hη]; linarith
  have hη3 : 0 < η / 3 := by positivity
  filter_upwards [Design.shellDesign_regime S53L75 hS2 r ε hr hε _ hK1,
    NfamQ_sharp_shell r ε hr hε hη3 (by linarith), eventually_ge_atTop 2]
    with Qn hreg hsharp hQn2
  intro P hdes
  obtain ⟨-, -, -, -, hszK, -, -, -⟩ := hreg P hdes
  have hP := hdes.1
  have hQ := (hdes.2.1 : P.Q = (Qn : ℝ))
  have hN := hsharp P hdes
  have hT0 : 0 < P.T := hP.T_pos
  have hLL0 : 0 < P.LL := hP.LL_pos
  have hQn0 : (0 : ℝ) < Qn := by exact_mod_cast (show 0 < Qn by omega)
  have hX0 : 0 ≤ P.T / (2 * Real.pi) * P.LL := by positivity
  have hsz := Cconst_mul_sizeR_le Family.qle Qn hQn2
  -- `100 Qn (1+log Qn)² ≤ (η/3) Qn²`
  have h100 : 100 * (Qn : ℝ) * (1 + Real.log Qn) ^ 2 ≤ η / 3 * (Qn : ℝ) ^ 2 := by
    have := mul_le_mul_of_nonneg_left hszK hQn0.le
    have e : (Qn : ℝ) * (300 / η * (1 + Real.log Qn) ^ 2) = (300 / η) * ((Qn : ℝ) * (1 + Real.log Qn) ^ 2) := by ring
    rw [e] at this
    have h2 : (300 / η) * ((Qn : ℝ) * (1 + Real.log Qn) ^ 2) ≤ (Qn : ℝ) ^ 2 := by nlinarith
    rw [div_mul_eq_mul_div, div_le_iff₀ hη] at h2
    nlinarith
  have hCS : Family.qle.Cconst * Family.qle.sizeR Qn ≤ (1 + η / 3) * (Qn : ℝ) ^ 2 := by nlinarith
  have hS0 : 0 ≤ Family.qle.sizeR Qn := by unfold Family.sizeR; positivity
  -- `|𝔉| X ≤ (1+η/3) Qn² X / C ≤ (1+η/3)² N`
  have h1 : Family.qle.Cconst * (Family.qle.sizeR Qn * (P.T / (2 * Real.pi) * P.LL))
      ≤ (1 + η / 3) * ((Qn : ℝ) ^ 2 * (P.T / (2 * Real.pi) * P.LL)) := by
    have := mul_le_mul_of_nonneg_right hCS hX0
    nlinarith
  have h2 : (Qn : ℝ) ^ 2 * (P.T / (2 * Real.pi) * P.LL) ≤ Family.qle.Cconst * (1 + η / 3) * NfamQ P Family.qle Qn := by
    have := hN
    nlinarith
  have hN0 := NfamQ_nonneg P Family.qle Qn
  have h3 : Family.qle.Cconst * (Family.qle.sizeR Qn * (P.T / (2 * Real.pi) * P.LL))
      ≤ Family.qle.Cconst * ((1 + η / 3) * (1 + η / 3) * NfamQ P Family.qle Qn) := by
    calc Family.qle.Cconst * (Family.qle.sizeR Qn * (P.T / (2 * Real.pi) * P.LL))
        ≤ (1 + η / 3) * ((Qn : ℝ) ^ 2 * (P.T / (2 * Real.pi) * P.LL)) := h1
      _ ≤ (1 + η / 3) * (Family.qle.Cconst * (1 + η / 3) * NfamQ P Family.qle Qn) :=
          mul_le_mul_of_nonneg_left h2 (by positivity)
      _ = _ := by ring
  have h4 := le_of_mul_le_mul_left h3 hC
  have h5 : (1 + η / 3) * (1 + η / 3) ≤ 1 + η := by nlinarith
  calc Family.qle.sizeR Qn * (P.T / (2 * Real.pi) * P.LL)
      ≤ (1 + η / 3) * (1 + η / 3) * NfamQ P Family.qle Qn := h4
    _ ≤ (1 + η) * NfamQ P Family.qle Qn := mul_le_mul_of_nonneg_right h5 hN0

set_option maxHeartbeats 8000000 in
theorem shell_inzone (r ε : ℝ) (hr : 3 ≤ r) (hε : 0 < ε) (η : ℝ) (hη : 0 < η) :
    ∃ e : ℝ, 0 < e ∧ ∀ᶠ Qn : ℕ in atTop, ∀ P : ParamsQ, Design.ShellDesignM S53L75 r ε (Qn : ℝ) P →
      inCrossRHS Qn P e
        ≤ (P.aQ * P.LB) ^ 2 * (FrobAssembly.K0a (zoneFactor P) (vDesign P) + η) * NfamQ P Family.qle Qn := by
  have hS2 : ((S53L75.lam : ℚ) : ℝ) ≤ 191 / 100 := by norm_num [S53L75]
  obtain ⟨Cs, hCs0, hdiag⟩ := lemma43_diagonal (Design.cWinShell S53L75)
  obtain ⟨CM, hCM0, hclose⟩ := sumA2gQ_close
  obtain ⟨Lρ, Tρ, hρ⟩ := FrobAssembly.rhoU_univ_le_pointwise (Design.cWinShell S53L75)
  have hC := FrobAssembly.Cconst_pos Family.qle
  have hpi := Real.pi_pos
  -- the small parameter
  obtain ⟨δ, hδdef⟩ : ∃ δ : ℝ, δ = min 1 (η / (48 * Family.qle.Cconst + 32)) := ⟨_, rfl⟩
  have hδ0 : 0 < δ := by rw [hδdef]; exact lt_min one_pos (by positivity)
  have hδ1 : δ ≤ 1 := by rw [hδdef]; exact min_le_left _ _
  have hδδ : δ ^ 2 ≤ δ := by
    have := mul_le_mul_of_nonneg_left hδ1 hδ0.le
    rw [mul_one] at this
    rw [pow_two]
    exact this
  have hδε : δ * (48 * Family.qle.Cconst + 32) ≤ η := by
    have h : δ ≤ η / (48 * Family.qle.Cconst + 32) := by rw [hδdef]; exact min_le_right _ _
    have hpos : 0 < 48 * Family.qle.Cconst + 32 := by positivity
    calc δ * (48 * Family.qle.Cconst + 32) ≤ η / (48 * Family.qle.Cconst + 32) * (48 * Family.qle.Cconst + 32) :=
          mul_le_mul_of_nonneg_right h hpos.le
      _ = η := div_mul_cancel₀ _ hpos.ne'
  have hδ3 : 0 < δ / 3 := by positivity
  have hδ31 : δ / 3 ≤ 1 := by linarith
  refine ⟨δ, hδ0, ?_⟩
  -- the thresholds
  have hK₁ : (1:ℝ) ≤ max 1 (Cs / δ + 1) := le_max_left _ _
  have hK₂ : (1:ℝ) ≤ max 1 (96 / (Real.pi * δ ^ 2)) := le_max_left _ _
  have hK₃ : (1:ℝ) ≤ max 1 (max Lρ Tρ) := le_max_left _ _
  have hK₄ : (1:ℝ) ≤ 500 := by norm_num
  have hK₅ : (1:ℝ) ≤ max 1 (3 / δ) := le_max_left _ _
  have hK₆ : (1:ℝ) ≤ max 1 (128 * Family.qle.Cconst * CM / (9 * δ)) := le_max_left _ _
  filter_upwards [Design.shellDesign_regime S53L75 hS2 r ε hr hε _ hK₁, Design.shellDesign_regime S53L75 hS2 r ε hr hε _ hK₂,
    Design.shellDesign_regime S53L75 hS2 r ε hr hε _ hK₃, Design.shellDesign_regime S53L75 hS2 r ε hr hε _ hK₄,
    Design.shellDesign_regime S53L75 hS2 r ε hr hε _ hK₅, Design.shellDesign_regime S53L75 hS2 r ε hr hε _ hK₆,
    design_basic_shell r ε hr hε,
    NfamQ_sharp_shell r ε hr hε hδ3 hδ31,
    zone_facts_shell r ε hr hε hδ0,
    zone_facts_shell r ε hr hε (ε₀ := δ ^ 2) (by positivity),
    ERRin_small_shell r ε hr hε hδ3,
    sizeR_LL_le_NfamQ_shell r ε hr hε hδ3 hδ31,
    reg_shell r ε hr hε]
    with Qn hreg₁ hreg₂ hreg₃ hreg₄ hreg₅ hreg₆ hbas hsharp hz1 hz2 herr hsN hregQ
  intro P hdes
  have hP := hdes.1
  have hQ := (hdes.2.1 : P.Q = (Qn : ℝ))
  obtain ⟨hlogK₁, hTK₁, -, -, -, hX32, -, -⟩ := hreg₁ P hdes
  obtain ⟨-, hTK₂, -, -, -, -, -, -⟩ := hreg₂ P hdes
  obtain ⟨hlogK₃, hTK₃, -, -, -, -, -, -⟩ := hreg₃ P hdes
  obtain ⟨-, -, -, -, hszK₄, -, -, -⟩ := hreg₄ P hdes
  obtain ⟨-, -, -, -, -, -, hQhalf₅, -⟩ := hreg₅ P hdes
  obtain ⟨hlogK₆, -, -, -, -, -, -, -⟩ := hreg₆ P hdes
  obtain ⟨hLL30, hL8, hlam, hw, hQn2⟩ := hbas P hdes
  obtain ⟨-, -, -, hs8, -, -, -, -, -⟩ := hregQ P hdes
  obtain ⟨hz1a, -⟩ := hz1 P hdes
  obtain ⟨-, hz2b⟩ := hz2 P hdes
  have hN := hsharp P hdes
  have herr' := herr P hdes
  have hsN' := hsN P hdes
  have hs0 : 0 ≤ P.s0 := by linarith
  have hQn : Qn ≤ ⌊P.Q⌋₊ := by rw [hQ, Nat.floor_natCast]
  have hQn1 : 1 ≤ Qn := by omega
  have hQnR : (2:ℝ) ≤ Qn := by exact_mod_cast hQn2
  have hQn0 : (0:ℝ) < Qn := by linarith
  have hTpos : 0 < P.T := hP.T_pos
  have hLL0 : 0 < P.LL := hP.LL_pos
  have hL0 : 0 < P.LB := hP.LB_pos
  have ha := hP.a_ge
  have ha0 := hP.aQ_pos
  have hcW : P.cWin = Design.cWinShell S53L75 := Design.cWin_of_shellDesignM hdes
  have hreg' : RegimeQ P := FrobAssembly.regimeQ_of hP hL8
  have hLS := largeSieveFamily_holds
  have hlogQ : Real.log Qn ≤ P.LL := (log_Qn_le_LL hP hQn1 hQ).1
  have hadm := vDesign_admissible hP
  -- ── (1) the master inequality
  -- ── (2) the diagonal: `D_ℝ = (T/π) S (1+Esm)`, `|Esm| ≤ Cs/T ≤ δ`, `D_ℝ > 0`
  obtain ⟨Esm, hEsm, hdg⟩ := hdiag P hP hreg' hw (by rw [hcW])
  have hSpos : (0:ℝ) < sumA2gQ P := by
    have h := sumA2gQ_lower_const P hP hreg' hw
    have hlog2 : (0:ℝ) < Real.log 2 := Real.log_pos (by norm_num)
    have hlog2le : Real.log 2 ≤ 1 := by
      have := Real.log_le_sub_one_of_pos (show (0:ℝ) < 2 by norm_num); linarith
    have h6 : 0 < 6 - Real.log 2 := by linarith
    have h7 : 0 < Real.log 2 ^ 2 / 2 * (6 - Real.log 2) / 1296 := by positivity
    linarith only [h, h7]
  have hTCs : Cs / δ + 1 ≤ P.T := le_trans (le_max_right _ _) hTK₁
  have hCsδ : Cs ≤ P.T * δ := by
    have : Cs / δ ≤ P.T := by linarith
    rwa [div_le_iff₀ hδ0] at this
  have hEsmδ : |Esm| ≤ δ := by
    refine hEsm.trans ?_
    rw [div_le_iff₀ hTpos]
    linarith
  have hEsm1 : |Esm| < 1 := by
    refine lt_of_le_of_lt hEsm ?_
    rw [div_lt_one hTpos]
    have : Cs / δ ≥ Cs := by
      rw [ge_iff_le, le_div_iff₀ hδ0]
      exact mul_le_of_le_one_right hCs0.le hδ1
    linarith
  have hTS : 0 < P.T / Real.pi * sumA2gQ P := by positivity
  have hDpos : 0 < ∫ s : ℝ, P.gQ s * (normA2 P s + normB2 P s) := by
    rw [hdg]
    exact mul_pos hTS (by linarith [(abs_lt.mp hEsm1).1])
  have hD0 : 0 ≤ ∫ s : ℝ, P.gQ s * (normA2 P s + normB2 P s) := hDpos.le
  -- ── (3) the cross term: `2 N_ℝ = ρ D_ℝ`, `ρ ≤ δ`
  have hρ0 : 0 ≤ rhoU P Set.univ := rhoU_nonneg P Set.univ MeasurableSet.univ
  have hNρ : 2 * (∫ s : ℝ, P.gQ s * Real.sqrt (normA2 P s) * Real.sqrt (normB2 P s))
      ≤ rhoU P Set.univ * ∫ s : ℝ, P.gQ s * (normA2 P s + normB2 P s) := by
    have hDne : (∫ s : ℝ, P.gQ s * (normA2 P s + normB2 P s)) ≠ 0 := hDpos.ne'
    have e : rhoU P Set.univ * (∫ s : ℝ, P.gQ s * (normA2 P s + normB2 P s))
        = 2 * ∫ s : ℝ, P.gQ s * Real.sqrt (normA2 P s) * Real.sqrt (normB2 P s) := by
      unfold rhoU
      simp only [MeasureTheory.setIntegral_univ]
      field_simp
    rw [e]
  have hρδ : rhoU P Set.univ ≤ δ := by
    have hLρ : Lρ ≤ P.LB := by
      have : Lρ ≤ max 1 (max Lρ Tρ) := le_trans (le_max_left _ _) (le_max_right _ _)
      linarith [this.trans hlogK₃, hlogQ, FrobAssembly.LL_le_LB hP hlam]
    have hTρ : Tρ ≤ P.T := by
      have : Tρ ≤ max 1 (max Lρ Tρ) := le_trans (le_max_right _ _) (le_max_right _ _)
      linarith [this.trans hTK₃]
    have h := hρ P hP hw (by rw [hcW]) hLρ hTρ
    refine h.trans ?_
    have hT96 : 96 / (Real.pi * δ ^ 2) ≤ P.T := le_trans (le_max_right _ _) hTK₂
    unfold rhoConstConservative
    rw [← Real.sqrt_mul (by positivity)]
    have harg : 48 / Real.pi * (2 / P.T) ≤ δ ^ 2 := by
      rw [div_le_iff₀ (by positivity)] at hT96
      rw [show 48 / Real.pi * (2 / P.T) = 96 / (Real.pi * P.T) by
          rw [div_mul_div_comm]; norm_num, div_le_iff₀ (by positivity)]
      linarith
    calc Real.sqrt (48 / Real.pi * (2 / P.T)) ≤ Real.sqrt (δ ^ 2) := Real.sqrt_le_sqrt harg
      _ = δ := Real.sqrt_sq hδ0.le
  -- ── (4) the Mertens evaluation: `D_ℝ ≤ (X W k + E)(1+δ)`
  have hIL := FrobAssembly.intervalIntegral_gQ_mul_eq hP hw
  have hSle : sumA2gQ P
      ≤ P.LL * (P.aQ * P.LB) ^ 2 * (K0 (vDesign P) + K1 (vDesign P)) / 2 + CM * P.LB ^ 2 := by
    have h := (abs_le.mp (hclose P hP hw hL8)).2
    rw [hIL] at h
    linarith
  have hDle : (∫ s : ℝ, P.gQ s * (normA2 P s + normB2 P s))
      ≤ (P.T / (2 * Real.pi) * P.LL * (P.aQ * P.LB) ^ 2 * (K0 (vDesign P) + K1 (vDesign P))
          + P.T / Real.pi * (CM * P.LB ^ 2)) * (1 + δ) := by
    rw [hdg]
    have hE1 : P.T / Real.pi * sumA2gQ P
        ≤ P.T / (2 * Real.pi) * P.LL * (P.aQ * P.LB) ^ 2 * (K0 (vDesign P) + K1 (vDesign P))
          + P.T / Real.pi * (CM * P.LB ^ 2) := by
      have := mul_le_mul_of_nonneg_left hSle (by positivity : 0 ≤ P.T / Real.pi)
      calc P.T / Real.pi * sumA2gQ P
          ≤ P.T / Real.pi * (P.LL * (P.aQ * P.LB) ^ 2 * (K0 (vDesign P) + K1 (vDesign P)) / 2
              + CM * P.LB ^ 2) := this
        _ = _ := by ring
    have hE2 : 1 + Esm ≤ 1 + δ := by linarith [(abs_le.mp hEsmδ).2]
    exact mul_le_mul hE1 hE2 (by linarith [(abs_lt.mp hEsm1).1])
      (add_nonneg (mul_nonneg (by positivity) (FrobAssembly.K0_add_K1_nonneg hadm)) (by positivity))
  -- ── (5) the budget: `B ≤ Q²(1+δ)`, `B X ≤ (1+δ)² C N`
  have hQ1 : (1:ℝ) ≤ P.Q := by rw [hQ]; linarith
  have hQ2pos : 0 < P.Q ^ 2 := by rw [hQ]; positivity
  have hBQ : sieveBudgetQ P ≤ P.Q ^ 2 * (1 + δ) := by
    have hbud := lemma43_budget_is_Qsq P (δ := Design.deltaShell) (by norm_num [Design.deltaShell]) (by norm_num [Design.deltaShell]) hX32 hQ1
    have h3 : sieveBudgetQ P / P.Q ^ 2 ≤ 1 + 4 * Real.rpow P.Q (-Design.deltaShell) := by
      linarith [(abs_le.mp hbud).2]
    -- Gallagher budget: `lemma43_budget_is_Qsq`'s constant is `4` (was `2`); `design_regime`'s
    -- unchanged `2Q^{−1/2} ≤ 1/max 1 (3/δ) ≤ δ/3` still gives `4Q^{−1/2} ≤ 2δ/3 ≤ δ`.
    have h4 : 4 * Real.rpow P.Q (-Design.deltaShell) ≤ δ := by
      have hm : 3 / δ ≤ max 1 (3 / δ) := le_max_right _ _
      have hmpos : 0 < max 1 (3 / δ) := by positivity
      have h5 : 3 ≤ max 1 (3 / δ) * δ := by
        have := mul_le_mul_of_nonneg_right hm hδ0.le
        rwa [div_mul_cancel₀ _ hδ0.ne'] at this
      have h6 : 1 / max 1 (3 / δ) ≤ δ / 3 := by
        rw [div_le_div_iff₀ hmpos (by norm_num)]
        linarith
      linarith [hQhalf₅]
    calc sieveBudgetQ P = sieveBudgetQ P / P.Q ^ 2 * P.Q ^ 2 :=
          (div_mul_cancel₀ _ hQ2pos.ne').symm
      _ ≤ (1 + δ) * P.Q ^ 2 := mul_le_mul_of_nonneg_right (by linarith) hQ2pos.le
      _ = P.Q ^ 2 * (1 + δ) := by ring
  have hX0 : 0 ≤ P.T / (2 * Real.pi) * P.LL := by positivity
  have hN0 : 0 ≤ NfamQ P Family.qle Qn := NfamQ_nonneg P Family.qle Qn
  have hQ2X : P.Q ^ 2 * (P.T / (2 * Real.pi) * P.LL) ≤ Family.qle.Cconst * (1 + δ / 3) * NfamQ P Family.qle Qn := by
    rw [hQ]
    calc (Qn:ℝ) ^ 2 * (P.T / (2 * Real.pi) * P.LL)
        = (Qn:ℝ) ^ 2 * (P.T / (2 * Real.pi)) * P.LL := by ring
      _ ≤ _ := hN
  have hCN0 : 0 ≤ Family.qle.Cconst * NfamQ P Family.qle Qn := by positivity
  have hBX : sieveBudgetQ P * (P.T / (2 * Real.pi) * P.LL)
      ≤ (1 + δ) ^ 2 * Family.qle.Cconst * NfamQ P Family.qle Qn := by
    calc sieveBudgetQ P * (P.T / (2 * Real.pi) * P.LL)
        ≤ P.Q ^ 2 * (1 + δ) * (P.T / (2 * Real.pi) * P.LL) :=
          mul_le_mul_of_nonneg_right hBQ hX0
      _ = (1 + δ) * (P.Q ^ 2 * (P.T / (2 * Real.pi) * P.LL)) := by ring
      _ ≤ (1 + δ) * (Family.qle.Cconst * (1 + δ / 3) * NfamQ P Family.qle Qn) :=
          mul_le_mul_of_nonneg_left hQ2X (by linarith)
      _ = (1 + δ) * (1 + δ / 3) * (Family.qle.Cconst * NfamQ P Family.qle Qn) := by ring
      _ ≤ (1 + δ) * (1 + δ) * (Family.qle.Cconst * NfamQ P Family.qle Qn) := by
          apply mul_le_mul_of_nonneg_right _ hCN0
          apply mul_le_mul_of_nonneg_left (by linarith) (by linarith)
      _ = (1 + δ) ^ 2 * Family.qle.Cconst * NfamQ P Family.qle Qn := by ring
  -- ── (6) `K_f X ≤ (1+δ)² N`, `K_f ≤ B`, `0 ≤ K_f`
  have hS0 : 0 ≤ Family.qle.sizeR Qn := by unfold Family.sizeR; positivity
  have hERR0 : 0 ≤ ERRin P Qn := ERRin_nonneg P Qn hs0
  have hK0 : 0 ≤ Family.qle.sizeR Qn + ERRin P Qn := by linarith
  have hKfle : Family.qle.sizeR Qn + ERRin P Qn ≤ (1 + δ / 3) * Family.qle.sizeR Qn := by linarith
  have hKX : (Family.qle.sizeR Qn + ERRin P Qn) * (P.T / (2 * Real.pi) * P.LL)
      ≤ (1 + δ) ^ 2 * NfamQ P Family.qle Qn := by
    calc (Family.qle.sizeR Qn + ERRin P Qn) * (P.T / (2 * Real.pi) * P.LL)
        ≤ (1 + δ / 3) * Family.qle.sizeR Qn * (P.T / (2 * Real.pi) * P.LL) :=
          mul_le_mul_of_nonneg_right hKfle hX0
      _ = (1 + δ / 3) * (Family.qle.sizeR Qn * (P.T / (2 * Real.pi) * P.LL)) := by ring
      _ ≤ (1 + δ / 3) * ((1 + δ / 3) * NfamQ P Family.qle Qn) :=
          mul_le_mul_of_nonneg_left hsN' (by linarith)
      _ = (1 + δ / 3) * (1 + δ / 3) * NfamQ P Family.qle Qn := by ring
      _ ≤ (1 + δ) * (1 + δ) * NfamQ P Family.qle Qn := by
          apply mul_le_mul_of_nonneg_right _ hN0
          apply mul_le_mul (by linarith) (by linarith) (by linarith) (by linarith)
      _ = (1 + δ) ^ 2 * NfamQ P Family.qle Qn := by ring
  have hsize := FrobAssembly.sizeR_le_point Family.qle Qn hQn1 hszK₄
  have hXQ1 : (1:ℝ) ≤ P.XQ := by
    unfold ParamsQ.XQ
    exact Real.one_le_exp hL0.le
  have hKB : Family.qle.sizeR Qn + ERRin P Qn ≤ sieveBudgetQ P := by
    have h1' : Family.qle.sizeR Qn + ERRin P Qn ≤ (1 + δ / 3) * (0.2 * (Qn:ℝ) ^ 2) :=
      hKfle.trans (mul_le_mul_of_nonneg_left hsize (by linarith))
    have h2' : (1 + δ / 3) * (0.2 * (Qn:ℝ) ^ 2) ≤ (4 / 3) * (0.2 * (Qn:ℝ) ^ 2) :=
      mul_le_mul_of_nonneg_right (by linarith) (by positivity)
    have h3' : (Qn:ℝ) ^ 2 ≤ sieveBudgetQ P := by
      have hπX : 0 ≤ Real.pi * P.XQ := mul_nonneg Real.pi_pos.le (by linarith)
      unfold sieveBudgetQ; rw [hQ]; linarith
    linarith only [h1', h2', h3', sq_nonneg (Qn:ℝ)]
  -- ── (7) the zone facts
  have hP1 : P.T / (2 * Real.pi) * (∫ u in Set.Icc 0 P.s0, u * P.gQ u) * (1 - δ) ≤ zoneP P := by
    have := (abs_le.mp hz1a).1; linarith only [this]
  have hP2 : zoneP P ≤ P.T / (2 * Real.pi) * (∫ u in Set.Icc 0 P.s0, u * P.gQ u) * (1 + δ) := by
    have := (abs_le.mp hz1a).2; linarith only [this]
  have hR : zoneR P ≤ δ ^ 2 * zoneP P := hz2b
  have hI₀0 : 0 ≤ ∫ u in Set.Icc 0 P.s0, u * P.gQ u :=
    setIntegral_nonneg measurableSet_Icc fun u hu => mul_nonneg hu.1 (lemma42_g_nonneg P u)
  have hM0 : 0 ≤ P.T / (2 * Real.pi) * ∫ u in Set.Icc 0 P.s0, u * P.gQ u := by positivity
  have hM : 2 * (P.T / (2 * Real.pi) * ∫ u in Set.Icc 0 P.s0, u * P.gQ u)
      = P.T / (2 * Real.pi) * P.LL * (P.aQ * P.LB) ^ 2 * FrobAssembly.K0a (zoneFactor P) (vDesign P) :=
    zoneMain_eq P hP hw hs0
  -- ── (8) the kernel pieces
  have hk : K0 (vDesign P) + K1 (vDesign P)
      = FrobAssembly.K0a (zoneFactor P) (vDesign P) + FrobAssembly.K1a (zoneFactor P) (vDesign P) := by
    rw [FrobAssembly.K0a_add_K1a hadm, K0_add_K1 hadm]
  have hk0 : 0 ≤ FrobAssembly.K0a (zoneFactor P) (vDesign P) := FrobAssembly.K0a_nonneg hadm _
  have hk1 : 0 ≤ FrobAssembly.K1a (zoneFactor P) (vDesign P) := FrobAssembly.K1a_nonneg hadm _
  have hk2 : K0 (vDesign P) + K1 (vDesign P) ≤ 2 :=
    FrobAssembly.K0_add_K1_le_two hadm hP.lam_lt_two.le
  have hW0 : 0 ≤ (P.aQ * P.LB) ^ 2 := by positivity
  -- ── (9) the Mertens-remainder term: `B E ≤ δ W N`
  have hE0 : 0 ≤ P.T / Real.pi * (CM * P.LB ^ 2) := by positivity
  have hBE : sieveBudgetQ P * (P.T / Real.pi * (CM * P.LB ^ 2))
      ≤ δ * (P.aQ * P.LB) ^ 2 * NfamQ P Family.qle Qn := by
    have hLL128 : 128 * Family.qle.Cconst * CM / (9 * δ) ≤ P.LL :=
      le_trans (le_trans (le_max_right _ _) hlogK₆) hlogQ
    have hB0 : 0 ≤ sieveBudgetQ P := hK0.trans hKB
    have e1 : sieveBudgetQ P * (P.T / Real.pi * (CM * P.LB ^ 2))
        = (sieveBudgetQ P * (P.T / (2 * Real.pi) * P.LL)) * (2 * CM * P.LB ^ 2 / P.LL) := by
      field_simp
    have hLB2 : P.LB ^ 2 ≤ 16 / 9 * (P.aQ * P.LB) ^ 2 := by
      have : (3 / 4) ^ 2 ≤ P.aQ ^ 2 := pow_le_pow_left₀ (by norm_num) ha 2
      have h0 : 0 ≤ P.LB ^ 2 := sq_nonneg _
      calc P.LB ^ 2 = 16 / 9 * ((3 / 4) ^ 2 * P.LB ^ 2) := by ring
        _ ≤ 16 / 9 * (P.aQ ^ 2 * P.LB ^ 2) := by
            apply mul_le_mul_of_nonneg_left _ (by norm_num)
            exact mul_le_mul_of_nonneg_right this h0
        _ = 16 / 9 * (P.aQ * P.LB) ^ 2 := by ring
    have hq : 2 * CM * P.LB ^ 2 / P.LL ≤ 32 / 9 * CM * (P.aQ * P.LB) ^ 2 / P.LL := by
      apply div_le_div_of_nonneg_right _ hLL0.le
      have := mul_le_mul_of_nonneg_left hLB2 (by positivity : 0 ≤ 2 * CM)
      linarith only [this]
    have h3 : (sieveBudgetQ P * (P.T / (2 * Real.pi) * P.LL)) * (2 * CM * P.LB ^ 2 / P.LL)
        ≤ ((1 + δ) ^ 2 * Family.qle.Cconst * NfamQ P Family.qle Qn)
            * (32 / 9 * CM * (P.aQ * P.LB) ^ 2 / P.LL) :=
      mul_le_mul hBX hq (by positivity) (mul_nonneg (mul_nonneg (by positivity) hC.le) hN0)
    have h4 : (1 + δ) ^ 2 ≤ 4 := by linarith only [hδδ, hδ1]
    have h5 : 128 / 9 * Family.qle.Cconst * CM / P.LL ≤ δ := by
      rw [div_le_iff₀ hLL0]
      rw [div_le_iff₀ (by positivity)] at hLL128
      linarith only [hLL128]
    have h6 : ((1 + δ) ^ 2 * Family.qle.Cconst * NfamQ P Family.qle Qn)
          * (32 / 9 * CM * (P.aQ * P.LB) ^ 2 / P.LL)
        = (1 + δ) ^ 2 * (32 / 9 * Family.qle.Cconst * CM / P.LL)
            * ((P.aQ * P.LB) ^ 2 * NfamQ P Family.qle Qn) := by
      field_simp
    have hWN0 : 0 ≤ (P.aQ * P.LB) ^ 2 * NfamQ P Family.qle Qn := by positivity
    have h7 : (1 + δ) ^ 2 * (32 / 9 * Family.qle.Cconst * CM / P.LL)
          * ((P.aQ * P.LB) ^ 2 * NfamQ P Family.qle Qn)
        ≤ 4 * (32 / 9 * Family.qle.Cconst * CM / P.LL) * ((P.aQ * P.LB) ^ 2 * NfamQ P Family.qle Qn) := by
      have h0 : 0 ≤ (32 / 9 * Family.qle.Cconst * CM / P.LL) * ((P.aQ * P.LB) ^ 2 * NfamQ P Family.qle Qn) := by
        positivity
      have := mul_le_mul_of_nonneg_right h4 h0
      linarith only [this]
    have h8 : 4 * (32 / 9 * Family.qle.Cconst * CM / P.LL) * ((P.aQ * P.LB) ^ 2 * NfamQ P Family.qle Qn)
        ≤ δ * (P.aQ * P.LB) ^ 2 * NfamQ P Family.qle Qn := by
      have e : 4 * (32 / 9 * Family.qle.Cconst * CM / P.LL) = 128 / 9 * Family.qle.Cconst * CM / P.LL := by ring
      rw [e]
      have := mul_le_mul_of_nonneg_right h5 hWN0
      linarith only [this]
    calc sieveBudgetQ P * (P.T / Real.pi * (CM * P.LB ^ 2))
        = (sieveBudgetQ P * (P.T / (2 * Real.pi) * P.LL)) * (2 * CM * P.LB ^ 2 / P.LL) := e1
      _ ≤ ((1 + δ) ^ 2 * Family.qle.Cconst * NfamQ P Family.qle Qn)
            * (32 / 9 * CM * (P.aQ * P.LB) ^ 2 / P.LL) := h3
      _ = (1 + δ) ^ 2 * (32 / 9 * Family.qle.Cconst * CM / P.LL)
            * ((P.aQ * P.LB) ^ 2 * NfamQ P Family.qle Qn) := h6
      _ ≤ 4 * (32 / 9 * Family.qle.Cconst * CM / P.LL) * ((P.aQ * P.LB) ^ 2 * NfamQ P Family.qle Qn) := h7
      _ ≤ δ * (P.aQ * P.LB) ^ 2 * NfamQ P Family.qle Qn := h8
  -- ── (10) assemble
  have hPz0 : 0 ≤ zoneP P := le_trans (mul_nonneg hM0 (by linarith)) hP1
  have hk02 : FrobAssembly.K0a (zoneFactor P) (vDesign P) ≤ 2 := by linarith [hk, hk1, hk2]
  unfold inCrossRHS
  exact inzone_arith (ρ := rhoU P Set.univ) (X := P.T / (2 * Real.pi) * P.LL)
    (k := K0 (vDesign P) + K1 (vDesign P)) hNρ hρ0 hρδ hD0 hDle hBE hE0 hPz0 hP2 hR hM hM0
    hδ0 le_rfl hδ1 hK0 hKB hBX hKX hk0 hk02 (FrobAssembly.K0_add_K1_nonneg hadm) hk2 hC hW0 hN0 hX0 hδε

end F1c
end ShellK
end ZetaShell
