/-
F1c-4a, part 1 (L7_3, round 4): ZetaQ's `A1_eventually` (Row 8 main term) and `A2_eventually` (Row 8 error) along the
Shell design. GENERATED by `py/gen_rows8.py` from `ZetaQ/FrobAssembly.lean` (green tree) by mechanical substitution:
the design predicate; `design_regime` -> A7 `shellDesign_regime` (same conjuncts, same order); `design_basic` ->
`design_basic_shell`; `NfamQ_crude_eventually` -> `NfamQ_crude_shell`; `cWinDesign F` -> C1's `cWinShell S53L75`;
`F` -> `Family.qle` (A1's non-full branch dropped: `Family.isFull_qle`). No bandwidth fact is read beyond `1 ≤ λ`.
-/
import ZetaShell.Skeleton.LF_AsmBase

noncomputable section
open MeasureTheory Set Real Filter

namespace ZetaShell
namespace ShellK
namespace F1c

open ZetaQ ZetaQ.Payoff ZetaQ.Zones ZetaQ.FrobAssembly Zeta23.PrimeSide Zeta23.ThmE ZetaQ.Ends ZetaQ.FamRows

set_option maxHeartbeats 4000000 in
theorem A1_shell (r ε : ℝ) (hr : 3 ≤ r) (hε : 0 < ε) (ε' : ℝ) (hε' : 0 < ε') :
    ∀ᶠ Qn : ℕ in atTop, ∀ P : ParamsQ, Design.ShellDesignM S53L75 r ε (Qn : ℝ) P →
      (P.aQ ^ 2 * P.LB ^ 2)⁻¹ * MAIN8chars Family.qle P Qn ≤ (psi (vDesign P) 0 + ε' / 8) * NfamQ P Family.qle Qn := by
  have hS2 : ((S53L75.lam : ℚ) : ℝ) ≤ 191 / 100 := by norm_num [S53L75]
  have hF : Family.qle.IsFull := Family.isFull_qle
  obtain ⟨A, T₀, hA, hrvm⟩ := EFChi.rvmChi_main_uniform
  have hre : (0:ℝ) < r + ε := by linarith
  have hTtop : Tendsto (fun n : ℕ => Twin (n : ℝ) r ε) atTop atTop :=
    (tendsto_rpow_atTop hre).comp tendsto_log_nat_atTop
  have hC := Cconst_pos Family.qle
  set K : ℝ := max 1 (max (12 / ε') (max (96 * Real.pi * A * Family.qle.Cconst / ε') 500)) with hKdef
  have hK1 : 1 ≤ K := le_max_left _ _
  filter_upwards [Design.shellDesign_regime S53L75 hS2 r ε hr hε K hK1, design_basic_shell r ε hr hε,
    NfamQ_crude_shell r ε hr hε, hTtop.eventually_ge_atTop T₀] with Qn hreg hbas hcrude hT0
  intro P hdes
  have hP := hdes.1
  have hQ := (hdes.2.1 : P.Q = (Qn : ℝ))
  have hT := (show P.T = Real.log (Qn : ℝ) ^ (r + ε) by rw [hdes.2.2.1]; rfl)
  obtain ⟨hlogK, hTK, -, -, hszK, -, -, hlog3⟩ := hreg P hdes
  obtain ⟨hLL30, hL8, hlam, hw, hQn2⟩ := hbas P hdes
  have hN := hcrude P hdes
  have hQn1 : 1 ≤ Qn := by omega
  have hTpos : 0 < P.T := hP.T_pos
  have hLL0 : 0 < P.LL := by linarith
  have hpi := Real.pi_pos
  have ha0 := hP.aQ_pos
  have hL0 := hP.LB_pos
  have hlogQ : Real.log Qn ≤ P.LL := (log_Qn_le_LL hP hQn1 hQ).1
  have hlogQ0 : 0 ≤ Real.log (Qn:ℝ) := Real.log_natCast_nonneg Qn
  have hK12 : 12 / ε' ≤ K := le_trans (le_max_left _ _) (le_max_right _ _)
  have hKA : 96 * Real.pi * A * Family.qle.Cconst / ε' ≤ K :=
    le_trans (le_trans (le_max_left _ _) (le_max_right _ _)) (le_max_right _ _)
  have hK500 : (500:ℝ) ≤ K := le_trans (le_trans (le_max_right _ _) (le_max_right _ _)) (le_max_right _ _)
  have hLL12 : 12 / ε' ≤ P.LL := hK12.trans (hlogK.trans hlogQ)
  have hTA : 96 * Real.pi * A * Family.qle.Cconst / ε' ≤ P.T := hKA.trans hTK
  have hsz500 : 500 * (1 + Real.log Qn) ^ 2 ≤ Qn := by
    have h := hszK
    have hsq : 0 ≤ (1 + Real.log Qn) ^ 2 := sq_nonneg _
    nlinarith
  have hS := sizeR_le_point Family.qle Qn hQn1 hsz500
  have hS0 : 0 ≤ Family.qle.sizeR Qn := by unfold Family.sizeR; positivity
  have hψ := psi0_le hP hw hlam
  have hψ0 := psi0_nonneg hP
  have hE := famEll1Sq_le hP Family.qle Qn hQ
  have hell := famEll1_le P hF Qn hQn2 hA.le hrvm (by rw [hT]; exact hT0) hTpos
  have hfam0 := famEll1_nonneg hP Family.qle Qn
  have hM8 : (P.aQ ^ 2 * P.LB ^ 2)⁻¹ * MAIN8chars Family.qle P Qn
      = psi (vDesign P) 0 * (P.T / (2 * Real.pi)) * (famEll1Sq Family.qle P Qn / P.LL) := by
    rw [MAIN8chars_eq_of_isFull hF, MAIN8_eq_psi P hP Family.qle Qn]; field_simp
  rw [hM8]
  have hlog2 := Real.log_two_lt_d9
  have hc : 2 * Real.log 2 - 1 ≤ 0.3863 := by linarith
  have hE' : famEll1Sq Family.qle P Qn / P.LL ≤ (1 + 0.3863 / P.LL) * famEll1 Family.qle P Qn := by
    rw [div_le_iff₀ hLL0]
    have h1 : (P.LL + (2 * Real.log 2 - 1)) * famEll1 Family.qle P Qn ≤ (P.LL + 0.3863) * famEll1 Family.qle P Qn :=
      mul_le_mul_of_nonneg_right (by linarith) hfam0
    have e : (1 + 0.3863 / P.LL) * famEll1 Family.qle P Qn * P.LL = (P.LL + 0.3863) * famEll1 Family.qle P Qn := by
      field_simp
    rw [e]; linarith
  have hrat : 0.3863 / P.LL ≤ 0.033 * ε' := by
    rw [div_le_iff₀ hLL0]
    have := hLL12; rw [div_le_iff₀ hε'] at this
    nlinarith
  have h14 : 1 + 0.3863 / P.LL ≤ 1.4 := by
    have : 0.3863 / P.LL ≤ 0.4 := by rw [div_le_iff₀ hLL0]; linarith
    linarith
  have h14' : 0 ≤ 1 + 0.3863 / P.LL := by positivity
  have hmain : psi (vDesign P) 0 * (P.T / (2 * Real.pi)) * (famEll1Sq Family.qle P Qn / P.LL)
      ≤ psi (vDesign P) 0 * (1 + 0.3863 / P.LL)
          * (NfamQ P Family.qle Qn + Family.qle.sizeR Qn * (A * Real.log ((Qn : ℝ) * (P.T + 2)))) := by
    calc psi (vDesign P) 0 * (P.T / (2 * Real.pi)) * (famEll1Sq Family.qle P Qn / P.LL)
        ≤ psi (vDesign P) 0 * (P.T / (2 * Real.pi)) * ((1 + 0.3863 / P.LL) * famEll1 Family.qle P Qn) := by
          gcongr
      _ = psi (vDesign P) 0 * (1 + 0.3863 / P.LL) * ((P.T / (2 * Real.pi)) * famEll1 Family.qle P Qn) := by ring
      _ ≤ _ := by gcongr
  have hN0 : 0 ≤ NfamQ P Family.qle Qn := NfamQ_nonneg P Family.qle Qn
  have hsmall1 : psi (vDesign P) 0 * (0.3863 / P.LL) * NfamQ P Family.qle Qn ≤ ε' / 16 * NfamQ P Family.qle Qn := by
    apply mul_le_mul_of_nonneg_right _ hN0
    calc psi (vDesign P) 0 * (0.3863 / P.LL) ≤ (16 / 9) * (0.033 * ε') :=
          mul_le_mul hψ hrat (by positivity) (by norm_num)
      _ ≤ ε' / 16 := by linarith
  have hsmall2 : psi (vDesign P) 0 * (1 + 0.3863 / P.LL)
        * (Family.qle.sizeR Qn * (A * Real.log ((Qn : ℝ) * (P.T + 2)))) ≤ ε' / 16 * NfamQ P Family.qle Qn := by
    have h1 : psi (vDesign P) 0 * (1 + 0.3863 / P.LL) ≤ 2.5 := by
      calc psi (vDesign P) 0 * (1 + 0.3863 / P.LL) ≤ (16 / 9) * 1.4 :=
            mul_le_mul hψ h14 h14' (by norm_num)
        _ ≤ 2.5 := by norm_num
    have hlogQT0 : 0 ≤ Real.log ((Qn : ℝ) * (P.T + 2)) := by
      apply Real.log_nonneg
      have : (1:ℝ) ≤ Qn := by exact_mod_cast hQn1
      nlinarith
    have hAlog0 : 0 ≤ A * Real.log ((Qn : ℝ) * (P.T + 2)) := mul_nonneg hA.le hlogQT0
    have h2 : Family.qle.sizeR Qn * (A * Real.log ((Qn : ℝ) * (P.T + 2)))
        ≤ 0.2 * (Qn:ℝ) ^ 2 * (A * (3 * P.LL)) := by
      apply mul_le_mul hS _ hAlog0 (by positivity)
      apply mul_le_mul_of_nonneg_left _ hA.le
      linarith
    have key : 96 * Real.pi * A * Family.qle.Cconst ≤ ε' * P.T := by
      rw [div_le_iff₀ hε'] at hTA; linarith
    have h3 : 2.5 * (0.2 * (Qn:ℝ) ^ 2 * (A * (3 * P.LL)))
        ≤ ε' / 16 * ((Qn : ℝ) ^ 2 * P.T * P.LL / (4 * Real.pi * Family.qle.Cconst)) := by
      rw [show 2.5 * (0.2 * (Qn:ℝ) ^ 2 * (A * (3 * P.LL)))
          = (96 * Real.pi * A * Family.qle.Cconst) * ((Qn:ℝ) ^ 2 * P.LL) / (64 * Real.pi * Family.qle.Cconst) by
            first | (field_simp; ring) | field_simp,
        show ε' / 16 * ((Qn : ℝ) ^ 2 * P.T * P.LL / (4 * Real.pi * Family.qle.Cconst))
          = (ε' * P.T) * ((Qn:ℝ) ^ 2 * P.LL) / (64 * Real.pi * Family.qle.Cconst) by ring]
      gcongr
    calc psi (vDesign P) 0 * (1 + 0.3863 / P.LL) * (Family.qle.sizeR Qn * (A * Real.log ((Qn : ℝ) * (P.T + 2))))
        ≤ 2.5 * (0.2 * (Qn:ℝ) ^ 2 * (A * (3 * P.LL))) :=
          mul_le_mul h1 h2 (mul_nonneg hS0 hAlog0) (by norm_num)
      _ ≤ ε' / 16 * ((Qn : ℝ) ^ 2 * P.T * P.LL / (4 * Real.pi * Family.qle.Cconst)) := h3
      _ ≤ ε' / 16 * NfamQ P Family.qle Qn := by gcongr
  have hfinal : psi (vDesign P) 0 * (1 + 0.3863 / P.LL)
        * (NfamQ P Family.qle Qn + Family.qle.sizeR Qn * (A * Real.log ((Qn : ℝ) * (P.T + 2))))
      = psi (vDesign P) 0 * NfamQ P Family.qle Qn + psi (vDesign P) 0 * (0.3863 / P.LL) * NfamQ P Family.qle Qn
        + psi (vDesign P) 0 * (1 + 0.3863 / P.LL)
            * (Family.qle.sizeR Qn * (A * Real.log ((Qn : ℝ) * (P.T + 2)))) := by ring
  linarith [hmain, hfinal, hsmall1, hsmall2]

set_option maxHeartbeats 4000000 in
theorem A2_shell (r ε : ℝ) (hr : 3 ≤ r) (hε : 0 < ε) (ε' : ℝ) (hε' : 0 < ε') :
    ∀ᶠ Qn : ℕ in atTop, ∀ P : ParamsQ, Design.ShellDesignM S53L75 r ε (Qn : ℝ) P →
      (P.aQ ^ 2 * P.LB ^ 2)⁻¹ * (Family.qle.sizeR Qn * err8 P Qn) ≤ ε' / 8 * NfamQ P Family.qle Qn := by
  have hS2 : ((S53L75.lam : ℚ) : ℝ) ≤ 191 / 100 := by norm_num [S53L75]
  have hC := Cconst_pos Family.qle
  set Kc : ℝ := Kerr (Design.cWinShell S53L75) with hKc
  set K : ℝ := max 1 (max (0.51 * Family.qle.Cconst / ε') (max (72 * Kc * Family.qle.Cconst / ε') 500)) with hKdef
  have hK1 : 1 ≤ K := le_max_left _ _
  filter_upwards [Design.shellDesign_regime S53L75 hS2 r ε hr hε K hK1, design_basic_shell r ε hr hε,
    NfamQ_crude_shell r ε hr hε] with Qn hreg hbas hcrude
  intro P hdes
  have hP := hdes.1
  have hQ := (hdes.2.1 : P.Q = (Qn : ℝ))
  obtain ⟨hlogK, hTK, -, -, hszK, -, -, -⟩ := hreg P hdes
  obtain ⟨hLL30, hL8, hlam, hw, hQn2⟩ := hbas P hdes
  have hN := hcrude P hdes
  have hQn1 : 1 ≤ Qn := by omega
  have hTpos : 0 < P.T := hP.T_pos
  have hLL0 : 0 < P.LL := by linarith
  have hpi := Real.pi_pos
  have hpi4 : Real.pi ≤ 3.1416 := Real.pi_lt_d4.le
  have ha0 := hP.aQ_pos
  have ha := hP.a_ge
  have hL0 := hP.LB_pos
  have hlogQ : Real.log Qn ≤ P.LL := (log_Qn_le_LL hP hQn1 hQ).1
  have hcW : P.cWin = Design.cWinShell S53L75 := Design.cWin_of_shellDesignM hdes
  have hc0 : 0 ≤ Design.cWinShell S53L75 := by rw [← hcW]; exact hP.cWin_pos.le
  have hKc0 : 0 ≤ Kc := Kerr_nonneg hc0
  have hK1' : 0.51 * Family.qle.Cconst / ε' ≤ K := le_trans (le_max_left _ _) (le_max_right _ _)
  have hK2' : 72 * Kc * Family.qle.Cconst / ε' ≤ K :=
    le_trans (le_trans (le_max_left _ _) (le_max_right _ _)) (le_max_right _ _)
  have hK500 : (500:ℝ) ≤ K := le_trans (le_trans (le_max_right _ _) (le_max_right _ _)) (le_max_right _ _)
  have hLL1 : 0.51 * Family.qle.Cconst ≤ ε' * P.LL := by
    have := hK1'.trans (hlogK.trans hlogQ); rw [div_le_iff₀ hε'] at this; linarith
  have hT2 : 72 * Kc * Family.qle.Cconst ≤ ε' * P.T := by
    have := hK2'.trans hTK; rw [div_le_iff₀ hε'] at this; linarith
  have hsz500 : 500 * (1 + Real.log Qn) ^ 2 ≤ Qn := by
    have h := hszK
    have hsq : 0 ≤ (1 + Real.log Qn) ^ 2 := sq_nonneg _
    nlinarith
  have hS := sizeR_le_point Family.qle Qn hQn1 hsz500
  have hS0 : 0 ≤ Family.qle.sizeR Qn := by unfold Family.sizeR; positivity
  have herr := err8_le hP hw Qn hQ hQn1 (by linarith) hL8
  rw [hcW] at herr
  have herr0 : 0 ≤ err8 P Qn := by
    unfold err8 Cm8 Aq Kinc
    have h1' : 0 ≤ 1 - 2 * Real.log 2 ^ 2 := one_sub_two_logsq_nonneg
    have hl0 := l_nonneg hP
    have hlogQ0 : 0 ≤ Real.log (Qn:ℝ) := Real.log_natCast_nonneg Qn
    have hℓ0 := ell1q_nonneg (T_ge_two_pi hP) hQn1
    have hb0 := hP.bQ_pos.le
    have hw1 := hP.one_le_w
    have hlogf : 0 ≤ Real.log (P.cWin * P.LB / (4 * P.w)) := by
      apply Real.log_nonneg
      rw [le_div_iff₀ (by positivity)]
      have hc4 := hP.four_le_cWin
      nlinarith
    positivity
  -- `(a²L²)⁻¹ ≤ (16/9)/(L·ℒ)`
  have hinv : (P.aQ ^ 2 * P.LB ^ 2)⁻¹ ≤ (16 / 9) / (P.LB * P.LL) := by
    have hLLle : P.LL ≤ P.LB := LL_le_LB hP hlam
    have h1 : (9 / 16) * (P.LB * P.LL) ≤ P.aQ ^ 2 * P.LB ^ 2 := by
      have ha2 : (9 / 16 : ℝ) ≤ P.aQ ^ 2 := by nlinarith
      have hL2 : P.LB * P.LL ≤ P.LB ^ 2 := by nlinarith
      calc (9 / 16) * (P.LB * P.LL) ≤ P.aQ ^ 2 * (P.LB * P.LL) :=
            mul_le_mul_of_nonneg_right ha2 (by positivity)
        _ ≤ P.aQ ^ 2 * P.LB ^ 2 := mul_le_mul_of_nonneg_left hL2 (by positivity)
    calc (P.aQ ^ 2 * P.LB ^ 2)⁻¹ ≤ ((9 / 16) * (P.LB * P.LL))⁻¹ :=
          inv_anti₀ (by positivity) h1
      _ = (16 / 9) / (P.LB * P.LL) := by field_simp
  have hmain : (P.aQ ^ 2 * P.LB ^ 2)⁻¹ * (Family.qle.sizeR Qn * err8 P Qn)
      ≤ (16 / 9) / (P.LB * P.LL)
          * (0.2 * (Qn : ℝ) ^ 2 * (0.0071 * P.LB * P.T + Kc * P.LB * P.LL ^ 2)) := by
    apply mul_le_mul hinv (mul_le_mul hS herr herr0 (by positivity)) (by positivity) (by positivity)
  have hsimp : (16 / 9) / (P.LB * P.LL)
        * (0.2 * (Qn : ℝ) ^ 2 * (0.0071 * P.LB * P.T + Kc * P.LB * P.LL ^ 2))
      = (16 / 9 * 0.2 * 0.0071) * ((Qn : ℝ) ^ 2 * P.T / P.LL)
        + (16 / 9 * 0.2 * Kc) * ((Qn : ℝ) ^ 2 * P.LL) := by
    first | (field_simp; ring) | field_simp
  rw [hsimp] at hmain
  have hpc1 : (16 / 9 * 0.2 * 0.0071) * ((Qn : ℝ) ^ 2 * P.T / P.LL)
      ≤ ε' / 16 * ((Qn : ℝ) ^ 2 * P.T * P.LL / (4 * Real.pi * Family.qle.Cconst)) := by
    have key : (16 / 9 * 0.2 * 0.0071) * (64 * Real.pi * Family.qle.Cconst) ≤ ε' * P.LL ^ 2 := by
      have h1 : (16 / 9 * 0.2 * 0.0071) * (64 * Real.pi * Family.qle.Cconst) ≤ 0.51 * Family.qle.Cconst := by
        have := mul_le_mul_of_nonneg_right hpi4 hC.le
        linarith
      have hLL2 : P.LL ≤ P.LL ^ 2 := by nlinarith
      nlinarith [mul_le_mul_of_nonneg_left hLL2 hε'.le]
    rw [show (16 / 9 * 0.2 * 0.0071) * ((Qn : ℝ) ^ 2 * P.T / P.LL)
        = ((16 / 9 * 0.2 * 0.0071) * (64 * Real.pi * Family.qle.Cconst)) * ((Qn : ℝ) ^ 2 * P.T * P.LL)
          / (64 * Real.pi * Family.qle.Cconst * P.LL ^ 2) by first | (field_simp; ring) | field_simp,
      show ε' / 16 * ((Qn : ℝ) ^ 2 * P.T * P.LL / (4 * Real.pi * Family.qle.Cconst))
        = (ε' * P.LL ^ 2) * ((Qn : ℝ) ^ 2 * P.T * P.LL) / (64 * Real.pi * Family.qle.Cconst * P.LL ^ 2) by
          first | (field_simp; ring) | field_simp]
    gcongr
  have hpc2 : (16 / 9 * 0.2 * Kc) * ((Qn : ℝ) ^ 2 * P.LL)
      ≤ ε' / 16 * ((Qn : ℝ) ^ 2 * P.T * P.LL / (4 * Real.pi * Family.qle.Cconst)) := by
    have key : (16 / 9 * 0.2 * Kc) * (64 * Real.pi * Family.qle.Cconst) ≤ ε' * P.T := by
      have h1 : (16 / 9 * 0.2 * Kc) * (64 * Real.pi * Family.qle.Cconst) ≤ 72 * Kc * Family.qle.Cconst := by
        have h0 : 0 ≤ Kc * Family.qle.Cconst := mul_nonneg hKc0 hC.le
        have hpc : Kc * (Real.pi * Family.qle.Cconst) ≤ Kc * (3.1416 * Family.qle.Cconst) :=
          mul_le_mul_of_nonneg_left (mul_le_mul_of_nonneg_right hpi4 hC.le) hKc0
        calc (16 / 9 * 0.2 * Kc) * (64 * Real.pi * Family.qle.Cconst)
            = (16 / 9 * 0.2 * 64) * (Kc * (Real.pi * Family.qle.Cconst)) := by ring
          _ ≤ (16 / 9 * 0.2 * 64) * (Kc * (3.1416 * Family.qle.Cconst)) := by gcongr
          _ = (16 / 9 * 0.2 * 64 * 3.1416) * (Kc * Family.qle.Cconst) := by ring
          _ ≤ 72 * (Kc * Family.qle.Cconst) := by gcongr; norm_num
          _ = 72 * Kc * Family.qle.Cconst := by ring
      linarith
    rw [show (16 / 9 * 0.2 * Kc) * ((Qn : ℝ) ^ 2 * P.LL)
        = ((16 / 9 * 0.2 * Kc) * (64 * Real.pi * Family.qle.Cconst)) * ((Qn : ℝ) ^ 2 * P.LL)
          / (64 * Real.pi * Family.qle.Cconst) by first | (field_simp; ring) | field_simp,
      show ε' / 16 * ((Qn : ℝ) ^ 2 * P.T * P.LL / (4 * Real.pi * Family.qle.Cconst))
        = (ε' * P.T) * ((Qn : ℝ) ^ 2 * P.LL) / (64 * Real.pi * Family.qle.Cconst) by ring]
    gcongr
  have hN0 : 0 ≤ NfamQ P Family.qle Qn := NfamQ_nonneg P Family.qle Qn
  calc (P.aQ ^ 2 * P.LB ^ 2)⁻¹ * (Family.qle.sizeR Qn * err8 P Qn)
      ≤ (16 / 9 * 0.2 * 0.0071) * ((Qn : ℝ) ^ 2 * P.T / P.LL)
        + (16 / 9 * 0.2 * Kc) * ((Qn : ℝ) ^ 2 * P.LL) := hmain
    _ ≤ ε' / 16 * ((Qn : ℝ) ^ 2 * P.T * P.LL / (4 * Real.pi * Family.qle.Cconst))
        + ε' / 16 * ((Qn : ℝ) ^ 2 * P.T * P.LL / (4 * Real.pi * Family.qle.Cconst)) := add_le_add hpc1 hpc2
    _ = ε' / 8 * ((Qn : ℝ) ^ 2 * P.T * P.LL / (4 * Real.pi * Family.qle.Cconst)) := by ring
    _ ≤ ε' / 8 * NfamQ P Family.qle Qn := by gcongr

end F1c
end ShellK
end ZetaShell
