"""Generate the full K = 5 all-marks replay (L1_1d).

  python gen_replay.py [CLASS ...]        (default: all 20 classes)

Per class c (directory replay/<c>/, every declaration in namespace ZetaS.CertV2.R<c>):
  R<c>_Data.lean, R<c>_Pts<k>.lean (<= 400 records), R<c>_Cells.lean, R<c>_Leaves<k>.lean (40 leaf theorems each),
  R<c>_Assembly.lean (node theorems up to `T0_ok : Node.check D_R<c> T0 root = true`),
  R<c>_Cert.lean (`cert : Cert := ⟨classData m, root, T0⟩`, `cert_ok : Cert.check cert = true`).
Common: replay/common/ReplayCommon.lean (LIQ.ext', rootOK, Cert.check_of_parts),
        replay/common/ReplayAM5.lean (`certAM5_replayed : CertAM5` via `ChainV3.certAM5_of_checks`).
"""
import os, sys, json, subprocess
HERE = os.path.dirname(os.path.abspath(__file__)); L11 = HERE
CLASSES = ['11111', '11112', '11121', '11122', '11211', '11212', '11221', '11222', '12112', '12121', '12122',
           '12212', '12221', '12222', '21112', '21122', '21212', '21222', '22122', '22222']
CERTS_ONLY = '--certs-only' in sys.argv
todo = [a for a in sys.argv[1:] if not a.startswith('--')] or CLASSES
HDR = 'set_option maxRecDepth 100000\nset_option maxHeartbeats 0\n\n'

def marks(c): return '[' + ','.join(c) + ']'

for c in todo:
    out = os.path.join(HERE, c); os.makedirs(out, exist_ok=True)
    env = dict(os.environ, OUTDIR=out, NSWRAP='1', LEAFFILE='40', PYTHONIOENCODING='utf-8')
    if not CERTS_ONLY:
      r = subprocess.run([sys.executable, 'gen_v2_lean.py', c, 'all', '0', f'R{c}', '--leaves-per-shard', '10000000'],
                       cwd=L11, env=env, capture_output=True, text=True, encoding='utf-8')
      print(r.stdout.strip()[:160], r.stderr.strip()[-300:])
      if r.returncode != 0:   # (Oct 2026) a failed generator run is an error, not a skipped class
          sys.exit(f'gen_v2_lean.py failed for class {c} (exit status {r.returncode})')
    js = json.load(open(os.path.join(L11, f'v2_K5_{c}.json')))
    root = '[' + ','.join(f'(({a} : ℚ),({b} : ℚ))' for a, b in js['root']) + ']'
    open(os.path.join(out, f'R{c}_Cert.lean'), 'w', encoding='utf-8').write(f'''/- replay: the class certificate {c} (L1_1d, generated by gen_replay.py). -/
import ReplayCommon
import R{c}_Assembly
import ZetaS.Cert.ChainV3

{HDR}namespace ZetaS.CertV2
namespace R{c}

/-- the certificate of class {c}: the specification's instance, the root box, the tree of the shards. -/
def cert : Cert := ⟨classData {marks(c)}, {root}, T0⟩

/-- the literal instance of the shards is the specification's `classData`. -/
theorem data_eq : classData {marks(c)} = D_R{c} :=
  LIQ.ext' (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide +kernel)

theorem cert_ok : Cert.check cert = true := by
  apply Cert.check_of_parts
  · decide +kernel
  · show Node.check (classData {marks(c)}) T0 {root} = true
    rw [data_eq]
    exact T0_ok

/-- the local inequality of class {c} on the whole orthant (soundness chain `ChainV3`, L5_2). -/
theorem holds : (classData {marks(c)}).Holds := ChainV3.cert_check_sound cert cert_ok

end R{c}
end ZetaS.CertV2
''')

com = os.path.join(HERE, 'common'); os.makedirs(com, exist_ok=True)
open(os.path.join(com, 'ReplayCommon.lean'), 'w', encoding='utf-8').write(f'''/- replay: common lemmas (L1_1d/e). Library modules only (green: ZetaS.Cert.*). -/
import ZetaS.Cert.CertSpecAM5

{HDR}namespace ZetaS.CertV2

theorem LIQ.ext' {{a b : LIQ}} (h0 : a.d = b.d) (h1 : a.spans = b.spans) (h2 : a.mu = b.mu)
    (h3 : a.claim = b.claim) : a = b := by
  cases a; cases b; simp_all

/-- the root conditions of `Cert.check` (everything except the tree). -/
def rootOK (C : Cert) : Bool :=
  C.data.wf && decide (C.root.length = C.data.d) &&
    (List.range C.data.d).all (fun l => decide ((C.root.getD l (0, 0)).1 = 0) &&
      decide (C.data.claim ≤ C.data.mu.getD l 0 * (C.root.getD l (0, 0)).2))

theorem Cert.check_of_parts (C : Cert) (h1 : rootOK C = true) (h2 : C.tree.check C.data C.root = true) :
    C.check = true := by
  show (rootOK C && C.tree.check C.data C.root) = true
  rw [h1, h2]; rfl

end ZetaS.CertV2
''')
chk = 'fun _ h => by simp at h'
for c in reversed(CLASSES):
    chk = f'List.forall_mem_cons.mpr ⟨R{c}.cert_ok, {chk}⟩'
open(os.path.join(com, 'ReplayAM5.lean'), 'w', encoding='utf-8').write(
    '/- replay: the K = 5 all-marks certificate, all 20 classes (L1_1d). Applies `ZetaS.CertV2.ChainV3.certAM5_of_checks` (library module ZetaS.Cert.ChainV3), the level-A\n'
    '   soundness chain of L5_2 (v3chain/ChainV3.lean); hdata holds by `rfl` (each cert has data `classData m`). -/\n'
    + 'import ZetaS.Cert.ChainV3\n' + ''.join(f'import R{c}_Cert\n' for c in CLASSES) + f'''
{HDR}namespace ZetaS.CertV2

theorem certAM5_replayed : ZetaS.CertAM5 :=
  ChainV3.certAM5_of_checks [{', '.join(f'R{c}.cert' for c in CLASSES)}] rfl
    ({chk})

end ZetaS.CertV2
''')
print('done', todo)

# ---- L1_1e: the two hypothesis-free headline theorems (compiled tonight after ReplayAM5)
open(os.path.join(com, 'ReplayHeadlines.lean'), 'w', encoding='utf-8').write('''/- replay: the two hypothesis-free K = 5 theorems (L1_1e). `ZetaS.Top.zeta_simple_K5_final` and
`zeta_distinct_K5_final` (library, ZetaS.Top.TopFinal) applied to `certAM5_replayed : ZetaS.CertAM5`; the statements are
those of the two headlines without the hypothesis `hcert`. -/
import ReplayAM5
import ZetaS.Top.TopFinal

namespace ZetaS
namespace Top

/-- **Simple zeros, K = 5, hypothesis-free** (thm:sigd-Sigma with the K = 5 certificate). -/
theorem zeta_simple_K5_uncond :
    ∀ ε > 0, ∃ T₀ : ℝ, ∀ T ≥ T₀,
      ((675158622 : ℝ) / 10 ^ 9 - ε) * (Ncount T (2 * T) : ℝ) ≤ Nsimple T (2 * T) :=
  zeta_simple_K5_final ZetaS.CertV2.certAM5_replayed

/-- **Distinct zeros, K = 5, hypothesis-free** (thm:sigd-D with the K = 5 certificate). -/
theorem zeta_distinct_K5_uncond :
    ∀ ε > 0, ∃ T₀ : ℝ, ∀ T ≥ T₀,
      ((837579311 : ℝ) / 10 ^ 9 - ε) * (Ncount T (2 * T) : ℝ) ≤ Ndist T (2 * T) :=
  zeta_distinct_K5_final ZetaS.CertV2.certAM5_replayed

end Top
end ZetaS
''')
print('headlines written')
