/-
L7_5 (28 Sep 2026), node R5 for S53L75: the analytic L75 side conditions.
Certificate for `-q'(s) > 0` on `(0,1)` (`q = pR d`, `s = (2t/λ)²`): the Bernstein form of degree 5
(`no elevation`), with every coefficient a positive rational
(generated by `py/bern_L7_5.py`, exact Fractions); the identity `-q' = bernS53 s (1-s)` is checked by `ring`,
positivity of each term by `positivity`. Moments: the kernel facts `CertQ.a_S53`, `CertQ.b_S53` (`TR_Q.lean`).
-/
import ZetaShell.Cert.TR_L75
import ZetaShell.Cert.TR_Q

namespace ZetaShell.TR
open ZetaShell.CertQ

noncomputable def bernS53 (s u : ℝ) : ℝ :=
  (109245641 / 315967035 : ℝ) * u ^ 5
    + (159992402518387181 / 57118782199866837 : ℝ) * s * u ^ 4
    + (9309744743904373131553709 / 9507371146877063535567114 : ℝ) * s ^ 2 * u ^ 3
    + (316866387570743671648513705984643 / 4516955273894853970826601489785874 : ℝ) * s ^ 3 * u ^ 2
    + (1048956048095377609939699541140430208361304 / 221613423019947260846323166388220003671495 : ℝ) * s ^ 4 * u
    + (29532861730926500827921437998883859897963701345877 / 10319431480671497420728907552422294741383205061445 : ℝ) * s ^ 5

theorem bernS53_pos (s u : ℝ) (hs : 0 < s) (hu : 0 < u) : 0 < bernS53 s u := by
  unfold bernS53; positivity

theorem negderiv_S53 (s : ℝ) : -pRd S53L75.d s = bernS53 s (1 - s) := by
  simp only [S53L75, pRd, pR_cons, pR_nil, bernS53]; push_cast; ring

theorem strictAnti_S53 : StrictAntiOn (pR S53L75.d) (Set.Icc 0 1) := by
  refine strictAntiOn_of_deriv_neg (convex_Icc 0 1) (continuous_pR _).continuousOn fun x hx => ?_
  rw [interior_Icc] at hx
  rw [(hasDerivAt_pR _ x).deriv]
  have h := negderiv_S53 x
  have hb := bernS53_pos x (1 - x) hx.1 (by linarith [hx.2])
  linarith

theorem S53L75_L75' : S53L75.L75 := by
  have hl : (0 : ℝ) < (S53L75.lam : ℝ) := by norm_num [S53L75]
  refine L75_of_cert S53L75 hl strictAnti_S53 ?_ ?_ a_S53 b_S53
  · simp [S53L75]
  · simp only [S53L75, pR_cons, pR_nil]; push_cast; norm_num

end ZetaShell.TR
