/- L5_2 shard NMajS0: 14 cells, breakpoints 0..8388608 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NMajS0_c0 : majOk 0 2097152 = true := by decide +kernel
theorem NMajS0_c1 : majOk 2097152 4194304 = true := by decide +kernel
theorem NMajS0_c2 : majOk 4194304 5242880 = true := by decide +kernel
theorem NMajS0_c3 : majOk 5242880 6291456 = true := by decide +kernel
theorem NMajS0_c4 : majOk 6291456 6815744 = true := by decide +kernel
theorem NMajS0_c5 : majOk 6815744 7340032 = true := by decide +kernel
theorem NMajS0_c6 : majOk 7340032 7602176 = true := by decide +kernel
theorem NMajS0_c7 : majOk 7602176 7864320 = true := by decide +kernel
theorem NMajS0_c8 : majOk 7864320 7995392 = true := by decide +kernel
theorem NMajS0_c9 : majOk 7995392 8126464 = true := by decide +kernel
theorem NMajS0_c10 : majOk 8126464 8192000 = true := by decide +kernel
theorem NMajS0_c11 : majOk 8192000 8257536 = true := by decide +kernel
theorem NMajS0_c12 : majOk 8257536 8323072 = true := by decide +kernel
theorem NMajS0_c13 : majOk 8323072 8388608 = true := by decide +kernel

theorem NMajS0_ok : majChainOk [0, 2097152, 4194304, 5242880, 6291456, 6815744, 7340032, 7602176, 7864320, 7995392, 8126464, 8192000, 8257536, 8323072, 8388608] = true :=
  majChainOk_cons NMajS0_c0 (majChainOk_cons NMajS0_c1 (majChainOk_cons NMajS0_c2 (majChainOk_cons NMajS0_c3 (majChainOk_cons NMajS0_c4 (majChainOk_cons NMajS0_c5 (majChainOk_cons NMajS0_c6 (majChainOk_cons NMajS0_c7 (majChainOk_cons NMajS0_c8 (majChainOk_cons NMajS0_c9 (majChainOk_cons NMajS0_c10 (majChainOk_cons NMajS0_c11 (majChainOk_cons NMajS0_c12 (majChainOk_cons NMajS0_c13 (majChainOk_single 8388608))))))))))))))

end ZetaS.MajCheck
