/- L5_2 shard NPosS3: 50 cells, breakpoints 168820736..209715200 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS3_c0 : cellOk 168820736 169869312 = true := by decide +kernel
theorem NPosS3_c1 : cellOk 169869312 170917888 = true := by decide +kernel
theorem NPosS3_c2 : cellOk 170917888 171966464 = true := by decide +kernel
theorem NPosS3_c3 : cellOk 171966464 173015040 = true := by decide +kernel
theorem NPosS3_c4 : cellOk 173015040 174063616 = true := by decide +kernel
theorem NPosS3_c5 : cellOk 174063616 174587904 = true := by decide +kernel
theorem NPosS3_c6 : cellOk 174587904 175112192 = true := by decide +kernel
theorem NPosS3_c7 : cellOk 175112192 175636480 = true := by decide +kernel
theorem NPosS3_c8 : cellOk 175636480 176160768 = true := by decide +kernel
theorem NPosS3_c9 : cellOk 176160768 176685056 = true := by decide +kernel
theorem NPosS3_c10 : cellOk 176685056 177209344 = true := by decide +kernel
theorem NPosS3_c11 : cellOk 177209344 177733632 = true := by decide +kernel
theorem NPosS3_c12 : cellOk 177733632 178257920 = true := by decide +kernel
theorem NPosS3_c13 : cellOk 178257920 179306496 = true := by decide +kernel
theorem NPosS3_c14 : cellOk 179306496 180355072 = true := by decide +kernel
theorem NPosS3_c15 : cellOk 180355072 181403648 = true := by decide +kernel
theorem NPosS3_c16 : cellOk 181403648 182452224 = true := by decide +kernel
theorem NPosS3_c17 : cellOk 182452224 183500800 = true := by decide +kernel
theorem NPosS3_c18 : cellOk 183500800 184549376 = true := by decide +kernel
theorem NPosS3_c19 : cellOk 184549376 185597952 = true := by decide +kernel
theorem NPosS3_c20 : cellOk 185597952 186646528 = true := by decide +kernel
theorem NPosS3_c21 : cellOk 186646528 187695104 = true := by decide +kernel
theorem NPosS3_c22 : cellOk 187695104 188743680 = true := by decide +kernel
theorem NPosS3_c23 : cellOk 188743680 189792256 = true := by decide +kernel
theorem NPosS3_c24 : cellOk 189792256 190316544 = true := by decide +kernel
theorem NPosS3_c25 : cellOk 190316544 190840832 = true := by decide +kernel
theorem NPosS3_c26 : cellOk 190840832 191365120 = true := by decide +kernel
theorem NPosS3_c27 : cellOk 191365120 191889408 = true := by decide +kernel
theorem NPosS3_c28 : cellOk 191889408 192413696 = true := by decide +kernel
theorem NPosS3_c29 : cellOk 192413696 192937984 = true := by decide +kernel
theorem NPosS3_c30 : cellOk 192937984 193462272 = true := by decide +kernel
theorem NPosS3_c31 : cellOk 193462272 193986560 = true := by decide +kernel
theorem NPosS3_c32 : cellOk 193986560 194510848 = true := by decide +kernel
theorem NPosS3_c33 : cellOk 194510848 195035136 = true := by decide +kernel
theorem NPosS3_c34 : cellOk 195035136 196083712 = true := by decide +kernel
theorem NPosS3_c35 : cellOk 196083712 197132288 = true := by decide +kernel
theorem NPosS3_c36 : cellOk 197132288 198180864 = true := by decide +kernel
theorem NPosS3_c37 : cellOk 198180864 199229440 = true := by decide +kernel
theorem NPosS3_c38 : cellOk 199229440 200278016 = true := by decide +kernel
theorem NPosS3_c39 : cellOk 200278016 201326592 = true := by decide +kernel
theorem NPosS3_c40 : cellOk 201326592 202375168 = true := by decide +kernel
theorem NPosS3_c41 : cellOk 202375168 203423744 = true := by decide +kernel
theorem NPosS3_c42 : cellOk 203423744 204472320 = true := by decide +kernel
theorem NPosS3_c43 : cellOk 204472320 205520896 = true := by decide +kernel
theorem NPosS3_c44 : cellOk 205520896 206569472 = true := by decide +kernel
theorem NPosS3_c45 : cellOk 206569472 207618048 = true := by decide +kernel
theorem NPosS3_c46 : cellOk 207618048 208142336 = true := by decide +kernel
theorem NPosS3_c47 : cellOk 208142336 208666624 = true := by decide +kernel
theorem NPosS3_c48 : cellOk 208666624 209190912 = true := by decide +kernel
theorem NPosS3_c49 : cellOk 209190912 209715200 = true := by decide +kernel

theorem NPosS3_ok : chainOk [168820736, 169869312, 170917888, 171966464, 173015040, 174063616, 174587904, 175112192, 175636480, 176160768, 176685056, 177209344, 177733632, 178257920, 179306496, 180355072, 181403648, 182452224, 183500800, 184549376, 185597952, 186646528, 187695104, 188743680, 189792256, 190316544, 190840832, 191365120, 191889408, 192413696, 192937984, 193462272, 193986560, 194510848, 195035136, 196083712, 197132288, 198180864, 199229440, 200278016, 201326592, 202375168, 203423744, 204472320, 205520896, 206569472, 207618048, 208142336, 208666624, 209190912, 209715200] = true :=
  chainOk_cons NPosS3_c0 (chainOk_cons NPosS3_c1 (chainOk_cons NPosS3_c2 (chainOk_cons NPosS3_c3 (chainOk_cons NPosS3_c4 (chainOk_cons NPosS3_c5 (chainOk_cons NPosS3_c6 (chainOk_cons NPosS3_c7 (chainOk_cons NPosS3_c8 (chainOk_cons NPosS3_c9 (chainOk_cons NPosS3_c10 (chainOk_cons NPosS3_c11 (chainOk_cons NPosS3_c12 (chainOk_cons NPosS3_c13 (chainOk_cons NPosS3_c14 (chainOk_cons NPosS3_c15 (chainOk_cons NPosS3_c16 (chainOk_cons NPosS3_c17 (chainOk_cons NPosS3_c18 (chainOk_cons NPosS3_c19 (chainOk_cons NPosS3_c20 (chainOk_cons NPosS3_c21 (chainOk_cons NPosS3_c22 (chainOk_cons NPosS3_c23 (chainOk_cons NPosS3_c24 (chainOk_cons NPosS3_c25 (chainOk_cons NPosS3_c26 (chainOk_cons NPosS3_c27 (chainOk_cons NPosS3_c28 (chainOk_cons NPosS3_c29 (chainOk_cons NPosS3_c30 (chainOk_cons NPosS3_c31 (chainOk_cons NPosS3_c32 (chainOk_cons NPosS3_c33 (chainOk_cons NPosS3_c34 (chainOk_cons NPosS3_c35 (chainOk_cons NPosS3_c36 (chainOk_cons NPosS3_c37 (chainOk_cons NPosS3_c38 (chainOk_cons NPosS3_c39 (chainOk_cons NPosS3_c40 (chainOk_cons NPosS3_c41 (chainOk_cons NPosS3_c42 (chainOk_cons NPosS3_c43 (chainOk_cons NPosS3_c44 (chainOk_cons NPosS3_c45 (chainOk_cons NPosS3_c46 (chainOk_cons NPosS3_c47 (chainOk_cons NPosS3_c48 (chainOk_cons NPosS3_c49 (chainOk_single 209715200))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
