/- L5_2 shard NPosS7: 50 cells, breakpoints 324009984..360185856 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS7_c0 : cellOk 324009984 324534272 = true := by decide +kernel
theorem NPosS7_c1 : cellOk 324534272 325058560 = true := by decide +kernel
theorem NPosS7_c2 : cellOk 325058560 325582848 = true := by decide +kernel
theorem NPosS7_c3 : cellOk 325582848 326107136 = true := by decide +kernel
theorem NPosS7_c4 : cellOk 326107136 326631424 = true := by decide +kernel
theorem NPosS7_c5 : cellOk 326631424 327155712 = true := by decide +kernel
theorem NPosS7_c6 : cellOk 327155712 327680000 = true := by decide +kernel
theorem NPosS7_c7 : cellOk 327680000 328204288 = true := by decide +kernel
theorem NPosS7_c8 : cellOk 328204288 328728576 = true := by decide +kernel
theorem NPosS7_c9 : cellOk 328728576 329252864 = true := by decide +kernel
theorem NPosS7_c10 : cellOk 329252864 329777152 = true := by decide +kernel
theorem NPosS7_c11 : cellOk 329777152 330301440 = true := by decide +kernel
theorem NPosS7_c12 : cellOk 330301440 330825728 = true := by decide +kernel
theorem NPosS7_c13 : cellOk 330825728 331350016 = true := by decide +kernel
theorem NPosS7_c14 : cellOk 331350016 332398592 = true := by decide +kernel
theorem NPosS7_c15 : cellOk 332398592 333447168 = true := by decide +kernel
theorem NPosS7_c16 : cellOk 333447168 334495744 = true := by decide +kernel
theorem NPosS7_c17 : cellOk 334495744 335544320 = true := by decide +kernel
theorem NPosS7_c18 : cellOk 335544320 336592896 = true := by decide +kernel
theorem NPosS7_c19 : cellOk 336592896 337641472 = true := by decide +kernel
theorem NPosS7_c20 : cellOk 337641472 338690048 = true := by decide +kernel
theorem NPosS7_c21 : cellOk 338690048 339738624 = true := by decide +kernel
theorem NPosS7_c22 : cellOk 339738624 340787200 = true := by decide +kernel
theorem NPosS7_c23 : cellOk 340787200 341311488 = true := by decide +kernel
theorem NPosS7_c24 : cellOk 341311488 341835776 = true := by decide +kernel
theorem NPosS7_c25 : cellOk 341835776 342360064 = true := by decide +kernel
theorem NPosS7_c26 : cellOk 342360064 342884352 = true := by decide +kernel
theorem NPosS7_c27 : cellOk 342884352 343408640 = true := by decide +kernel
theorem NPosS7_c28 : cellOk 343408640 343932928 = true := by decide +kernel
theorem NPosS7_c29 : cellOk 343932928 344457216 = true := by decide +kernel
theorem NPosS7_c30 : cellOk 344457216 344981504 = true := by decide +kernel
theorem NPosS7_c31 : cellOk 344981504 345505792 = true := by decide +kernel
theorem NPosS7_c32 : cellOk 345505792 346030080 = true := by decide +kernel
theorem NPosS7_c33 : cellOk 346030080 346554368 = true := by decide +kernel
theorem NPosS7_c34 : cellOk 346554368 347078656 = true := by decide +kernel
theorem NPosS7_c35 : cellOk 347078656 348127232 = true := by decide +kernel
theorem NPosS7_c36 : cellOk 348127232 349175808 = true := by decide +kernel
theorem NPosS7_c37 : cellOk 349175808 350224384 = true := by decide +kernel
theorem NPosS7_c38 : cellOk 350224384 351272960 = true := by decide +kernel
theorem NPosS7_c39 : cellOk 351272960 352321536 = true := by decide +kernel
theorem NPosS7_c40 : cellOk 352321536 353370112 = true := by decide +kernel
theorem NPosS7_c41 : cellOk 353370112 354418688 = true := by decide +kernel
theorem NPosS7_c42 : cellOk 354418688 355467264 = true := by decide +kernel
theorem NPosS7_c43 : cellOk 355467264 356515840 = true := by decide +kernel
theorem NPosS7_c44 : cellOk 356515840 357564416 = true := by decide +kernel
theorem NPosS7_c45 : cellOk 357564416 358088704 = true := by decide +kernel
theorem NPosS7_c46 : cellOk 358088704 358612992 = true := by decide +kernel
theorem NPosS7_c47 : cellOk 358612992 359137280 = true := by decide +kernel
theorem NPosS7_c48 : cellOk 359137280 359661568 = true := by decide +kernel
theorem NPosS7_c49 : cellOk 359661568 360185856 = true := by decide +kernel

theorem NPosS7_ok : chainOk [324009984, 324534272, 325058560, 325582848, 326107136, 326631424, 327155712, 327680000, 328204288, 328728576, 329252864, 329777152, 330301440, 330825728, 331350016, 332398592, 333447168, 334495744, 335544320, 336592896, 337641472, 338690048, 339738624, 340787200, 341311488, 341835776, 342360064, 342884352, 343408640, 343932928, 344457216, 344981504, 345505792, 346030080, 346554368, 347078656, 348127232, 349175808, 350224384, 351272960, 352321536, 353370112, 354418688, 355467264, 356515840, 357564416, 358088704, 358612992, 359137280, 359661568, 360185856] = true :=
  chainOk_cons NPosS7_c0 (chainOk_cons NPosS7_c1 (chainOk_cons NPosS7_c2 (chainOk_cons NPosS7_c3 (chainOk_cons NPosS7_c4 (chainOk_cons NPosS7_c5 (chainOk_cons NPosS7_c6 (chainOk_cons NPosS7_c7 (chainOk_cons NPosS7_c8 (chainOk_cons NPosS7_c9 (chainOk_cons NPosS7_c10 (chainOk_cons NPosS7_c11 (chainOk_cons NPosS7_c12 (chainOk_cons NPosS7_c13 (chainOk_cons NPosS7_c14 (chainOk_cons NPosS7_c15 (chainOk_cons NPosS7_c16 (chainOk_cons NPosS7_c17 (chainOk_cons NPosS7_c18 (chainOk_cons NPosS7_c19 (chainOk_cons NPosS7_c20 (chainOk_cons NPosS7_c21 (chainOk_cons NPosS7_c22 (chainOk_cons NPosS7_c23 (chainOk_cons NPosS7_c24 (chainOk_cons NPosS7_c25 (chainOk_cons NPosS7_c26 (chainOk_cons NPosS7_c27 (chainOk_cons NPosS7_c28 (chainOk_cons NPosS7_c29 (chainOk_cons NPosS7_c30 (chainOk_cons NPosS7_c31 (chainOk_cons NPosS7_c32 (chainOk_cons NPosS7_c33 (chainOk_cons NPosS7_c34 (chainOk_cons NPosS7_c35 (chainOk_cons NPosS7_c36 (chainOk_cons NPosS7_c37 (chainOk_cons NPosS7_c38 (chainOk_cons NPosS7_c39 (chainOk_cons NPosS7_c40 (chainOk_cons NPosS7_c41 (chainOk_cons NPosS7_c42 (chainOk_cons NPosS7_c43 (chainOk_cons NPosS7_c44 (chainOk_cons NPosS7_c45 (chainOk_cons NPosS7_c46 (chainOk_cons NPosS7_c47 (chainOk_cons NPosS7_c48 (chainOk_cons NPosS7_c49 (chainOk_single 360185856))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
