/- L5_2 shard NPosS2: 50 cells, breakpoints 125829120..168820736 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS2_c0 : cellOk 125829120 126353408 = true := by decide +kernel
theorem NPosS2_c1 : cellOk 126353408 126877696 = true := by decide +kernel
theorem NPosS2_c2 : cellOk 126877696 127401984 = true := by decide +kernel
theorem NPosS2_c3 : cellOk 127401984 127926272 = true := by decide +kernel
theorem NPosS2_c4 : cellOk 127926272 128974848 = true := by decide +kernel
theorem NPosS2_c5 : cellOk 128974848 130023424 = true := by decide +kernel
theorem NPosS2_c6 : cellOk 130023424 131072000 = true := by decide +kernel
theorem NPosS2_c7 : cellOk 131072000 132120576 = true := by decide +kernel
theorem NPosS2_c8 : cellOk 132120576 134217728 = true := by decide +kernel
theorem NPosS2_c9 : cellOk 134217728 135266304 = true := by decide +kernel
theorem NPosS2_c10 : cellOk 135266304 136314880 = true := by decide +kernel
theorem NPosS2_c11 : cellOk 136314880 137363456 = true := by decide +kernel
theorem NPosS2_c12 : cellOk 137363456 138412032 = true := by decide +kernel
theorem NPosS2_c13 : cellOk 138412032 139460608 = true := by decide +kernel
theorem NPosS2_c14 : cellOk 139460608 140509184 = true := by decide +kernel
theorem NPosS2_c15 : cellOk 140509184 141033472 = true := by decide +kernel
theorem NPosS2_c16 : cellOk 141033472 141557760 = true := by decide +kernel
theorem NPosS2_c17 : cellOk 141557760 142082048 = true := by decide +kernel
theorem NPosS2_c18 : cellOk 142082048 142606336 = true := by decide +kernel
theorem NPosS2_c19 : cellOk 142606336 143130624 = true := by decide +kernel
theorem NPosS2_c20 : cellOk 143130624 143654912 = true := by decide +kernel
theorem NPosS2_c21 : cellOk 143654912 144179200 = true := by decide +kernel
theorem NPosS2_c22 : cellOk 144179200 144703488 = true := by decide +kernel
theorem NPosS2_c23 : cellOk 144703488 145752064 = true := by decide +kernel
theorem NPosS2_c24 : cellOk 145752064 146800640 = true := by decide +kernel
theorem NPosS2_c25 : cellOk 146800640 147849216 = true := by decide +kernel
theorem NPosS2_c26 : cellOk 147849216 148897792 = true := by decide +kernel
theorem NPosS2_c27 : cellOk 148897792 149946368 = true := by decide +kernel
theorem NPosS2_c28 : cellOk 149946368 150994944 = true := by decide +kernel
theorem NPosS2_c29 : cellOk 150994944 152043520 = true := by decide +kernel
theorem NPosS2_c30 : cellOk 152043520 153092096 = true := by decide +kernel
theorem NPosS2_c31 : cellOk 153092096 154140672 = true := by decide +kernel
theorem NPosS2_c32 : cellOk 154140672 155189248 = true := by decide +kernel
theorem NPosS2_c33 : cellOk 155189248 156237824 = true := by decide +kernel
theorem NPosS2_c34 : cellOk 156237824 157286400 = true := by decide +kernel
theorem NPosS2_c35 : cellOk 157286400 157810688 = true := by decide +kernel
theorem NPosS2_c36 : cellOk 157810688 158334976 = true := by decide +kernel
theorem NPosS2_c37 : cellOk 158334976 158859264 = true := by decide +kernel
theorem NPosS2_c38 : cellOk 158859264 159383552 = true := by decide +kernel
theorem NPosS2_c39 : cellOk 159383552 159907840 = true := by decide +kernel
theorem NPosS2_c40 : cellOk 159907840 160432128 = true := by decide +kernel
theorem NPosS2_c41 : cellOk 160432128 160956416 = true := by decide +kernel
theorem NPosS2_c42 : cellOk 160956416 161480704 = true := by decide +kernel
theorem NPosS2_c43 : cellOk 161480704 162529280 = true := by decide +kernel
theorem NPosS2_c44 : cellOk 162529280 163577856 = true := by decide +kernel
theorem NPosS2_c45 : cellOk 163577856 164626432 = true := by decide +kernel
theorem NPosS2_c46 : cellOk 164626432 165675008 = true := by decide +kernel
theorem NPosS2_c47 : cellOk 165675008 166723584 = true := by decide +kernel
theorem NPosS2_c48 : cellOk 166723584 167772160 = true := by decide +kernel
theorem NPosS2_c49 : cellOk 167772160 168820736 = true := by decide +kernel

theorem NPosS2_ok : chainOk [125829120, 126353408, 126877696, 127401984, 127926272, 128974848, 130023424, 131072000, 132120576, 134217728, 135266304, 136314880, 137363456, 138412032, 139460608, 140509184, 141033472, 141557760, 142082048, 142606336, 143130624, 143654912, 144179200, 144703488, 145752064, 146800640, 147849216, 148897792, 149946368, 150994944, 152043520, 153092096, 154140672, 155189248, 156237824, 157286400, 157810688, 158334976, 158859264, 159383552, 159907840, 160432128, 160956416, 161480704, 162529280, 163577856, 164626432, 165675008, 166723584, 167772160, 168820736] = true :=
  chainOk_cons NPosS2_c0 (chainOk_cons NPosS2_c1 (chainOk_cons NPosS2_c2 (chainOk_cons NPosS2_c3 (chainOk_cons NPosS2_c4 (chainOk_cons NPosS2_c5 (chainOk_cons NPosS2_c6 (chainOk_cons NPosS2_c7 (chainOk_cons NPosS2_c8 (chainOk_cons NPosS2_c9 (chainOk_cons NPosS2_c10 (chainOk_cons NPosS2_c11 (chainOk_cons NPosS2_c12 (chainOk_cons NPosS2_c13 (chainOk_cons NPosS2_c14 (chainOk_cons NPosS2_c15 (chainOk_cons NPosS2_c16 (chainOk_cons NPosS2_c17 (chainOk_cons NPosS2_c18 (chainOk_cons NPosS2_c19 (chainOk_cons NPosS2_c20 (chainOk_cons NPosS2_c21 (chainOk_cons NPosS2_c22 (chainOk_cons NPosS2_c23 (chainOk_cons NPosS2_c24 (chainOk_cons NPosS2_c25 (chainOk_cons NPosS2_c26 (chainOk_cons NPosS2_c27 (chainOk_cons NPosS2_c28 (chainOk_cons NPosS2_c29 (chainOk_cons NPosS2_c30 (chainOk_cons NPosS2_c31 (chainOk_cons NPosS2_c32 (chainOk_cons NPosS2_c33 (chainOk_cons NPosS2_c34 (chainOk_cons NPosS2_c35 (chainOk_cons NPosS2_c36 (chainOk_cons NPosS2_c37 (chainOk_cons NPosS2_c38 (chainOk_cons NPosS2_c39 (chainOk_cons NPosS2_c40 (chainOk_cons NPosS2_c41 (chainOk_cons NPosS2_c42 (chainOk_cons NPosS2_c43 (chainOk_cons NPosS2_c44 (chainOk_cons NPosS2_c45 (chainOk_cons NPosS2_c46 (chainOk_cons NPosS2_c47 (chainOk_cons NPosS2_c48 (chainOk_cons NPosS2_c49 (chainOk_single 168820736))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
