/- L5_2 shard NPosS9: 50 cells, breakpoints 395837440..432013312 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS9_c0 : cellOk 395837440 396361728 = true := by decide +kernel
theorem NPosS9_c1 : cellOk 396361728 396886016 = true := by decide +kernel
theorem NPosS9_c2 : cellOk 396886016 397410304 = true := by decide +kernel
theorem NPosS9_c3 : cellOk 397410304 398458880 = true := by decide +kernel
theorem NPosS9_c4 : cellOk 398458880 399507456 = true := by decide +kernel
theorem NPosS9_c5 : cellOk 399507456 400556032 = true := by decide +kernel
theorem NPosS9_c6 : cellOk 400556032 401604608 = true := by decide +kernel
theorem NPosS9_c7 : cellOk 401604608 402653184 = true := by decide +kernel
theorem NPosS9_c8 : cellOk 402653184 403701760 = true := by decide +kernel
theorem NPosS9_c9 : cellOk 403701760 404750336 = true := by decide +kernel
theorem NPosS9_c10 : cellOk 404750336 405798912 = true := by decide +kernel
theorem NPosS9_c11 : cellOk 405798912 406847488 = true := by decide +kernel
theorem NPosS9_c12 : cellOk 406847488 407896064 = true := by decide +kernel
theorem NPosS9_c13 : cellOk 407896064 408420352 = true := by decide +kernel
theorem NPosS9_c14 : cellOk 408420352 408944640 = true := by decide +kernel
theorem NPosS9_c15 : cellOk 408944640 409468928 = true := by decide +kernel
theorem NPosS9_c16 : cellOk 409468928 409993216 = true := by decide +kernel
theorem NPosS9_c17 : cellOk 409993216 410517504 = true := by decide +kernel
theorem NPosS9_c18 : cellOk 410517504 411041792 = true := by decide +kernel
theorem NPosS9_c19 : cellOk 411041792 411566080 = true := by decide +kernel
theorem NPosS9_c20 : cellOk 411566080 412090368 = true := by decide +kernel
theorem NPosS9_c21 : cellOk 412090368 412614656 = true := by decide +kernel
theorem NPosS9_c22 : cellOk 412614656 413138944 = true := by decide +kernel
theorem NPosS9_c23 : cellOk 413138944 413663232 = true := by decide +kernel
theorem NPosS9_c24 : cellOk 413663232 414187520 = true := by decide +kernel
theorem NPosS9_c25 : cellOk 414187520 414711808 = true := by decide +kernel
theorem NPosS9_c26 : cellOk 414711808 415236096 = true := by decide +kernel
theorem NPosS9_c27 : cellOk 415236096 416284672 = true := by decide +kernel
theorem NPosS9_c28 : cellOk 416284672 417333248 = true := by decide +kernel
theorem NPosS9_c29 : cellOk 417333248 418381824 = true := by decide +kernel
theorem NPosS9_c30 : cellOk 418381824 419430400 = true := by decide +kernel
theorem NPosS9_c31 : cellOk 419430400 420478976 = true := by decide +kernel
theorem NPosS9_c32 : cellOk 420478976 421527552 = true := by decide +kernel
theorem NPosS9_c33 : cellOk 421527552 422576128 = true := by decide +kernel
theorem NPosS9_c34 : cellOk 422576128 423624704 = true := by decide +kernel
theorem NPosS9_c35 : cellOk 423624704 424148992 = true := by decide +kernel
theorem NPosS9_c36 : cellOk 424148992 424673280 = true := by decide +kernel
theorem NPosS9_c37 : cellOk 424673280 425197568 = true := by decide +kernel
theorem NPosS9_c38 : cellOk 425197568 425721856 = true := by decide +kernel
theorem NPosS9_c39 : cellOk 425721856 426246144 = true := by decide +kernel
theorem NPosS9_c40 : cellOk 426246144 426770432 = true := by decide +kernel
theorem NPosS9_c41 : cellOk 426770432 427294720 = true := by decide +kernel
theorem NPosS9_c42 : cellOk 427294720 427819008 = true := by decide +kernel
theorem NPosS9_c43 : cellOk 427819008 428343296 = true := by decide +kernel
theorem NPosS9_c44 : cellOk 428343296 428867584 = true := by decide +kernel
theorem NPosS9_c45 : cellOk 428867584 429391872 = true := by decide +kernel
theorem NPosS9_c46 : cellOk 429391872 429916160 = true := by decide +kernel
theorem NPosS9_c47 : cellOk 429916160 430440448 = true := by decide +kernel
theorem NPosS9_c48 : cellOk 430440448 430964736 = true := by decide +kernel
theorem NPosS9_c49 : cellOk 430964736 432013312 = true := by decide +kernel

theorem NPosS9_ok : chainOk [395837440, 396361728, 396886016, 397410304, 398458880, 399507456, 400556032, 401604608, 402653184, 403701760, 404750336, 405798912, 406847488, 407896064, 408420352, 408944640, 409468928, 409993216, 410517504, 411041792, 411566080, 412090368, 412614656, 413138944, 413663232, 414187520, 414711808, 415236096, 416284672, 417333248, 418381824, 419430400, 420478976, 421527552, 422576128, 423624704, 424148992, 424673280, 425197568, 425721856, 426246144, 426770432, 427294720, 427819008, 428343296, 428867584, 429391872, 429916160, 430440448, 430964736, 432013312] = true :=
  chainOk_cons NPosS9_c0 (chainOk_cons NPosS9_c1 (chainOk_cons NPosS9_c2 (chainOk_cons NPosS9_c3 (chainOk_cons NPosS9_c4 (chainOk_cons NPosS9_c5 (chainOk_cons NPosS9_c6 (chainOk_cons NPosS9_c7 (chainOk_cons NPosS9_c8 (chainOk_cons NPosS9_c9 (chainOk_cons NPosS9_c10 (chainOk_cons NPosS9_c11 (chainOk_cons NPosS9_c12 (chainOk_cons NPosS9_c13 (chainOk_cons NPosS9_c14 (chainOk_cons NPosS9_c15 (chainOk_cons NPosS9_c16 (chainOk_cons NPosS9_c17 (chainOk_cons NPosS9_c18 (chainOk_cons NPosS9_c19 (chainOk_cons NPosS9_c20 (chainOk_cons NPosS9_c21 (chainOk_cons NPosS9_c22 (chainOk_cons NPosS9_c23 (chainOk_cons NPosS9_c24 (chainOk_cons NPosS9_c25 (chainOk_cons NPosS9_c26 (chainOk_cons NPosS9_c27 (chainOk_cons NPosS9_c28 (chainOk_cons NPosS9_c29 (chainOk_cons NPosS9_c30 (chainOk_cons NPosS9_c31 (chainOk_cons NPosS9_c32 (chainOk_cons NPosS9_c33 (chainOk_cons NPosS9_c34 (chainOk_cons NPosS9_c35 (chainOk_cons NPosS9_c36 (chainOk_cons NPosS9_c37 (chainOk_cons NPosS9_c38 (chainOk_cons NPosS9_c39 (chainOk_cons NPosS9_c40 (chainOk_cons NPosS9_c41 (chainOk_cons NPosS9_c42 (chainOk_cons NPosS9_c43 (chainOk_cons NPosS9_c44 (chainOk_cons NPosS9_c45 (chainOk_cons NPosS9_c46 (chainOk_cons NPosS9_c47 (chainOk_cons NPosS9_c48 (chainOk_cons NPosS9_c49 (chainOk_single 432013312))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
