/- L5_2 shard NPosS4: 50 cells, breakpoints 209715200..246415360 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS4_c0 : cellOk 209715200 210239488 = true := by decide +kernel
theorem NPosS4_c1 : cellOk 210239488 210763776 = true := by decide +kernel
theorem NPosS4_c2 : cellOk 210763776 211288064 = true := by decide +kernel
theorem NPosS4_c3 : cellOk 211288064 211812352 = true := by decide +kernel
theorem NPosS4_c4 : cellOk 211812352 212336640 = true := by decide +kernel
theorem NPosS4_c5 : cellOk 212336640 212860928 = true := by decide +kernel
theorem NPosS4_c6 : cellOk 212860928 213909504 = true := by decide +kernel
theorem NPosS4_c7 : cellOk 213909504 214958080 = true := by decide +kernel
theorem NPosS4_c8 : cellOk 214958080 216006656 = true := by decide +kernel
theorem NPosS4_c9 : cellOk 216006656 217055232 = true := by decide +kernel
theorem NPosS4_c10 : cellOk 217055232 218103808 = true := by decide +kernel
theorem NPosS4_c11 : cellOk 218103808 219152384 = true := by decide +kernel
theorem NPosS4_c12 : cellOk 219152384 220200960 = true := by decide +kernel
theorem NPosS4_c13 : cellOk 220200960 221249536 = true := by decide +kernel
theorem NPosS4_c14 : cellOk 221249536 222298112 = true := by decide +kernel
theorem NPosS4_c15 : cellOk 222298112 223346688 = true := by decide +kernel
theorem NPosS4_c16 : cellOk 223346688 223870976 = true := by decide +kernel
theorem NPosS4_c17 : cellOk 223870976 224395264 = true := by decide +kernel
theorem NPosS4_c18 : cellOk 224395264 224919552 = true := by decide +kernel
theorem NPosS4_c19 : cellOk 224919552 225443840 = true := by decide +kernel
theorem NPosS4_c20 : cellOk 225443840 225968128 = true := by decide +kernel
theorem NPosS4_c21 : cellOk 225968128 226492416 = true := by decide +kernel
theorem NPosS4_c22 : cellOk 226492416 227016704 = true := by decide +kernel
theorem NPosS4_c23 : cellOk 227016704 227540992 = true := by decide +kernel
theorem NPosS4_c24 : cellOk 227540992 228065280 = true := by decide +kernel
theorem NPosS4_c25 : cellOk 228065280 228589568 = true := by decide +kernel
theorem NPosS4_c26 : cellOk 228589568 229113856 = true := by decide +kernel
theorem NPosS4_c27 : cellOk 229113856 229638144 = true := by decide +kernel
theorem NPosS4_c28 : cellOk 229638144 230686720 = true := by decide +kernel
theorem NPosS4_c29 : cellOk 230686720 231735296 = true := by decide +kernel
theorem NPosS4_c30 : cellOk 231735296 232783872 = true := by decide +kernel
theorem NPosS4_c31 : cellOk 232783872 233832448 = true := by decide +kernel
theorem NPosS4_c32 : cellOk 233832448 234881024 = true := by decide +kernel
theorem NPosS4_c33 : cellOk 234881024 235929600 = true := by decide +kernel
theorem NPosS4_c34 : cellOk 235929600 236978176 = true := by decide +kernel
theorem NPosS4_c35 : cellOk 236978176 238026752 = true := by decide +kernel
theorem NPosS4_c36 : cellOk 238026752 239075328 = true := by decide +kernel
theorem NPosS4_c37 : cellOk 239075328 240123904 = true := by decide +kernel
theorem NPosS4_c38 : cellOk 240123904 240648192 = true := by decide +kernel
theorem NPosS4_c39 : cellOk 240648192 241172480 = true := by decide +kernel
theorem NPosS4_c40 : cellOk 241172480 241696768 = true := by decide +kernel
theorem NPosS4_c41 : cellOk 241696768 242221056 = true := by decide +kernel
theorem NPosS4_c42 : cellOk 242221056 242745344 = true := by decide +kernel
theorem NPosS4_c43 : cellOk 242745344 243269632 = true := by decide +kernel
theorem NPosS4_c44 : cellOk 243269632 243793920 = true := by decide +kernel
theorem NPosS4_c45 : cellOk 243793920 244318208 = true := by decide +kernel
theorem NPosS4_c46 : cellOk 244318208 244842496 = true := by decide +kernel
theorem NPosS4_c47 : cellOk 244842496 245366784 = true := by decide +kernel
theorem NPosS4_c48 : cellOk 245366784 245891072 = true := by decide +kernel
theorem NPosS4_c49 : cellOk 245891072 246415360 = true := by decide +kernel

theorem NPosS4_ok : chainOk [209715200, 210239488, 210763776, 211288064, 211812352, 212336640, 212860928, 213909504, 214958080, 216006656, 217055232, 218103808, 219152384, 220200960, 221249536, 222298112, 223346688, 223870976, 224395264, 224919552, 225443840, 225968128, 226492416, 227016704, 227540992, 228065280, 228589568, 229113856, 229638144, 230686720, 231735296, 232783872, 233832448, 234881024, 235929600, 236978176, 238026752, 239075328, 240123904, 240648192, 241172480, 241696768, 242221056, 242745344, 243269632, 243793920, 244318208, 244842496, 245366784, 245891072, 246415360] = true :=
  chainOk_cons NPosS4_c0 (chainOk_cons NPosS4_c1 (chainOk_cons NPosS4_c2 (chainOk_cons NPosS4_c3 (chainOk_cons NPosS4_c4 (chainOk_cons NPosS4_c5 (chainOk_cons NPosS4_c6 (chainOk_cons NPosS4_c7 (chainOk_cons NPosS4_c8 (chainOk_cons NPosS4_c9 (chainOk_cons NPosS4_c10 (chainOk_cons NPosS4_c11 (chainOk_cons NPosS4_c12 (chainOk_cons NPosS4_c13 (chainOk_cons NPosS4_c14 (chainOk_cons NPosS4_c15 (chainOk_cons NPosS4_c16 (chainOk_cons NPosS4_c17 (chainOk_cons NPosS4_c18 (chainOk_cons NPosS4_c19 (chainOk_cons NPosS4_c20 (chainOk_cons NPosS4_c21 (chainOk_cons NPosS4_c22 (chainOk_cons NPosS4_c23 (chainOk_cons NPosS4_c24 (chainOk_cons NPosS4_c25 (chainOk_cons NPosS4_c26 (chainOk_cons NPosS4_c27 (chainOk_cons NPosS4_c28 (chainOk_cons NPosS4_c29 (chainOk_cons NPosS4_c30 (chainOk_cons NPosS4_c31 (chainOk_cons NPosS4_c32 (chainOk_cons NPosS4_c33 (chainOk_cons NPosS4_c34 (chainOk_cons NPosS4_c35 (chainOk_cons NPosS4_c36 (chainOk_cons NPosS4_c37 (chainOk_cons NPosS4_c38 (chainOk_cons NPosS4_c39 (chainOk_cons NPosS4_c40 (chainOk_cons NPosS4_c41 (chainOk_cons NPosS4_c42 (chainOk_cons NPosS4_c43 (chainOk_cons NPosS4_c44 (chainOk_cons NPosS4_c45 (chainOk_cons NPosS4_c46 (chainOk_cons NPosS4_c47 (chainOk_cons NPosS4_c48 (chainOk_cons NPosS4_c49 (chainOk_single 246415360))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
