/- L5_2 shard NPosS8: 50 cells, breakpoints 360185856..395837440 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS8_c0 : cellOk 360185856 360710144 = true := by decide +kernel
theorem NPosS8_c1 : cellOk 360710144 361234432 = true := by decide +kernel
theorem NPosS8_c2 : cellOk 361234432 361758720 = true := by decide +kernel
theorem NPosS8_c3 : cellOk 361758720 362283008 = true := by decide +kernel
theorem NPosS8_c4 : cellOk 362283008 362807296 = true := by decide +kernel
theorem NPosS8_c5 : cellOk 362807296 363331584 = true := by decide +kernel
theorem NPosS8_c6 : cellOk 363331584 363855872 = true := by decide +kernel
theorem NPosS8_c7 : cellOk 363855872 364904448 = true := by decide +kernel
theorem NPosS8_c8 : cellOk 364904448 365953024 = true := by decide +kernel
theorem NPosS8_c9 : cellOk 365953024 367001600 = true := by decide +kernel
theorem NPosS8_c10 : cellOk 367001600 368050176 = true := by decide +kernel
theorem NPosS8_c11 : cellOk 368050176 369098752 = true := by decide +kernel
theorem NPosS8_c12 : cellOk 369098752 370147328 = true := by decide +kernel
theorem NPosS8_c13 : cellOk 370147328 371195904 = true := by decide +kernel
theorem NPosS8_c14 : cellOk 371195904 372244480 = true := by decide +kernel
theorem NPosS8_c15 : cellOk 372244480 373293056 = true := by decide +kernel
theorem NPosS8_c16 : cellOk 373293056 373817344 = true := by decide +kernel
theorem NPosS8_c17 : cellOk 373817344 374341632 = true := by decide +kernel
theorem NPosS8_c18 : cellOk 374341632 374865920 = true := by decide +kernel
theorem NPosS8_c19 : cellOk 374865920 375390208 = true := by decide +kernel
theorem NPosS8_c20 : cellOk 375390208 375914496 = true := by decide +kernel
theorem NPosS8_c21 : cellOk 375914496 376438784 = true := by decide +kernel
theorem NPosS8_c22 : cellOk 376438784 376963072 = true := by decide +kernel
theorem NPosS8_c23 : cellOk 376963072 377487360 = true := by decide +kernel
theorem NPosS8_c24 : cellOk 377487360 378011648 = true := by decide +kernel
theorem NPosS8_c25 : cellOk 378011648 378535936 = true := by decide +kernel
theorem NPosS8_c26 : cellOk 378535936 379060224 = true := by decide +kernel
theorem NPosS8_c27 : cellOk 379060224 379584512 = true := by decide +kernel
theorem NPosS8_c28 : cellOk 379584512 380108800 = true := by decide +kernel
theorem NPosS8_c29 : cellOk 380108800 380633088 = true := by decide +kernel
theorem NPosS8_c30 : cellOk 380633088 381681664 = true := by decide +kernel
theorem NPosS8_c31 : cellOk 381681664 382730240 = true := by decide +kernel
theorem NPosS8_c32 : cellOk 382730240 383778816 = true := by decide +kernel
theorem NPosS8_c33 : cellOk 383778816 384827392 = true := by decide +kernel
theorem NPosS8_c34 : cellOk 384827392 385875968 = true := by decide +kernel
theorem NPosS8_c35 : cellOk 385875968 386924544 = true := by decide +kernel
theorem NPosS8_c36 : cellOk 386924544 387973120 = true := by decide +kernel
theorem NPosS8_c37 : cellOk 387973120 389021696 = true := by decide +kernel
theorem NPosS8_c38 : cellOk 389021696 390070272 = true := by decide +kernel
theorem NPosS8_c39 : cellOk 390070272 390594560 = true := by decide +kernel
theorem NPosS8_c40 : cellOk 390594560 391118848 = true := by decide +kernel
theorem NPosS8_c41 : cellOk 391118848 391643136 = true := by decide +kernel
theorem NPosS8_c42 : cellOk 391643136 392167424 = true := by decide +kernel
theorem NPosS8_c43 : cellOk 392167424 392691712 = true := by decide +kernel
theorem NPosS8_c44 : cellOk 392691712 393216000 = true := by decide +kernel
theorem NPosS8_c45 : cellOk 393216000 393740288 = true := by decide +kernel
theorem NPosS8_c46 : cellOk 393740288 394264576 = true := by decide +kernel
theorem NPosS8_c47 : cellOk 394264576 394788864 = true := by decide +kernel
theorem NPosS8_c48 : cellOk 394788864 395313152 = true := by decide +kernel
theorem NPosS8_c49 : cellOk 395313152 395837440 = true := by decide +kernel

theorem NPosS8_ok : chainOk [360185856, 360710144, 361234432, 361758720, 362283008, 362807296, 363331584, 363855872, 364904448, 365953024, 367001600, 368050176, 369098752, 370147328, 371195904, 372244480, 373293056, 373817344, 374341632, 374865920, 375390208, 375914496, 376438784, 376963072, 377487360, 378011648, 378535936, 379060224, 379584512, 380108800, 380633088, 381681664, 382730240, 383778816, 384827392, 385875968, 386924544, 387973120, 389021696, 390070272, 390594560, 391118848, 391643136, 392167424, 392691712, 393216000, 393740288, 394264576, 394788864, 395313152, 395837440] = true :=
  chainOk_cons NPosS8_c0 (chainOk_cons NPosS8_c1 (chainOk_cons NPosS8_c2 (chainOk_cons NPosS8_c3 (chainOk_cons NPosS8_c4 (chainOk_cons NPosS8_c5 (chainOk_cons NPosS8_c6 (chainOk_cons NPosS8_c7 (chainOk_cons NPosS8_c8 (chainOk_cons NPosS8_c9 (chainOk_cons NPosS8_c10 (chainOk_cons NPosS8_c11 (chainOk_cons NPosS8_c12 (chainOk_cons NPosS8_c13 (chainOk_cons NPosS8_c14 (chainOk_cons NPosS8_c15 (chainOk_cons NPosS8_c16 (chainOk_cons NPosS8_c17 (chainOk_cons NPosS8_c18 (chainOk_cons NPosS8_c19 (chainOk_cons NPosS8_c20 (chainOk_cons NPosS8_c21 (chainOk_cons NPosS8_c22 (chainOk_cons NPosS8_c23 (chainOk_cons NPosS8_c24 (chainOk_cons NPosS8_c25 (chainOk_cons NPosS8_c26 (chainOk_cons NPosS8_c27 (chainOk_cons NPosS8_c28 (chainOk_cons NPosS8_c29 (chainOk_cons NPosS8_c30 (chainOk_cons NPosS8_c31 (chainOk_cons NPosS8_c32 (chainOk_cons NPosS8_c33 (chainOk_cons NPosS8_c34 (chainOk_cons NPosS8_c35 (chainOk_cons NPosS8_c36 (chainOk_cons NPosS8_c37 (chainOk_cons NPosS8_c38 (chainOk_cons NPosS8_c39 (chainOk_cons NPosS8_c40 (chainOk_cons NPosS8_c41 (chainOk_cons NPosS8_c42 (chainOk_cons NPosS8_c43 (chainOk_cons NPosS8_c44 (chainOk_cons NPosS8_c45 (chainOk_cons NPosS8_c46 (chainOk_cons NPosS8_c47 (chainOk_cons NPosS8_c48 (chainOk_cons NPosS8_c49 (chainOk_single 395837440))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
