/- L5_2 shard NPosS11: 50 cells, breakpoints 467664896..503316480 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS11_c0 : cellOk 467664896 468713472 = true := by decide +kernel
theorem NPosS11_c1 : cellOk 468713472 469762048 = true := by decide +kernel
theorem NPosS11_c2 : cellOk 469762048 470810624 = true := by decide +kernel
theorem NPosS11_c3 : cellOk 470810624 471859200 = true := by decide +kernel
theorem NPosS11_c4 : cellOk 471859200 472907776 = true := by decide +kernel
theorem NPosS11_c5 : cellOk 472907776 473956352 = true := by decide +kernel
theorem NPosS11_c6 : cellOk 473956352 474480640 = true := by decide +kernel
theorem NPosS11_c7 : cellOk 474480640 475004928 = true := by decide +kernel
theorem NPosS11_c8 : cellOk 475004928 475529216 = true := by decide +kernel
theorem NPosS11_c9 : cellOk 475529216 476053504 = true := by decide +kernel
theorem NPosS11_c10 : cellOk 476053504 476577792 = true := by decide +kernel
theorem NPosS11_c11 : cellOk 476577792 477102080 = true := by decide +kernel
theorem NPosS11_c12 : cellOk 477102080 477626368 = true := by decide +kernel
theorem NPosS11_c13 : cellOk 477626368 478150656 = true := by decide +kernel
theorem NPosS11_c14 : cellOk 478150656 478674944 = true := by decide +kernel
theorem NPosS11_c15 : cellOk 478674944 479199232 = true := by decide +kernel
theorem NPosS11_c16 : cellOk 479199232 479723520 = true := by decide +kernel
theorem NPosS11_c17 : cellOk 479723520 480247808 = true := by decide +kernel
theorem NPosS11_c18 : cellOk 480247808 480772096 = true := by decide +kernel
theorem NPosS11_c19 : cellOk 480772096 481296384 = true := by decide +kernel
theorem NPosS11_c20 : cellOk 481296384 481820672 = true := by decide +kernel
theorem NPosS11_c21 : cellOk 481820672 482344960 = true := by decide +kernel
theorem NPosS11_c22 : cellOk 482344960 483393536 = true := by decide +kernel
theorem NPosS11_c23 : cellOk 483393536 484442112 = true := by decide +kernel
theorem NPosS11_c24 : cellOk 484442112 485490688 = true := by decide +kernel
theorem NPosS11_c25 : cellOk 485490688 486539264 = true := by decide +kernel
theorem NPosS11_c26 : cellOk 486539264 487587840 = true := by decide +kernel
theorem NPosS11_c27 : cellOk 487587840 488636416 = true := by decide +kernel
theorem NPosS11_c28 : cellOk 488636416 489684992 = true := by decide +kernel
theorem NPosS11_c29 : cellOk 489684992 490733568 = true := by decide +kernel
theorem NPosS11_c30 : cellOk 490733568 491257856 = true := by decide +kernel
theorem NPosS11_c31 : cellOk 491257856 491782144 = true := by decide +kernel
theorem NPosS11_c32 : cellOk 491782144 492306432 = true := by decide +kernel
theorem NPosS11_c33 : cellOk 492306432 492830720 = true := by decide +kernel
theorem NPosS11_c34 : cellOk 492830720 493355008 = true := by decide +kernel
theorem NPosS11_c35 : cellOk 493355008 493879296 = true := by decide +kernel
theorem NPosS11_c36 : cellOk 493879296 494403584 = true := by decide +kernel
theorem NPosS11_c37 : cellOk 494403584 494927872 = true := by decide +kernel
theorem NPosS11_c38 : cellOk 494927872 495452160 = true := by decide +kernel
theorem NPosS11_c39 : cellOk 495452160 495976448 = true := by decide +kernel
theorem NPosS11_c40 : cellOk 495976448 496500736 = true := by decide +kernel
theorem NPosS11_c41 : cellOk 496500736 497025024 = true := by decide +kernel
theorem NPosS11_c42 : cellOk 497025024 497549312 = true := by decide +kernel
theorem NPosS11_c43 : cellOk 497549312 498073600 = true := by decide +kernel
theorem NPosS11_c44 : cellOk 498073600 498597888 = true := by decide +kernel
theorem NPosS11_c45 : cellOk 498597888 499122176 = true := by decide +kernel
theorem NPosS11_c46 : cellOk 499122176 500170752 = true := by decide +kernel
theorem NPosS11_c47 : cellOk 500170752 501219328 = true := by decide +kernel
theorem NPosS11_c48 : cellOk 501219328 502267904 = true := by decide +kernel
theorem NPosS11_c49 : cellOk 502267904 503316480 = true := by decide +kernel

theorem NPosS11_ok : chainOk [467664896, 468713472, 469762048, 470810624, 471859200, 472907776, 473956352, 474480640, 475004928, 475529216, 476053504, 476577792, 477102080, 477626368, 478150656, 478674944, 479199232, 479723520, 480247808, 480772096, 481296384, 481820672, 482344960, 483393536, 484442112, 485490688, 486539264, 487587840, 488636416, 489684992, 490733568, 491257856, 491782144, 492306432, 492830720, 493355008, 493879296, 494403584, 494927872, 495452160, 495976448, 496500736, 497025024, 497549312, 498073600, 498597888, 499122176, 500170752, 501219328, 502267904, 503316480] = true :=
  chainOk_cons NPosS11_c0 (chainOk_cons NPosS11_c1 (chainOk_cons NPosS11_c2 (chainOk_cons NPosS11_c3 (chainOk_cons NPosS11_c4 (chainOk_cons NPosS11_c5 (chainOk_cons NPosS11_c6 (chainOk_cons NPosS11_c7 (chainOk_cons NPosS11_c8 (chainOk_cons NPosS11_c9 (chainOk_cons NPosS11_c10 (chainOk_cons NPosS11_c11 (chainOk_cons NPosS11_c12 (chainOk_cons NPosS11_c13 (chainOk_cons NPosS11_c14 (chainOk_cons NPosS11_c15 (chainOk_cons NPosS11_c16 (chainOk_cons NPosS11_c17 (chainOk_cons NPosS11_c18 (chainOk_cons NPosS11_c19 (chainOk_cons NPosS11_c20 (chainOk_cons NPosS11_c21 (chainOk_cons NPosS11_c22 (chainOk_cons NPosS11_c23 (chainOk_cons NPosS11_c24 (chainOk_cons NPosS11_c25 (chainOk_cons NPosS11_c26 (chainOk_cons NPosS11_c27 (chainOk_cons NPosS11_c28 (chainOk_cons NPosS11_c29 (chainOk_cons NPosS11_c30 (chainOk_cons NPosS11_c31 (chainOk_cons NPosS11_c32 (chainOk_cons NPosS11_c33 (chainOk_cons NPosS11_c34 (chainOk_cons NPosS11_c35 (chainOk_cons NPosS11_c36 (chainOk_cons NPosS11_c37 (chainOk_cons NPosS11_c38 (chainOk_cons NPosS11_c39 (chainOk_cons NPosS11_c40 (chainOk_cons NPosS11_c41 (chainOk_cons NPosS11_c42 (chainOk_cons NPosS11_c43 (chainOk_cons NPosS11_c44 (chainOk_cons NPosS11_c45 (chainOk_cons NPosS11_c46 (chainOk_cons NPosS11_c47 (chainOk_cons NPosS11_c48 (chainOk_cons NPosS11_c49 (chainOk_single 503316480))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
