/- L5_2 shard NPosS10: 50 cells, breakpoints 432013312..467664896 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS10_c0 : cellOk 432013312 433061888 = true := by decide +kernel
theorem NPosS10_c1 : cellOk 433061888 434110464 = true := by decide +kernel
theorem NPosS10_c2 : cellOk 434110464 435159040 = true := by decide +kernel
theorem NPosS10_c3 : cellOk 435159040 436207616 = true := by decide +kernel
theorem NPosS10_c4 : cellOk 436207616 437256192 = true := by decide +kernel
theorem NPosS10_c5 : cellOk 437256192 438304768 = true := by decide +kernel
theorem NPosS10_c6 : cellOk 438304768 439353344 = true := by decide +kernel
theorem NPosS10_c7 : cellOk 439353344 440401920 = true := by decide +kernel
theorem NPosS10_c8 : cellOk 440401920 440926208 = true := by decide +kernel
theorem NPosS10_c9 : cellOk 440926208 441450496 = true := by decide +kernel
theorem NPosS10_c10 : cellOk 441450496 441974784 = true := by decide +kernel
theorem NPosS10_c11 : cellOk 441974784 442499072 = true := by decide +kernel
theorem NPosS10_c12 : cellOk 442499072 443023360 = true := by decide +kernel
theorem NPosS10_c13 : cellOk 443023360 443547648 = true := by decide +kernel
theorem NPosS10_c14 : cellOk 443547648 444071936 = true := by decide +kernel
theorem NPosS10_c15 : cellOk 444071936 444596224 = true := by decide +kernel
theorem NPosS10_c16 : cellOk 444596224 445120512 = true := by decide +kernel
theorem NPosS10_c17 : cellOk 445120512 445644800 = true := by decide +kernel
theorem NPosS10_c18 : cellOk 445644800 446169088 = true := by decide +kernel
theorem NPosS10_c19 : cellOk 446169088 446693376 = true := by decide +kernel
theorem NPosS10_c20 : cellOk 446693376 447217664 = true := by decide +kernel
theorem NPosS10_c21 : cellOk 447217664 447741952 = true := by decide +kernel
theorem NPosS10_c22 : cellOk 447741952 448266240 = true := by decide +kernel
theorem NPosS10_c23 : cellOk 448266240 448790528 = true := by decide +kernel
theorem NPosS10_c24 : cellOk 448790528 449839104 = true := by decide +kernel
theorem NPosS10_c25 : cellOk 449839104 450887680 = true := by decide +kernel
theorem NPosS10_c26 : cellOk 450887680 451936256 = true := by decide +kernel
theorem NPosS10_c27 : cellOk 451936256 452984832 = true := by decide +kernel
theorem NPosS10_c28 : cellOk 452984832 454033408 = true := by decide +kernel
theorem NPosS10_c29 : cellOk 454033408 455081984 = true := by decide +kernel
theorem NPosS10_c30 : cellOk 455081984 456130560 = true := by decide +kernel
theorem NPosS10_c31 : cellOk 456130560 457179136 = true := by decide +kernel
theorem NPosS10_c32 : cellOk 457179136 457703424 = true := by decide +kernel
theorem NPosS10_c33 : cellOk 457703424 458227712 = true := by decide +kernel
theorem NPosS10_c34 : cellOk 458227712 458752000 = true := by decide +kernel
theorem NPosS10_c35 : cellOk 458752000 459276288 = true := by decide +kernel
theorem NPosS10_c36 : cellOk 459276288 459800576 = true := by decide +kernel
theorem NPosS10_c37 : cellOk 459800576 460324864 = true := by decide +kernel
theorem NPosS10_c38 : cellOk 460324864 460849152 = true := by decide +kernel
theorem NPosS10_c39 : cellOk 460849152 461373440 = true := by decide +kernel
theorem NPosS10_c40 : cellOk 461373440 461897728 = true := by decide +kernel
theorem NPosS10_c41 : cellOk 461897728 462422016 = true := by decide +kernel
theorem NPosS10_c42 : cellOk 462422016 462946304 = true := by decide +kernel
theorem NPosS10_c43 : cellOk 462946304 463470592 = true := by decide +kernel
theorem NPosS10_c44 : cellOk 463470592 463994880 = true := by decide +kernel
theorem NPosS10_c45 : cellOk 463994880 464519168 = true := by decide +kernel
theorem NPosS10_c46 : cellOk 464519168 465043456 = true := by decide +kernel
theorem NPosS10_c47 : cellOk 465043456 465567744 = true := by decide +kernel
theorem NPosS10_c48 : cellOk 465567744 466616320 = true := by decide +kernel
theorem NPosS10_c49 : cellOk 466616320 467664896 = true := by decide +kernel

theorem NPosS10_ok : chainOk [432013312, 433061888, 434110464, 435159040, 436207616, 437256192, 438304768, 439353344, 440401920, 440926208, 441450496, 441974784, 442499072, 443023360, 443547648, 444071936, 444596224, 445120512, 445644800, 446169088, 446693376, 447217664, 447741952, 448266240, 448790528, 449839104, 450887680, 451936256, 452984832, 454033408, 455081984, 456130560, 457179136, 457703424, 458227712, 458752000, 459276288, 459800576, 460324864, 460849152, 461373440, 461897728, 462422016, 462946304, 463470592, 463994880, 464519168, 465043456, 465567744, 466616320, 467664896] = true :=
  chainOk_cons NPosS10_c0 (chainOk_cons NPosS10_c1 (chainOk_cons NPosS10_c2 (chainOk_cons NPosS10_c3 (chainOk_cons NPosS10_c4 (chainOk_cons NPosS10_c5 (chainOk_cons NPosS10_c6 (chainOk_cons NPosS10_c7 (chainOk_cons NPosS10_c8 (chainOk_cons NPosS10_c9 (chainOk_cons NPosS10_c10 (chainOk_cons NPosS10_c11 (chainOk_cons NPosS10_c12 (chainOk_cons NPosS10_c13 (chainOk_cons NPosS10_c14 (chainOk_cons NPosS10_c15 (chainOk_cons NPosS10_c16 (chainOk_cons NPosS10_c17 (chainOk_cons NPosS10_c18 (chainOk_cons NPosS10_c19 (chainOk_cons NPosS10_c20 (chainOk_cons NPosS10_c21 (chainOk_cons NPosS10_c22 (chainOk_cons NPosS10_c23 (chainOk_cons NPosS10_c24 (chainOk_cons NPosS10_c25 (chainOk_cons NPosS10_c26 (chainOk_cons NPosS10_c27 (chainOk_cons NPosS10_c28 (chainOk_cons NPosS10_c29 (chainOk_cons NPosS10_c30 (chainOk_cons NPosS10_c31 (chainOk_cons NPosS10_c32 (chainOk_cons NPosS10_c33 (chainOk_cons NPosS10_c34 (chainOk_cons NPosS10_c35 (chainOk_cons NPosS10_c36 (chainOk_cons NPosS10_c37 (chainOk_cons NPosS10_c38 (chainOk_cons NPosS10_c39 (chainOk_cons NPosS10_c40 (chainOk_cons NPosS10_c41 (chainOk_cons NPosS10_c42 (chainOk_cons NPosS10_c43 (chainOk_cons NPosS10_c44 (chainOk_cons NPosS10_c45 (chainOk_cons NPosS10_c46 (chainOk_cons NPosS10_c47 (chainOk_cons NPosS10_c48 (chainOk_cons NPosS10_c49 (chainOk_single 467664896))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
