/- L5_2 shard NPosS6: 50 cells, breakpoints 286261248..324009984 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS6_c0 : cellOk 286261248 287309824 = true := by decide +kernel
theorem NPosS6_c1 : cellOk 287309824 288358400 = true := by decide +kernel
theorem NPosS6_c2 : cellOk 288358400 289406976 = true := by decide +kernel
theorem NPosS6_c3 : cellOk 289406976 290455552 = true := by decide +kernel
theorem NPosS6_c4 : cellOk 290455552 290979840 = true := by decide +kernel
theorem NPosS6_c5 : cellOk 290979840 291504128 = true := by decide +kernel
theorem NPosS6_c6 : cellOk 291504128 292028416 = true := by decide +kernel
theorem NPosS6_c7 : cellOk 292028416 292552704 = true := by decide +kernel
theorem NPosS6_c8 : cellOk 292552704 293076992 = true := by decide +kernel
theorem NPosS6_c9 : cellOk 293076992 293601280 = true := by decide +kernel
theorem NPosS6_c10 : cellOk 293601280 294125568 = true := by decide +kernel
theorem NPosS6_c11 : cellOk 294125568 294649856 = true := by decide +kernel
theorem NPosS6_c12 : cellOk 294649856 295174144 = true := by decide +kernel
theorem NPosS6_c13 : cellOk 295174144 295698432 = true := by decide +kernel
theorem NPosS6_c14 : cellOk 295698432 296222720 = true := by decide +kernel
theorem NPosS6_c15 : cellOk 296222720 296747008 = true := by decide +kernel
theorem NPosS6_c16 : cellOk 296747008 297795584 = true := by decide +kernel
theorem NPosS6_c17 : cellOk 297795584 298844160 = true := by decide +kernel
theorem NPosS6_c18 : cellOk 298844160 299892736 = true := by decide +kernel
theorem NPosS6_c19 : cellOk 299892736 300941312 = true := by decide +kernel
theorem NPosS6_c20 : cellOk 300941312 301989888 = true := by decide +kernel
theorem NPosS6_c21 : cellOk 301989888 303038464 = true := by decide +kernel
theorem NPosS6_c22 : cellOk 303038464 304087040 = true := by decide +kernel
theorem NPosS6_c23 : cellOk 304087040 305135616 = true := by decide +kernel
theorem NPosS6_c24 : cellOk 305135616 306184192 = true := by decide +kernel
theorem NPosS6_c25 : cellOk 306184192 307232768 = true := by decide +kernel
theorem NPosS6_c26 : cellOk 307232768 307757056 = true := by decide +kernel
theorem NPosS6_c27 : cellOk 307757056 308281344 = true := by decide +kernel
theorem NPosS6_c28 : cellOk 308281344 308805632 = true := by decide +kernel
theorem NPosS6_c29 : cellOk 308805632 309329920 = true := by decide +kernel
theorem NPosS6_c30 : cellOk 309329920 309854208 = true := by decide +kernel
theorem NPosS6_c31 : cellOk 309854208 310378496 = true := by decide +kernel
theorem NPosS6_c32 : cellOk 310378496 310902784 = true := by decide +kernel
theorem NPosS6_c33 : cellOk 310902784 311427072 = true := by decide +kernel
theorem NPosS6_c34 : cellOk 311427072 311951360 = true := by decide +kernel
theorem NPosS6_c35 : cellOk 311951360 312475648 = true := by decide +kernel
theorem NPosS6_c36 : cellOk 312475648 312999936 = true := by decide +kernel
theorem NPosS6_c37 : cellOk 312999936 313524224 = true := by decide +kernel
theorem NPosS6_c38 : cellOk 313524224 314048512 = true := by decide +kernel
theorem NPosS6_c39 : cellOk 314048512 314572800 = true := by decide +kernel
theorem NPosS6_c40 : cellOk 314572800 315621376 = true := by decide +kernel
theorem NPosS6_c41 : cellOk 315621376 316669952 = true := by decide +kernel
theorem NPosS6_c42 : cellOk 316669952 317718528 = true := by decide +kernel
theorem NPosS6_c43 : cellOk 317718528 318767104 = true := by decide +kernel
theorem NPosS6_c44 : cellOk 318767104 319815680 = true := by decide +kernel
theorem NPosS6_c45 : cellOk 319815680 320864256 = true := by decide +kernel
theorem NPosS6_c46 : cellOk 320864256 321912832 = true := by decide +kernel
theorem NPosS6_c47 : cellOk 321912832 322961408 = true := by decide +kernel
theorem NPosS6_c48 : cellOk 322961408 323485696 = true := by decide +kernel
theorem NPosS6_c49 : cellOk 323485696 324009984 = true := by decide +kernel

theorem NPosS6_ok : chainOk [286261248, 287309824, 288358400, 289406976, 290455552, 290979840, 291504128, 292028416, 292552704, 293076992, 293601280, 294125568, 294649856, 295174144, 295698432, 296222720, 296747008, 297795584, 298844160, 299892736, 300941312, 301989888, 303038464, 304087040, 305135616, 306184192, 307232768, 307757056, 308281344, 308805632, 309329920, 309854208, 310378496, 310902784, 311427072, 311951360, 312475648, 312999936, 313524224, 314048512, 314572800, 315621376, 316669952, 317718528, 318767104, 319815680, 320864256, 321912832, 322961408, 323485696, 324009984] = true :=
  chainOk_cons NPosS6_c0 (chainOk_cons NPosS6_c1 (chainOk_cons NPosS6_c2 (chainOk_cons NPosS6_c3 (chainOk_cons NPosS6_c4 (chainOk_cons NPosS6_c5 (chainOk_cons NPosS6_c6 (chainOk_cons NPosS6_c7 (chainOk_cons NPosS6_c8 (chainOk_cons NPosS6_c9 (chainOk_cons NPosS6_c10 (chainOk_cons NPosS6_c11 (chainOk_cons NPosS6_c12 (chainOk_cons NPosS6_c13 (chainOk_cons NPosS6_c14 (chainOk_cons NPosS6_c15 (chainOk_cons NPosS6_c16 (chainOk_cons NPosS6_c17 (chainOk_cons NPosS6_c18 (chainOk_cons NPosS6_c19 (chainOk_cons NPosS6_c20 (chainOk_cons NPosS6_c21 (chainOk_cons NPosS6_c22 (chainOk_cons NPosS6_c23 (chainOk_cons NPosS6_c24 (chainOk_cons NPosS6_c25 (chainOk_cons NPosS6_c26 (chainOk_cons NPosS6_c27 (chainOk_cons NPosS6_c28 (chainOk_cons NPosS6_c29 (chainOk_cons NPosS6_c30 (chainOk_cons NPosS6_c31 (chainOk_cons NPosS6_c32 (chainOk_cons NPosS6_c33 (chainOk_cons NPosS6_c34 (chainOk_cons NPosS6_c35 (chainOk_cons NPosS6_c36 (chainOk_cons NPosS6_c37 (chainOk_cons NPosS6_c38 (chainOk_cons NPosS6_c39 (chainOk_cons NPosS6_c40 (chainOk_cons NPosS6_c41 (chainOk_cons NPosS6_c42 (chainOk_cons NPosS6_c43 (chainOk_cons NPosS6_c44 (chainOk_cons NPosS6_c45 (chainOk_cons NPosS6_c46 (chainOk_cons NPosS6_c47 (chainOk_cons NPosS6_c48 (chainOk_cons NPosS6_c49 (chainOk_single 324009984))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
