/- L5_2 shard NPosS0: 50 cells, breakpoints 0..75497472 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS0_c0 : cellOk 0 8388608 = true := by decide +kernel
theorem NPosS0_c1 : cellOk 8388608 16777216 = true := by decide +kernel
theorem NPosS0_c2 : cellOk 16777216 20971520 = true := by decide +kernel
theorem NPosS0_c3 : cellOk 20971520 23068672 = true := by decide +kernel
theorem NPosS0_c4 : cellOk 23068672 24117248 = true := by decide +kernel
theorem NPosS0_c5 : cellOk 24117248 24641536 = true := by decide +kernel
theorem NPosS0_c6 : cellOk 24641536 24903680 = true := by decide +kernel
theorem NPosS0_c7 : cellOk 24903680 25034752 = true := by decide +kernel
theorem NPosS0_c8 : cellOk 25034752 25165824 = true := by decide +kernel
theorem NPosS0_c9 : cellOk 25165824 25296896 = true := by decide +kernel
theorem NPosS0_c10 : cellOk 25296896 25427968 = true := by decide +kernel
theorem NPosS0_c11 : cellOk 25427968 25690112 = true := by decide +kernel
theorem NPosS0_c12 : cellOk 25690112 26214400 = true := by decide +kernel
theorem NPosS0_c13 : cellOk 26214400 27262976 = true := by decide +kernel
theorem NPosS0_c14 : cellOk 27262976 29360128 = true := by decide +kernel
theorem NPosS0_c15 : cellOk 29360128 33554432 = true := by decide +kernel
theorem NPosS0_c16 : cellOk 33554432 37748736 = true := by decide +kernel
theorem NPosS0_c17 : cellOk 37748736 39845888 = true := by decide +kernel
theorem NPosS0_c18 : cellOk 39845888 40894464 = true := by decide +kernel
theorem NPosS0_c19 : cellOk 40894464 41418752 = true := by decide +kernel
theorem NPosS0_c20 : cellOk 41418752 41680896 = true := by decide +kernel
theorem NPosS0_c21 : cellOk 41680896 41943040 = true := by decide +kernel
theorem NPosS0_c22 : cellOk 41943040 42205184 = true := by decide +kernel
theorem NPosS0_c23 : cellOk 42205184 42467328 = true := by decide +kernel
theorem NPosS0_c24 : cellOk 42467328 42991616 = true := by decide +kernel
theorem NPosS0_c25 : cellOk 42991616 44040192 = true := by decide +kernel
theorem NPosS0_c26 : cellOk 44040192 46137344 = true := by decide +kernel
theorem NPosS0_c27 : cellOk 46137344 48234496 = true := by decide +kernel
theorem NPosS0_c28 : cellOk 48234496 50331648 = true := by decide +kernel
theorem NPosS0_c29 : cellOk 50331648 52428800 = true := by decide +kernel
theorem NPosS0_c30 : cellOk 52428800 54525952 = true := by decide +kernel
theorem NPosS0_c31 : cellOk 54525952 55574528 = true := by decide +kernel
theorem NPosS0_c32 : cellOk 55574528 56623104 = true := by decide +kernel
theorem NPosS0_c33 : cellOk 56623104 57671680 = true := by decide +kernel
theorem NPosS0_c34 : cellOk 57671680 58195968 = true := by decide +kernel
theorem NPosS0_c35 : cellOk 58195968 58720256 = true := by decide +kernel
theorem NPosS0_c36 : cellOk 58720256 59244544 = true := by decide +kernel
theorem NPosS0_c37 : cellOk 59244544 59768832 = true := by decide +kernel
theorem NPosS0_c38 : cellOk 59768832 60817408 = true := by decide +kernel
theorem NPosS0_c39 : cellOk 60817408 61865984 = true := by decide +kernel
theorem NPosS0_c40 : cellOk 61865984 62914560 = true := by decide +kernel
theorem NPosS0_c41 : cellOk 62914560 65011712 = true := by decide +kernel
theorem NPosS0_c42 : cellOk 65011712 67108864 = true := by decide +kernel
theorem NPosS0_c43 : cellOk 67108864 69206016 = true := by decide +kernel
theorem NPosS0_c44 : cellOk 69206016 71303168 = true := by decide +kernel
theorem NPosS0_c45 : cellOk 71303168 72351744 = true := by decide +kernel
theorem NPosS0_c46 : cellOk 72351744 73400320 = true := by decide +kernel
theorem NPosS0_c47 : cellOk 73400320 74448896 = true := by decide +kernel
theorem NPosS0_c48 : cellOk 74448896 74973184 = true := by decide +kernel
theorem NPosS0_c49 : cellOk 74973184 75497472 = true := by decide +kernel

theorem NPosS0_ok : chainOk [0, 8388608, 16777216, 20971520, 23068672, 24117248, 24641536, 24903680, 25034752, 25165824, 25296896, 25427968, 25690112, 26214400, 27262976, 29360128, 33554432, 37748736, 39845888, 40894464, 41418752, 41680896, 41943040, 42205184, 42467328, 42991616, 44040192, 46137344, 48234496, 50331648, 52428800, 54525952, 55574528, 56623104, 57671680, 58195968, 58720256, 59244544, 59768832, 60817408, 61865984, 62914560, 65011712, 67108864, 69206016, 71303168, 72351744, 73400320, 74448896, 74973184, 75497472] = true :=
  chainOk_cons NPosS0_c0 (chainOk_cons NPosS0_c1 (chainOk_cons NPosS0_c2 (chainOk_cons NPosS0_c3 (chainOk_cons NPosS0_c4 (chainOk_cons NPosS0_c5 (chainOk_cons NPosS0_c6 (chainOk_cons NPosS0_c7 (chainOk_cons NPosS0_c8 (chainOk_cons NPosS0_c9 (chainOk_cons NPosS0_c10 (chainOk_cons NPosS0_c11 (chainOk_cons NPosS0_c12 (chainOk_cons NPosS0_c13 (chainOk_cons NPosS0_c14 (chainOk_cons NPosS0_c15 (chainOk_cons NPosS0_c16 (chainOk_cons NPosS0_c17 (chainOk_cons NPosS0_c18 (chainOk_cons NPosS0_c19 (chainOk_cons NPosS0_c20 (chainOk_cons NPosS0_c21 (chainOk_cons NPosS0_c22 (chainOk_cons NPosS0_c23 (chainOk_cons NPosS0_c24 (chainOk_cons NPosS0_c25 (chainOk_cons NPosS0_c26 (chainOk_cons NPosS0_c27 (chainOk_cons NPosS0_c28 (chainOk_cons NPosS0_c29 (chainOk_cons NPosS0_c30 (chainOk_cons NPosS0_c31 (chainOk_cons NPosS0_c32 (chainOk_cons NPosS0_c33 (chainOk_cons NPosS0_c34 (chainOk_cons NPosS0_c35 (chainOk_cons NPosS0_c36 (chainOk_cons NPosS0_c37 (chainOk_cons NPosS0_c38 (chainOk_cons NPosS0_c39 (chainOk_cons NPosS0_c40 (chainOk_cons NPosS0_c41 (chainOk_cons NPosS0_c42 (chainOk_cons NPosS0_c43 (chainOk_cons NPosS0_c44 (chainOk_cons NPosS0_c45 (chainOk_cons NPosS0_c46 (chainOk_cons NPosS0_c47 (chainOk_cons NPosS0_c48 (chainOk_cons NPosS0_c49 (chainOk_single 75497472))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
