/- L5_2 shard NPosS5: 50 cells, breakpoints 246415360..286261248 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS5_c0 : cellOk 246415360 247463936 = true := by decide +kernel
theorem NPosS5_c1 : cellOk 247463936 248512512 = true := by decide +kernel
theorem NPosS5_c2 : cellOk 248512512 249561088 = true := by decide +kernel
theorem NPosS5_c3 : cellOk 249561088 250609664 = true := by decide +kernel
theorem NPosS5_c4 : cellOk 250609664 251658240 = true := by decide +kernel
theorem NPosS5_c5 : cellOk 251658240 252706816 = true := by decide +kernel
theorem NPosS5_c6 : cellOk 252706816 253755392 = true := by decide +kernel
theorem NPosS5_c7 : cellOk 253755392 254803968 = true := by decide +kernel
theorem NPosS5_c8 : cellOk 254803968 255852544 = true := by decide +kernel
theorem NPosS5_c9 : cellOk 255852544 256901120 = true := by decide +kernel
theorem NPosS5_c10 : cellOk 256901120 257425408 = true := by decide +kernel
theorem NPosS5_c11 : cellOk 257425408 257949696 = true := by decide +kernel
theorem NPosS5_c12 : cellOk 257949696 258473984 = true := by decide +kernel
theorem NPosS5_c13 : cellOk 258473984 258998272 = true := by decide +kernel
theorem NPosS5_c14 : cellOk 258998272 259522560 = true := by decide +kernel
theorem NPosS5_c15 : cellOk 259522560 260046848 = true := by decide +kernel
theorem NPosS5_c16 : cellOk 260046848 260571136 = true := by decide +kernel
theorem NPosS5_c17 : cellOk 260571136 261095424 = true := by decide +kernel
theorem NPosS5_c18 : cellOk 261095424 261619712 = true := by decide +kernel
theorem NPosS5_c19 : cellOk 261619712 262144000 = true := by decide +kernel
theorem NPosS5_c20 : cellOk 262144000 262668288 = true := by decide +kernel
theorem NPosS5_c21 : cellOk 262668288 263192576 = true := by decide +kernel
theorem NPosS5_c22 : cellOk 263192576 264241152 = true := by decide +kernel
theorem NPosS5_c23 : cellOk 264241152 265289728 = true := by decide +kernel
theorem NPosS5_c24 : cellOk 265289728 266338304 = true := by decide +kernel
theorem NPosS5_c25 : cellOk 266338304 267386880 = true := by decide +kernel
theorem NPosS5_c26 : cellOk 267386880 268435456 = true := by decide +kernel
theorem NPosS5_c27 : cellOk 268435456 269484032 = true := by decide +kernel
theorem NPosS5_c28 : cellOk 269484032 270532608 = true := by decide +kernel
theorem NPosS5_c29 : cellOk 270532608 271581184 = true := by decide +kernel
theorem NPosS5_c30 : cellOk 271581184 272629760 = true := by decide +kernel
theorem NPosS5_c31 : cellOk 272629760 273678336 = true := by decide +kernel
theorem NPosS5_c32 : cellOk 273678336 274202624 = true := by decide +kernel
theorem NPosS5_c33 : cellOk 274202624 274726912 = true := by decide +kernel
theorem NPosS5_c34 : cellOk 274726912 275251200 = true := by decide +kernel
theorem NPosS5_c35 : cellOk 275251200 275775488 = true := by decide +kernel
theorem NPosS5_c36 : cellOk 275775488 276299776 = true := by decide +kernel
theorem NPosS5_c37 : cellOk 276299776 276824064 = true := by decide +kernel
theorem NPosS5_c38 : cellOk 276824064 277348352 = true := by decide +kernel
theorem NPosS5_c39 : cellOk 277348352 277872640 = true := by decide +kernel
theorem NPosS5_c40 : cellOk 277872640 278396928 = true := by decide +kernel
theorem NPosS5_c41 : cellOk 278396928 278921216 = true := by decide +kernel
theorem NPosS5_c42 : cellOk 278921216 279445504 = true := by decide +kernel
theorem NPosS5_c43 : cellOk 279445504 279969792 = true := by decide +kernel
theorem NPosS5_c44 : cellOk 279969792 281018368 = true := by decide +kernel
theorem NPosS5_c45 : cellOk 281018368 282066944 = true := by decide +kernel
theorem NPosS5_c46 : cellOk 282066944 283115520 = true := by decide +kernel
theorem NPosS5_c47 : cellOk 283115520 284164096 = true := by decide +kernel
theorem NPosS5_c48 : cellOk 284164096 285212672 = true := by decide +kernel
theorem NPosS5_c49 : cellOk 285212672 286261248 = true := by decide +kernel

theorem NPosS5_ok : chainOk [246415360, 247463936, 248512512, 249561088, 250609664, 251658240, 252706816, 253755392, 254803968, 255852544, 256901120, 257425408, 257949696, 258473984, 258998272, 259522560, 260046848, 260571136, 261095424, 261619712, 262144000, 262668288, 263192576, 264241152, 265289728, 266338304, 267386880, 268435456, 269484032, 270532608, 271581184, 272629760, 273678336, 274202624, 274726912, 275251200, 275775488, 276299776, 276824064, 277348352, 277872640, 278396928, 278921216, 279445504, 279969792, 281018368, 282066944, 283115520, 284164096, 285212672, 286261248] = true :=
  chainOk_cons NPosS5_c0 (chainOk_cons NPosS5_c1 (chainOk_cons NPosS5_c2 (chainOk_cons NPosS5_c3 (chainOk_cons NPosS5_c4 (chainOk_cons NPosS5_c5 (chainOk_cons NPosS5_c6 (chainOk_cons NPosS5_c7 (chainOk_cons NPosS5_c8 (chainOk_cons NPosS5_c9 (chainOk_cons NPosS5_c10 (chainOk_cons NPosS5_c11 (chainOk_cons NPosS5_c12 (chainOk_cons NPosS5_c13 (chainOk_cons NPosS5_c14 (chainOk_cons NPosS5_c15 (chainOk_cons NPosS5_c16 (chainOk_cons NPosS5_c17 (chainOk_cons NPosS5_c18 (chainOk_cons NPosS5_c19 (chainOk_cons NPosS5_c20 (chainOk_cons NPosS5_c21 (chainOk_cons NPosS5_c22 (chainOk_cons NPosS5_c23 (chainOk_cons NPosS5_c24 (chainOk_cons NPosS5_c25 (chainOk_cons NPosS5_c26 (chainOk_cons NPosS5_c27 (chainOk_cons NPosS5_c28 (chainOk_cons NPosS5_c29 (chainOk_cons NPosS5_c30 (chainOk_cons NPosS5_c31 (chainOk_cons NPosS5_c32 (chainOk_cons NPosS5_c33 (chainOk_cons NPosS5_c34 (chainOk_cons NPosS5_c35 (chainOk_cons NPosS5_c36 (chainOk_cons NPosS5_c37 (chainOk_cons NPosS5_c38 (chainOk_cons NPosS5_c39 (chainOk_cons NPosS5_c40 (chainOk_cons NPosS5_c41 (chainOk_cons NPosS5_c42 (chainOk_cons NPosS5_c43 (chainOk_cons NPosS5_c44 (chainOk_cons NPosS5_c45 (chainOk_cons NPosS5_c46 (chainOk_cons NPosS5_c47 (chainOk_cons NPosS5_c48 (chainOk_cons NPosS5_c49 (chainOk_single 286261248))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
