/- L5_2 shard NPosS1: 50 cells, breakpoints 75497472..125829120 (scale 2^-24). Generated by py/gen_shards.py. -/
import ZetaS.Majorant.MajCheck
namespace ZetaS.MajCheck

theorem NPosS1_c0 : cellOk 75497472 76021760 = true := by decide +kernel
theorem NPosS1_c1 : cellOk 76021760 76546048 = true := by decide +kernel
theorem NPosS1_c2 : cellOk 76546048 77594624 = true := by decide +kernel
theorem NPosS1_c3 : cellOk 77594624 78643200 = true := by decide +kernel
theorem NPosS1_c4 : cellOk 78643200 79691776 = true := by decide +kernel
theorem NPosS1_c5 : cellOk 79691776 81788928 = true := by decide +kernel
theorem NPosS1_c6 : cellOk 81788928 83886080 = true := by decide +kernel
theorem NPosS1_c7 : cellOk 83886080 85983232 = true := by decide +kernel
theorem NPosS1_c8 : cellOk 85983232 88080384 = true := by decide +kernel
theorem NPosS1_c9 : cellOk 88080384 89128960 = true := by decide +kernel
theorem NPosS1_c10 : cellOk 89128960 90177536 = true := by decide +kernel
theorem NPosS1_c11 : cellOk 90177536 90701824 = true := by decide +kernel
theorem NPosS1_c12 : cellOk 90701824 91226112 = true := by decide +kernel
theorem NPosS1_c13 : cellOk 91226112 91750400 = true := by decide +kernel
theorem NPosS1_c14 : cellOk 91750400 92274688 = true := by decide +kernel
theorem NPosS1_c15 : cellOk 92274688 92798976 = true := by decide +kernel
theorem NPosS1_c16 : cellOk 92798976 93323264 = true := by decide +kernel
theorem NPosS1_c17 : cellOk 93323264 93847552 = true := by decide +kernel
theorem NPosS1_c18 : cellOk 93847552 94371840 = true := by decide +kernel
theorem NPosS1_c19 : cellOk 94371840 95420416 = true := by decide +kernel
theorem NPosS1_c20 : cellOk 95420416 96468992 = true := by decide +kernel
theorem NPosS1_c21 : cellOk 96468992 98566144 = true := by decide +kernel
theorem NPosS1_c22 : cellOk 98566144 100663296 = true := by decide +kernel
theorem NPosS1_c23 : cellOk 100663296 102760448 = true := by decide +kernel
theorem NPosS1_c24 : cellOk 102760448 103809024 = true := by decide +kernel
theorem NPosS1_c25 : cellOk 103809024 104857600 = true := by decide +kernel
theorem NPosS1_c26 : cellOk 104857600 105906176 = true := by decide +kernel
theorem NPosS1_c27 : cellOk 105906176 106954752 = true := by decide +kernel
theorem NPosS1_c28 : cellOk 106954752 107479040 = true := by decide +kernel
theorem NPosS1_c29 : cellOk 107479040 108003328 = true := by decide +kernel
theorem NPosS1_c30 : cellOk 108003328 108527616 = true := by decide +kernel
theorem NPosS1_c31 : cellOk 108527616 109051904 = true := by decide +kernel
theorem NPosS1_c32 : cellOk 109051904 109576192 = true := by decide +kernel
theorem NPosS1_c33 : cellOk 109576192 110100480 = true := by decide +kernel
theorem NPosS1_c34 : cellOk 110100480 110624768 = true := by decide +kernel
theorem NPosS1_c35 : cellOk 110624768 111149056 = true := by decide +kernel
theorem NPosS1_c36 : cellOk 111149056 112197632 = true := by decide +kernel
theorem NPosS1_c37 : cellOk 112197632 113246208 = true := by decide +kernel
theorem NPosS1_c38 : cellOk 113246208 114294784 = true := by decide +kernel
theorem NPosS1_c39 : cellOk 114294784 115343360 = true := by decide +kernel
theorem NPosS1_c40 : cellOk 115343360 117440512 = true := by decide +kernel
theorem NPosS1_c41 : cellOk 117440512 119537664 = true := by decide +kernel
theorem NPosS1_c42 : cellOk 119537664 120586240 = true := by decide +kernel
theorem NPosS1_c43 : cellOk 120586240 121634816 = true := by decide +kernel
theorem NPosS1_c44 : cellOk 121634816 122683392 = true := by decide +kernel
theorem NPosS1_c45 : cellOk 122683392 123731968 = true := by decide +kernel
theorem NPosS1_c46 : cellOk 123731968 124256256 = true := by decide +kernel
theorem NPosS1_c47 : cellOk 124256256 124780544 = true := by decide +kernel
theorem NPosS1_c48 : cellOk 124780544 125304832 = true := by decide +kernel
theorem NPosS1_c49 : cellOk 125304832 125829120 = true := by decide +kernel

theorem NPosS1_ok : chainOk [75497472, 76021760, 76546048, 77594624, 78643200, 79691776, 81788928, 83886080, 85983232, 88080384, 89128960, 90177536, 90701824, 91226112, 91750400, 92274688, 92798976, 93323264, 93847552, 94371840, 95420416, 96468992, 98566144, 100663296, 102760448, 103809024, 104857600, 105906176, 106954752, 107479040, 108003328, 108527616, 109051904, 109576192, 110100480, 110624768, 111149056, 112197632, 113246208, 114294784, 115343360, 117440512, 119537664, 120586240, 121634816, 122683392, 123731968, 124256256, 124780544, 125304832, 125829120] = true :=
  chainOk_cons NPosS1_c0 (chainOk_cons NPosS1_c1 (chainOk_cons NPosS1_c2 (chainOk_cons NPosS1_c3 (chainOk_cons NPosS1_c4 (chainOk_cons NPosS1_c5 (chainOk_cons NPosS1_c6 (chainOk_cons NPosS1_c7 (chainOk_cons NPosS1_c8 (chainOk_cons NPosS1_c9 (chainOk_cons NPosS1_c10 (chainOk_cons NPosS1_c11 (chainOk_cons NPosS1_c12 (chainOk_cons NPosS1_c13 (chainOk_cons NPosS1_c14 (chainOk_cons NPosS1_c15 (chainOk_cons NPosS1_c16 (chainOk_cons NPosS1_c17 (chainOk_cons NPosS1_c18 (chainOk_cons NPosS1_c19 (chainOk_cons NPosS1_c20 (chainOk_cons NPosS1_c21 (chainOk_cons NPosS1_c22 (chainOk_cons NPosS1_c23 (chainOk_cons NPosS1_c24 (chainOk_cons NPosS1_c25 (chainOk_cons NPosS1_c26 (chainOk_cons NPosS1_c27 (chainOk_cons NPosS1_c28 (chainOk_cons NPosS1_c29 (chainOk_cons NPosS1_c30 (chainOk_cons NPosS1_c31 (chainOk_cons NPosS1_c32 (chainOk_cons NPosS1_c33 (chainOk_cons NPosS1_c34 (chainOk_cons NPosS1_c35 (chainOk_cons NPosS1_c36 (chainOk_cons NPosS1_c37 (chainOk_cons NPosS1_c38 (chainOk_cons NPosS1_c39 (chainOk_cons NPosS1_c40 (chainOk_cons NPosS1_c41 (chainOk_cons NPosS1_c42 (chainOk_cons NPosS1_c43 (chainOk_cons NPosS1_c44 (chainOk_cons NPosS1_c45 (chainOk_cons NPosS1_c46 (chainOk_cons NPosS1_c47 (chainOk_cons NPosS1_c48 (chainOk_cons NPosS1_c49 (chainOk_single 125829120))))))))))))))))))))))))))))))))))))))))))))))))))

end ZetaS.MajCheck
